/**
 * Field + Input — labelled form controls with correct wiring.
 *
 * <Field> owns the label/hint/error plumbing (ids, aria-describedby,
 * aria-invalid) and renders any control via a render-prop-free children
 * clone; <Input> is the styled text control.
 *
 * Usage:
 *   <Field label="Team name" hint="Shown in the league hub">
 *     <Input value={v} onChange={...} />
 *   </Field>
 *   <Field label="FAAB bid" error="Must be a number">
 *     <Input inputMode="numeric" data-numeric />
 *   </Field>
 *
 * Props (Field): label, hint, error, id (optional — autogenerated), children
 * Props (Input): any native input prop; `data-numeric` applies the mono
 *   tabular-nums treatment for value entry.
 *
 * A11y: label is a real <label htmlFor>; error text is linked via
 * aria-describedby and flips aria-invalid on the control.
 */
"use client";

import React, { useId } from "react";

export function Field({ label, hint, error, id, children }) {
  const autoId = useId();
  const controlId = id || `ds-field-${autoId}`;
  const hintId = hint ? `${controlId}-hint` : undefined;
  const errorId = error ? `${controlId}-error` : undefined;
  const describedBy =
    [errorId, hintId].filter(Boolean).join(" ") || undefined;

  const control = React.Children.only(children);
  const wired = React.cloneElement(control, {
    id: controlId,
    "aria-describedby": describedBy,
    "aria-invalid": error ? true : undefined,
  });

  return (
    <div className="ds-field">
      {label ? (
        <label className="ds-label" htmlFor={controlId}>
          {label}
        </label>
      ) : null}
      {wired}
      {/* Error and hint BOTH render when both exist (error first, hint as
          quiet guidance) — the hint matters most while the user is fixing
          invalid input, and aria-describedby references both ids so
          neither is ever dangling. */}
      {error ? (
        <span className="ds-error-text" id={errorId}>
          {error}
        </span>
      ) : null}
      {hint ? (
        <span className="ds-hint" id={hintId}>
          {hint}
        </span>
      ) : null}
    </div>
  );
}

export function Input({ className = "", "data-numeric": numeric, ...rest }) {
  const classes = ["ds-input", numeric !== undefined ? "ds-mono" : "", className]
    .filter(Boolean)
    .join(" ");
  return <input className={classes} {...rest} />;
}
