/**
 * TradeWarRoom (#792 / #1173 / #843 / #842, Lane 6).
 *
 * Payloads are REAL `POST /api/trade/analyze` output: generated by
 * `tests/trade/war_room_ui_payloads.py` through `simulate_trade` +
 * `analyze_trade`, and `tests/trade/test_war_room_ui_fixtures.py` fails if
 * the backend stops emitting exactly these.  So a number asserted here is the
 * number the API publishes, formatted — the component computes nothing.
 */
import { act, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import TradeWarRoom from "@/components/trade/TradeWarRoom";
import {
  RECOMMENDATION_LABELS,
  formatSignedPpg,
  formatSignedValue,
  tradeRequestForTeam,
  validAnalyzePayload,
} from "@/lib/trade-war-room";

import CONSOLIDATION from "../fixtures/trade-war-room/consolidation.json";
import FORCED from "../fixtures/trade-war-room/forced-cut.json";
import ASSET_ONLY from "../fixtures/trade-war-room/asset-only.json";
import PARTIAL from "../fixtures/trade-war-room/partial-coverage.json";

const req = (fixture) => ({ ...fixture._fixture.request, mySide: 0 });

function ok(body) {
  return { ok: true, status: 200, json: async () => body };
}

function deferred() {
  let resolve;
  const promise = new Promise((r) => (resolve = r));
  return { promise, resolve };
}

async function settle() {
  await act(async () => {
    vi.advanceTimersByTime(800);
  });
  await act(async () => {});
}

async function renderWith(fixture, props = {}) {
  globalThis.fetch = vi.fn(async () => ok(fixture));
  const view = render(
    <TradeWarRoom
      request={req(fixture)}
      leagueKey="main"
      useTeamContext={fixture._fixture.request.useTeamContext}
      {...props}
    />,
  );
  await settle();
  return view;
}

function lens(name) {
  return document.querySelector(`[data-lens="${name}"]`);
}

beforeEach(() => {
  vi.useFakeTimers({ shouldAdvanceTime: true });
});

afterEach(() => {
  vi.useRealTimers();
  vi.restoreAllMocks();
});

describe("TradeWarRoom — the packet, verbatim", () => {
  it("leads with the recommendation, then three separate answers", async () => {
    await renderWith(CONSOLIDATION);
    const a = CONSOLIDATION.analysis;
    expect(screen.getByText(RECOMMENDATION_LABELS[a.recommendation])).toBeInTheDocument();
    expect(screen.getByText(`${a.confidence.toLowerCase()} confidence`)).toBeInTheDocument();
    // Market: the VA gap exactly as published.
    expect(
      within(lens("market")).getByText(formatSignedValue(a.lenses.market.detail.vaAdjustedGap)),
    ).toBeInTheDocument();
    // Roster: best-ball points per week, not a value index.
    expect(within(lens("roster")).getByText(formatSignedPpg(a.lenses.roster.detail.ppg))).toBeInTheDocument();
    expect(within(lens("roster")).getByText(/best-ball pts \/ week/)).toBeInTheDocument();
    // Feasibility.
    expect(within(lens("feasibility")).getByText("Fits — no cut needed")).toBeInTheDocument();
    expect(within(lens("feasibility")).getByText(/picks don't use roster spots/)).toBeInTheDocument();
    // Reasons both ways — dissent is shown, not hidden.
    for (const r of [...a.reasonsFor, ...a.reasonsAgainst]) expect(screen.getByText(r)).toBeInTheDocument();
  });

  it("shows lineup entry per affected player, with missing as words", async () => {
    await renderWith(CONSOLIDATION);
    const table = screen.getByRole("table", { name: /Lineup entry/ });
    const star = within(table).getByRole("row", { name: /WR Buf Star/ });
    expect(within(star).getByText("In")).toBeInTheDocument();
    expect(within(star).getByText("100%")).toBeInTheDocument();
    // Before the trade he was not on the roster: "—", never 0%.
    expect(within(star).getByText("—")).toBeInTheDocument();
  });

  it("a forced cut shows the likely cut and the gain before and after cleanup", async () => {
    await renderWith(FORCED);
    const f = within(lens("feasibility"));
    expect(f.getByText("Roster full — cut required")).toBeInTheDocument();
    expect(f.getByText(/likely cut: Ghost Player/)).toBeInTheDocument();
    const r = FORCED.analysis.lenses.roster.detail;
    expect(
      within(lens("roster")).getByText(
        `${formatSignedPpg(r.ppgBeforeCleanup)} before the required cut · ${formatSignedPpg(r.ppg)} once the roster is legal`,
      ),
    ).toBeInTheDocument();
  });

  it("Asset-Only excludes roster and feasibility by mode, and says so", async () => {
    await renderWith(ASSET_ONLY);
    expect(screen.getByRole("radio", { name: "Asset only" })).toBeChecked();
    expect(screen.getByText(/roster fit, lineup impact and roster capacity are not included/)).toBeInTheDocument();
    expect(within(lens("roster")).getAllByText("Not included in Asset-Only analysis").length).toBeGreaterThan(0);
    expect(within(lens("feasibility")).getAllByText("Not included in Asset-Only analysis").length).toBeGreaterThan(0);
    expect(screen.queryByRole("table", { name: /Lineup entry/ })).toBeNull();
  });

  it("partial projection coverage abstains, labelled, and leads the uncertainty", async () => {
    await renderWith(PARTIAL);
    expect(within(lens("roster")).getByText(/\(partial\)/)).toBeInTheDocument();
    expect(
      within(lens("roster")).getByText("Abstains — a traded player has no projection"),
    ).toBeInTheDocument();
    expect(screen.getByText(PARTIAL.analysis.topUncertainty, { selector: "p" })).toBeInTheDocument();
    const table = screen.getByRole("table", { name: /Lineup entry/ });
    expect(within(table).getByText("No projection")).toBeInTheDocument();
  });

  it("details disclose KTC VA, the projection basis and what is not included", async () => {
    await renderWith(CONSOLIDATION);
    fireEvent.click(screen.getByRole("button", { name: "How this was decided" }));
    expect(screen.getByText(/KTC VA is a separate market lens/)).toBeInTheDocument();
    expect(screen.getByText(/SYNTHETIC_FIXTURE_PROJECTIONS/)).toBeInTheDocument();
    expect(screen.getByText("strategicPosture")).toBeInTheDocument();
    expect(screen.getByText("currentSeasonEquity")).toBeInTheDocument();
  });
});

describe("TradeWarRoom — requests and identity", () => {
  it("asks the backend the exact question, in the selected league and mode", async () => {
    await renderWith(CONSOLIDATION);
    const [url, init] = globalThis.fetch.mock.calls[0];
    expect(url).toBe("/api/trade/analyze");
    const body = JSON.parse(init.body);
    expect(body).toMatchObject({
      leagueKey: "main",
      teamName: "Us",
      playersIn: ["WR Buf Star"],
      playersOut: ["WR Kc", "WR Phi"],
      useTeamContext: true,
    });
  });

  it("the mode control asks the page to change mode", async () => {
    const onChange = vi.fn();
    await renderWith(CONSOLIDATION, { onTeamContextChange: onChange });
    fireEvent.click(screen.getByRole("radio", { name: "Asset only" }));
    expect(onChange).toHaveBeenCalledWith(false);
  });

  it("refuses an answer for the other mode", async () => {
    globalThis.fetch = vi.fn(async () => ok(ASSET_ONLY)); // asset-only answer...
    render(<TradeWarRoom request={req(CONSOLIDATION)} leagueKey="main" useTeamContext />); // ...to a team question
    await settle();
    expect(screen.getByText(/Analysis unavailable right now \(invalid_analysis\)/)).toBeInTheDocument();
    expect(screen.queryByText(RECOMMENDATION_LABELS.MAKE)).toBeNull();
  });

  it("a late answer to an earlier trade never publishes", async () => {
    const first = deferred();
    globalThis.fetch = vi
      .fn()
      .mockImplementationOnce(() => first.promise)
      .mockResolvedValueOnce(ok(FORCED));
    const view = render(<TradeWarRoom request={req(CONSOLIDATION)} leagueKey="main" useTeamContext />);
    await settle();
    view.rerender(<TradeWarRoom request={req(FORCED)} leagueKey="main" useTeamContext />);
    await settle();
    expect(within(lens("feasibility")).getByText("Roster full — cut required")).toBeInTheDocument();
    await act(async () => first.resolve(ok(CONSOLIDATION)));
    expect(within(lens("feasibility")).getByText("Roster full — cut required")).toBeInTheDocument();
    expect(screen.queryByText("Fits — no cut needed")).toBeNull();
  });

  it("with only the assets changed, the previous answer stays visible and marked updating", async () => {
    const { rerender } = await renderWith(CONSOLIDATION);
    globalThis.fetch = vi.fn(() => new Promise(() => {}));
    rerender(<TradeWarRoom request={req(FORCED)} leagueKey="main" useTeamContext />);
    await act(async () => {});
    expect(screen.getByText("Updating for your latest change…")).toBeInTheDocument();
    expect(screen.getByText("Fits — no cut needed")).toBeInTheDocument();
    expect(document.querySelector('[data-war-room="updating"]')).not.toBeNull();
  });

  it("with the mode changed, the previous verdict is blanked", async () => {
    const { rerender } = await renderWith(CONSOLIDATION);
    globalThis.fetch = vi.fn(() => new Promise(() => {}));
    rerender(<TradeWarRoom request={req(CONSOLIDATION)} leagueKey="main" useTeamContext={false} />);
    await act(async () => {});
    expect(screen.getByText("Analyzing this trade…")).toBeInTheDocument();
    expect(screen.queryByText(RECOMMENDATION_LABELS[CONSOLIDATION.analysis.recommendation])).toBeNull();
  });
});

describe("TradeWarRoom — idle states", () => {
  it("asks for a team when none is selected", () => {
    render(<TradeWarRoom request={null} leagueKey="main" useTeamContext />);
    expect(screen.getByText("Pick your team to see what this trade does to your roster.")).toBeInTheDocument();
  });

  it("asks for both sides when one is empty", () => {
    render(
      <TradeWarRoom
        request={{ teamName: "Us", playersIn: ["X"], playersOut: [], picksIn: [], picksOut: [] }}
        leagueKey="main"
        useTeamContext
      />,
    );
    expect(screen.getByText(/Add assets to both sides/)).toBeInTheDocument();
  });
});

describe("trade-war-room lib", () => {
  it("maps the side holding the team's players to OUT", () => {
    const sides = [
      { assets: [{ name: "Theirs" }] },
      { assets: [{ name: "Mine A" }, { name: "2027 Round 1", assetId: "p1", assetLabel: "2027 1st (own)" }] },
    ];
    const r = tradeRequestForTeam(sides, new Set(["Mine A"]), "Us");
    expect(r).toMatchObject({
      mySide: 1,
      playersOut: ["Mine A"],
      picksOut: ["2027 1st (own)"],
      playersIn: ["Theirs"],
    });
  });

  it("refuses malformed or mismatched payloads", () => {
    expect(validAnalyzePayload(null)).toBe(false);
    expect(validAnalyzePayload({ ...CONSOLIDATION, analysis: { recommendation: "MAYBE" } })).toBe(false);
    expect(validAnalyzePayload(CONSOLIDATION, { leagueKey: "other" })).toBe(false);
    expect(validAnalyzePayload(CONSOLIDATION, { leagueKey: "main", useTeamContext: true })).toBe(true);
  });
});
