"""Generate docs/master-site-audit/evidence/W30/formula-inventory.csv.

One row per formula found at HEAD by workstream W30.  Written as a script
so the CSV quoting is correct and the file is regenerable.
"""

from __future__ import annotations

import csv
import pathlib

COLS = [
    "id",
    "concept",
    "expression",
    "file:lines",
    "inputs",
    "units",
    "scale/range",
    "consumers",
    "source/rationale",
    "version",
    "tests",
    "assumptions",
    "possible double-count",
    "possible leakage",
    "duplicate-of",
    "verdict",
]

R = []


def add(*vals):
    assert len(vals) == len(COLS), (len(vals), vals[0])
    R.append(dict(zip(COLS, vals)))


# ─────────────────────────────────────────────────────────────────────
# 1. PLAYER VALUE / THE BOARD
# ─────────────────────────────────────────────────────────────────────
add(
    "F-001",
    "Player value (canonical board)",
    "rankDerivedValue = count_aware_blend(per-source Hill(percentile(rank))) then "
    "TE-basis lift -> Hampel -> shrinkage(IDP/picks) -> single-source haircut(0.30) "
    "-> corridor clamp(IDP) -> two-way max() -> pick year discount -> pick tethering",
    "src/api/data_contract.py::_compute_unified_rankings (~5290-6900)",
    "per-source ranks + value-direct votes from _RANKING_SOURCES; scope master curves",
    "internal value points",
    "0-9999 (_DISPLAY_SCALE_MAX=9999)",
    "/api/data, /rankings, every trade engine, /terminal, /waivers, /angle, /arbitrage",
    "CLAUDE.md 'Live Value Pipeline'; the one live valuation path",
    "contract 2026-03-10.v2",
    "tests/api/test_source_overrides.py, tests/api/test_data_contract*.py",
    "a fixed 500-rank percentile reference; ranks past 500 clamp to the curve tail",
    "TE lift + TEP-native flat 1.10 both touch TE rows; guarded by from==to no-op",
    "none — value-only, no roster inputs",
    "-",
    "Implemented and verified",
)
add(
    "F-002",
    "Player value (scraper composite)",
    "_composite / _finalAdjusted / _rawComposite — the pre-canonical scraper blend",
    "Dynasty Scraper.py (_market_confidence, composite build)",
    "raw source CSVs",
    "scraper points",
    "site-specific",
    "written into data/dynasty_data_*.json; read by data_contract as INPUT only",
    "legacy scraper scale kept as an input snapshot, not a board",
    "n/a",
    "tests/audit/test_formula_registry.py::test_value_bundle_scale_contract_is_enforced",
    "assumed never surfaced as a user-visible value",
    "would double-count if re-blended with rankDerivedValue",
    "leaked to /arbitrage until 2026-07-27 (WS-J F-6); now fixed",
    "F-001 (different concept, retained)",
    "Deprecated but still active",
)
add(
    "F-003",
    "Fundamental value (BDVM)",
    "to_trade_value(strategy capitals) — surplus over dynamic replacement, "
    "CES package math (Sum v^theta)^(1/theta) - C_spot*overflow",
    "src/bdvm/engine.py::to_trade_value; src/bdvm/trade_math.py:35-38",
    "projection snapshots under data/bdvm/projections/, league scoring, aging curves",
    "fundamental value points",
    "model-scaled, not 0-9999",
    "/api/bdvm/values|roster|trades|trade-eval, /bdvm, /rankings Fund-gap col, /draft",
    "docs/research/bdvm-v1/ — an independent value CONCEPT, never merged into F-001",
    "modelVersion + content-hashed paramSetId",
    "tests/bdvm/ (engine parity vs frozen Appendix-C fixture)",
    "projections exist; without a snapshot the endpoint says so",
    "explicitly never written to rankDerivedValue",
    "market layer runs strictly after fundamentals; zero market input to fundamentals",
    "-",
    "Blocked by data (data/bdvm/ absent in this container)",
)
add(
    "F-004",
    "Value bundle scale contract",
    "overall/finalAdjusted/displayValue = None unless the row carries canonical stamps; "
    "rawComposite passes the scraper number through",
    "src/api/data_contract.py::_player_value_bundle:8675",
    "player dict",
    "internal value points",
    "0-9999 or None",
    "every /api/data row",
    "formula-registry value-bundle-scale",
    "-",
    "tests/audit/test_formula_registry.py:157-163",
    "None is rendered as 'unpriced', never as 0",
    "-",
    "-",
    "-",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 2. RANK <-> VALUE
# ─────────────────────────────────────────────────────────────────────
add(
    "F-010",
    "Rank -> value (Hill, backend)",
    "v = 1 + 9998 / (1 + ((rank-1)/HILL_MIDPOINT)^HILL_SLOPE); "
    "OFFENSE/GLOBAL/ROOKIE share 65.4/0.91, IDP uses 64.6/0.90",
    "src/canonical/player_valuation.py::rank_to_value:287, rank_to_value_for_scope:313",
    "rank, scope",
    "value points",
    "1..9999",
    "src/api/rank_history.py:72, src/api/terminal.py:38",
    "reconstruction path for history rows that stored a rank but no value",
    "constants committed in-module",
    "tests/api/test_rank_form_frontend_parity.py",
    "scope routing is a no-op for OFFENSE vs GLOBAL vs ROOKIE at HEAD (measured identical)",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-011",
    "Rank -> value (Hill, frontend)",
    "Math.round(1 + span/(1 + ((r-1)/midpoint)^slope)) with {65.4, 0.91, 9998}",
    "frontend/lib/value-history.js::valueFromRank:349 (RANK_FORM_CURVE:333)",
    "rank",
    "value points",
    "1..9999",
    "frontend/components/terminal/TeamCommandHeader.jsx, TeamValueChart.jsx",
    "avoids one API call per history point on /terminal",
    "hardcoded object mirrored from Python",
    "tests/api/test_rank_form_frontend_parity.py",
    "the two constants stay in lockstep — enforced by a test, not by import",
    "-",
    "-",
    "F-010 (verified numerically identical at 15 ranks, W30 rank-to-value-js-vs-py.json)",
    "Duplicate or conflicting implementation (currently in agreement)",
)
add(
    "F-012",
    "Value -> rank (closed-form inverse)",
    "r = 1 + midpoint * (span/(v-1) - 1)^(1/slope)",
    "frontend/lib/value-history.js::rankFromValue:371",
    "blended value",
    "rank ordinal",
    ">=1 or null outside the invertible domain",
    "frontend/components/PlayerRankHistoryChart.jsx:268",
    "derives a rank line for snapshots that persisted value but not rank",
    "-",
    "frontend/__tests__ value-history",
    "the board's value came from this exact curve (it did not — F-001 did)",
    "-",
    "a derived rank can be mistaken for a stamped one on the chart",
    "F-010",
    "Implemented and verified",
)
add(
    "F-013",
    "Rank -> value (scraper)",
    "_calibrated_rank_to_value / _fallback_sparse_rank_value",
    "Dynasty Scraper.py (5 references)",
    "source ranks",
    "scraper points",
    "site-specific",
    "the scraper's own composite (F-002)",
    "separate system predating the canonical engine",
    "-",
    "scraper tests",
    "-",
    "-",
    "-",
    "F-010 (separate system, documented)",
    "Deprecated but still active",
)
add(
    "F-014",
    "Percentile -> value (the live conversion)",
    "percentile_to_value(p, scope) using per-scope (C, S) master constants",
    "src/canonical/player_valuation.py::percentile_to_value:371",
    "percentile in [0,1], scope",
    "value points",
    "0-9999",
    "src/api/data_contract.py::_compute_unified_rankings",
    "Hill-style masters refit weekly, promoted by hand",
    "config/model_registry/hill_scope_masters.json championVersion=2 (matches live constants)",
    "tests/canonical/, tests/model_registry/",
    "the four scopes really are different populations",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-015",
    "Rank -> percentile denominator",
    "p = (rank - 1) / (_PERCENTILE_REFERENCE_N - 1) with _PERCENTILE_REFERENCE_N = 500; "
    "ranks past 500 clamp",
    "src/api/data_contract.py:5303",
    "combined-pool rank",
    "percentile",
    "0..1 (clamped)",
    "F-001",
    "deliberate top-500-board behaviour",
    "-",
    "tests/api/",
    "every source's pool is comparable to a 500-row reference",
    "-",
    "-",
    "F-016 (train/serve skew)",
    "Implemented and verified",
)
add(
    "F-016",
    "Rank -> percentile (model-registry holdout)",
    "p = i / (n - 1) over a 400-capped NATIVE pool",
    "src/model_registry/holdout.py",
    "per-source native ranks",
    "percentile",
    "0..1",
    "scripts/auto_refit_hill_curves.py challenger scoring",
    "holdout scoring measures generalization across markets",
    "-",
    "tests/model_registry/",
    "the fit's percentile definition matches serving's — it does not",
    "-",
    "TRAIN/SERVE SKEW: curves are fitted under i/(n-1) over <=400 and served under "
    "(rank-1)/499 with a clamp",
    "F-015",
    "Implemented but defective",
)

# ─────────────────────────────────────────────────────────────────────
# 3. BLENDING / WEIGHTS / GUARDRAILS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-020",
    "Consensus blending (count-aware)",
    "n=1 passthrough; n=2 mean; n=3-4 untrimmed mean-median; n>=5 trimmed mean-median",
    "src/api/data_contract.py::_compute_unified_rankings (aggregation stage 7)",
    "per-source votes after Hill",
    "value points",
    "0-9999",
    "F-001",
    "CLAUDE.md 'Live Value Pipeline' step 7",
    "-",
    "tests/api/test_source_overrides.py",
    "sources are exchangeable peers",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-021",
    "Source weights",
    "every entry in _RANKING_SOURCES carries weight 1.0 by policy",
    "src/api/data_contract.py::_RANKING_SOURCES:1005",
    "source registry",
    "unitless weight",
    "1.0",
    "F-001, POST /api/rankings/overrides",
    "policy: equal weight until a measured reason exists",
    "-",
    "tests/api/test_source_registry_parity.py",
    "config/weights/default_weights.json is documentation only — nothing loads it",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-022",
    "Hampel outlier filter",
    "reject |x - median| > _HAMPEL_K * 1.4826 * MAD with K=2.75, min_n=4, " "min_threshold=1000.0",
    "src/api/data_contract.py:232-234",
    "per-source votes",
    "value points",
    "0-9999",
    "F-001 pre-blend",
    "robust outlier rejection",
    "-",
    "tests/api/",
    "MAD is a valid dispersion estimate at n>=4",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-023",
    "MAD volatility penalty",
    "value -= _MAD_PENALTY_LAMBDA * MAD  (lambda = 0.0 since 2026-04-20)",
    "src/api/data_contract.py:5429",
    "sourceSpread",
    "value points",
    "no-op",
    "sourceSpread is stamped as a pure diagnostic",
    "retired; kept for the diagnostic field",
    "-",
    "tests/api/",
    "-",
    "-",
    "-",
    "-",
    "Deprecated but still active",
)
add(
    "F-024",
    "Single-source haircut",
    "non-pick rows resting on one post-Hampel source keep 0.30 of blended value",
    "src/api/data_contract.py:5443 (_SINGLE_SOURCE_VALUE_RETENTION)",
    "post-Hampel source count",
    "value points",
    "x0.30",
    "F-001",
    "one source is not a consensus",
    "-",
    "tests/api/",
    "a 70% haircut is the right magnitude — a prior, not a measurement",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-025",
    "Hierarchical anchor + alpha shrinkage",
    "shrunk = (1-alpha)*group_estimate + alpha*anchor with alpha = 0.10; "
    "IDP and picks ONLY (offense takes a flat count-aware mean-median)",
    "src/api/data_contract.py:5395 (_ALPHA_SHRINKAGE)",
    "anchor source set (picks widen to include ktcSfTep)",
    "value points",
    "0-9999",
    "F-001 step 6",
    "thin IDP/pick coverage needs an anchor",
    "-",
    "tests/api/",
    "offense coverage is thick enough not to need it",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-026",
    "Market corridor clamp (guardrail)",
    "clamp drift to the P90 band per confidence bucket, hard cap "
    "_MARKET_CORRIDOR_MAX_BAND_BY_ASSET_CLASS = {'idp': 0.15}; min bucket n = 30",
    "src/api/data_contract.py:4670-4690",
    "market anchor per asset class, confidence bucket",
    "fractional drift",
    "<=0.15 for IDP",
    "F-001 step 10 — IDP rows only; offense is not clamped",
    "contains raw blend drift",
    "-",
    "tests/api/",
    "stated rationale ('contain the IDP calibration runaway') names a mechanism that "
    "no longer exists — the calibration post-pass and config/idp_calibration.json are gone",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-027",
    "Two-way player boost",
    "rankDerivedValue = max(offense value, alt-position-family value) for "
    "_TWO_WAY_PLAYERS = {'Travis Hunter': 'DB'}",
    "src/api/data_contract.py:5048-5054",
    "both position families' blended values",
    "value points",
    "0-9999",
    "F-001 step 11 — a genuine post-blend override",
    "a two-way player is worth the better of his two markets",
    "-",
    "tests/api/",
    "hardcoded to exactly one name; a second two-way player needs a code edit",
    "max() cannot double count",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-028",
    "Rankings override delta",
    "recompute F-001 with disabled sources filtered and overridden weights, "
    "emit only _DELTA_PLAYER_FIELDS keyed by displayName",
    "src/api/data_contract.py::build_rankings_delta_payload:9619",
    "siteOverrides map",
    "value points",
    "0-9999",
    "POST /api/rankings/overrides?view=delta, frontend mergeRankingsDelta",
    "~4 MB -> ~1.25 MB uncompressed",
    "-",
    "tests/api/test_source_overrides.py::TestBuildRankingsDeltaPayload",
    "every override-sensitive field is in _DELTA_PLAYER_FIELDS",
    "-",
    "-",
    "-",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 4. TE / IDP / LEAGUE ADJUSTMENT
# ─────────────────────────────────────────────────────────────────────
add(
    "F-030",
    "TE premium (basis conversion)",
    "convert_te_value(v, from_basis='base', to_basis='tepp') using KTC's measured "
    "uplift curve (1.209 at board top rising toward 2.05); no-op when from==to",
    "src/league_intel/te_premium.py::convert_te_value:355, tep_uplift:323",
    "TE row value, source basis",
    "value points",
    "multiplier 1.209..2.05",
    "F-001 step 5a; ktc/ktcSfTep exempt",
    "ADR-015 docs/league-intelligence/DECISIONS.md; replaced a flat 1.15",
    "config/weights TE curve",
    "tests/audit/test_formula_registry.py::test_te_conversion_double_count_guard_is_structural",
    "target basis is a CONSTANT, not the league's measured TE demand",
    "structurally guarded by the from==to no-op",
    "the two live leagues on one scoring profile want different bases — unresolved",
    "-",
    "Partially implemented",
)
add(
    "F-031",
    "TE lift scale-ceiling guard",
    "_te_lift_under_ceiling(v) — compresses lifted TE votes under 9999 without "
    "collapsing distinct votes",
    "src/api/data_contract.py (_te_lift_under_ceiling, ref at :6055)",
    "uncapped lifted TE vote",
    "value points",
    "<9999",
    "F-030 output",
    "a naive clamp made three distinct Bowers votes identical",
    "-",
    "tests/audit/test_formula_registry.py::test_te_lift_cannot_collapse_distinct_votes",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-032",
    "TEP-native flat premium",
    "TEP-native sources keep a flat 1.10 multiplier (only base<->tepp is measured)",
    "src/api/data_contract.py (TE stage)",
    "TE rows from TEP-native sources",
    "value points",
    "x1.10",
    "F-001",
    "no measurement exists for TEP-native -> TE++",
    "-",
    "tests/api/",
    "1.10 is a prior, not a measurement",
    "-",
    "-",
    "F-030 (different math for the same concept, by source class)",
    "Duplicate or conflicting implementation",
)
add(
    "F-033",
    "TEP multiplier derivation",
    "_TEP_DERIVATION_SLOPE = 0.30, clamped to [1.0, 2.0]",
    "src/api/data_contract.py:5909-5911",
    "league TE scoring bonus",
    "multiplier",
    "1.0..2.0",
    "F-001 TE stage",
    "-",
    "-",
    "tests/api/",
    "linear in the TE bonus",
    "-",
    "-",
    "F-030",
    "Implemented and verified",
)
add(
    "F-034",
    "IDP rank translation backbone",
    "translate IDP source ranks onto the shared board ladder before Hill",
    "src/canonical/idp_backbone.py (341L)",
    "IDP source ranks",
    "board rank",
    "1..N",
    "F-001",
    "IDP sources publish disjoint populations",
    "-",
    "tests/canonical/",
    "the IDP ladder is commensurable with offense",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-035",
    "Cross-market comparability (KTC vs IDPTC)",
    "median value ratio 1.000 (p10 0.888, p90 1.054) over 475 shared rows; "
    "both boards top out at 9999 so no rescaling is applied",
    "src/league_intel/cross_market.py (703L)",
    "ktcSfTep and idpTradeCalc boards",
    "ratio",
    "~1.0",
    "src/trade/finder.py per-market gate",
    "measured 2026-07-26",
    "-",
    "tests/league_intel/",
    "the measured ratio holds forward",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-036",
    "League-adjusted valuation (the lens)",
    "adjusted = consensus * total_factor where total_factor is the product of four "
    "axes: structural scarcity, scoring fit, reception fit, TE premium",
    "src/league_intel/adjustment.py::build_adjustment:408 (axes at :211,:261,:312,:371)",
    "this league's 12 rosters, exact scoring settings",
    "unitless factor",
    "clamped per axis",
    "GET /api/valuation/league-adjusted, and every engine via valuation_mode",
    "positional scarcity is leagueKey-scoped by necessity",
    "-",
    "tests/league_intel/test_publish.py, tests/api/test_valuation_mode_threading.py",
    "the factor is a function of POSITION alone, so it composes against any board",
    "the two overlays are composed server-side, never multiplied twice on the client",
    "would reprice another league's board if stamped onto the contract — it is not",
    "-",
    "Implemented and verified",
)
add(
    "F-037",
    "Overlay application",
    "adjusted_rows() reprices EVERY row on a shallow copy; ranks re-derived with the "
    "same compact_ranks_and_tiers the pipeline uses",
    "src/league_intel/overlay.py::adjusted_rows:61, adjusted_contract:129",
    "factors + contract rows",
    "value points",
    "0-9999",
    "server.py::_valuation_scoped_contract",
    "serving only ranked rows measured 740 of 1093 — every 2026 pick vanished",
    "-",
    "frontend/__tests__/valuation-overlay.test.js",
    "latest_contract_data is a shared mutable global and must never be mutated",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-038",
    "Adjusted-board backtest verdict",
    "four framings over 572 players vs realized 2025 scoring: no difference detected, "
    "three of four lean negative",
    "scripts/backtest_adjusted_board.py, docs/adjusted-board-backtest.md",
    "realized 2025 scoring",
    "correlation / rank metrics",
    "-",
    "the decision to keep the adjusted board a toggle, not the default",
    "measured decision",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 5. REPLACEMENT LEVEL — FOUR IMPLEMENTATIONS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-040",
    "Replacement level (league-intel, value scale)",
    "four thresholds per position — starter / bestBallStarter / roster / waiver — "
    "measured from what the exact optimizer actually starts across all rosters",
    "src/league_intel/replacement.py::compute_replacement_levels (672L)",
    "this league's rosters, rosValue point estimates, src.ros.lineup solver",
    "dynasty board value points",
    "0-9999",
    "src/api/gameplan.py:129-132, src/roster_intel/{engine,profiles,targets,partner}.py",
    "endogenous flex allocation, smoothed bands",
    "-",
    "tests/league_intel/",
    "KNOWN LIMITATION, self-documented: optimizes on season-long MEANS, so it "
    "understates flex demand for high-variance positions (FLEX TE share 0.0% "
    "projected vs 10.4% measured on 2025 weekly actuals)",
    "-",
    "-",
    "F-041, F-042, F-043 — four separate answers to 'replacement level'",
    "Duplicate or conflicting implementation",
)
add(
    "F-041",
    "Replacement level (scoring, points-per-game)",
    "replacement_per_game = mean per-game pace of the FIVE players ranked just below "
    "the league's starter cutoff; vorp = points - replacement * games",
    "src/scoring/replacement_level.py::replacement_per_game, vorp_table (237L)",
    "PlayerSeasonRow(points, games) from any source; Sleeper roster_positions",
    "fantasy points per game",
    "PPG",
    "src/public_league/awards.py (League MVP / Playoff MVP), IDP scoring-fit pipeline",
    "lifted out of awards.py to be reusable",
    "-",
    "tests/scoring/",
    "FLEX splits 1/3 each, SUPER_FLEX 1/4 each, IDP_FLEX 1/3 each — a PREASSIGNED "
    "split, the opposite convention to F-040's endogenous one",
    "-",
    "-",
    "F-040, F-042, F-043",
    "Duplicate or conflicting implementation",
)
add(
    "F-042",
    "Replacement level (BDVM, dynamic flex-aware)",
    "R_g = FPG at rank [league-wide flex-allocated startable slots at g + waiver "
    "buffer]; greedy flex allocation, deterministic tie-break on group name",
    "src/bdvm/replacement.py::ReplacementEngine (155L)",
    "per-group rank->FPG pools, BdvmLeagueConfig",
    "fantasy points per game",
    "PPG",
    "src/bdvm/engine.py, /api/bdvm/*",
    "replacement does ALL positional-scarcity work in BDVM — no multipliers exist",
    "paramSetId",
    "tests/bdvm/",
    "raises ReplacementUnavailableError rather than fabricating R=0 — the strictest " "of the four",
    "-",
    "-",
    "F-040, F-041, F-043",
    "Duplicate or conflicting implementation",
)
add(
    "F-043",
    "Replacement level (league comparison)",
    "replacement_level = the Nth player's points (e.g. QB24); "
    "replacement_adj = average - replacement_level",
    "src/league_comparison/metrics.py:95-97, :164, :172-174",
    "top-N points arrays per position",
    "season fantasy points",
    "points",
    "/api/league-comparison, /league-comparison page",
    "measures replacement-end compression between scoring systems",
    "-",
    "tests/league_comparison/",
    "a single rank, not a smoothed band — the exact thing F-040's docstring argues "
    "against ('hostage to one player's projection')",
    "-",
    "-",
    "F-040, F-041, F-042",
    "Duplicate or conflicting implementation",
)

# ─────────────────────────────────────────────────────────────────────
# 6. BEST-BALL / LINEUP / ROSTER STRENGTH
# ─────────────────────────────────────────────────────────────────────
add(
    "F-050",
    "Best-ball lineup optimizer (backend)",
    "exact best-projected-lineup solve over slot tokens with flex eligibility",
    "src/ros/lineup.py (516L)",
    "RosterPlayer pool, league starter slots",
    "ROS points",
    "points",
    "src/roster_intel/marginal.py, src/league_intel/replacement.py, src/api/gameplan.py",
    "the one exact optimizer",
    "-",
    "tests/ros/",
    "point estimates, not weekly spikes",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-051",
    "Marginal best-ball contribution",
    "marginal(pos) = S(full) - S(full minus every player at this position); "
    "optimal_score(pool, slots) = solve_summary(...).score",
    "src/roster_intel/marginal.py:136-138 (347L)",
    "roster pool + slots",
    "ROS points",
    "points",
    "src/roster_intel/{engine,profiles,window}.py, /api/gameplan",
    "THE lineup-constrained team-value definition",
    "-",
    "tests/roster_intel/",
    "leave-one-position-out is the right marginal",
    "-",
    "-",
    "F-052, F-053 (three legitimately different 'team value' concepts)",
    "Implemented and verified",
)
add(
    "F-052",
    "Team value (frontend simple sum)",
    "totalValue = sum(player meta values) + sum(resolved pick values)",
    "frontend/lib/league-analysis.js::buildTeamValueBreakdown",
    "contract rows + Sleeper team rosters",
    "board value points",
    "0-9999 summed",
    "/rosters",
    "documented divergence — a portfolio total, not a lineup value",
    "-",
    "frontend/__tests__/",
    "-",
    "-",
    "-",
    "F-051, F-053",
    "Duplicate or conflicting implementation",
)
add(
    "F-053",
    "Team value (terminal simple sum, picks excluded)",
    "totalValue = sum(p['value'] for p in rosterValues)  — EXCLUDES picks",
    "src/api/terminal.py:1070 (comment at :1204-1221)",
    "contract rows for the roster",
    "board value points",
    "0-9999 summed",
    "GET /api/terminal, / (home terminal)",
    "self-documented: 442,936 of pick value vs 1,524,591 of player value on the live "
    "snapshot — 22.5% of a portfolio",
    "-",
    "tests/api/",
    "-",
    "-",
    "the FE fallback INCLUDES picks; the same tile can read 22.5% apart depending on "
    "which path served it",
    "F-051, F-052",
    "Duplicate or conflicting implementation",
)
add(
    "F-054",
    "Team ROS strength composite",
    "0.72*starting_lineup_strength + 0.18*best_ball_depth_strength "
    "+ 0.05*positional_coverage + 0.05*health_availability",
    "src/ros/team_strength.py:33-36 (269L)",
    "aggregated ROS player values, league starter slots",
    "composite",
    "0..1 scaled",
    "GET /api/ros/team-strength, rosPower (F-062), rosPlayoffOdds (F-071), "
    "trade-deadline direction (F-081)",
    "spec-defined defaults, hardcoded in PR1",
    "-",
    "tests/ros/",
    "weights are a prior; the module says they 'can be overridden per-league later'",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-055",
    "Lineup fill (frontend)",
    "fillLineup({assets, rosterPositions, positionOf, valueFor}) — greedy slot fill, "
    "live host rosterPositions first, registry second, never a literal",
    "frontend/lib/starter-slots.js",
    "team roster + sleeper.rosterPositions",
    "board value points",
    "0-9999",
    "frontend/lib/league-analysis.js (/rosters), frontend/lib/portfolio-insights.js " "(/terminal)",
    "consolidated SIX answers, two of which were wrong (audit 2026-07-30)",
    "-",
    "frontend/__tests__/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-056",
    "Roster strength tier score",
    "score = starterValue*0.7 + depthValue*0.2 - pickValue*0.1; "
    "tier = top third contender / bottom third rebuilder / middle",
    "frontend/lib/league-analysis.js:1131-1152",
    "filled lineup + depth + pick capital",
    "board value points",
    "0-9999 weighted",
    "/rosters",
    "picks penalized at -10% as a rebuild signal",
    "-",
    "frontend/__tests__/",
    "a tercile split forces exactly 4/4/4 in a 12-team league regardless of spread",
    "pickValue is added into totalValue AND subtracted here at 10%",
    "-",
    "F-051, F-054",
    "Duplicate or conflicting implementation",
)

# ─────────────────────────────────────────────────────────────────────
# 7. POSITIONAL NEED / STARTER SLOTS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-060",
    "Starter slots (canonical)",
    "config/leagues/registry.json rosterSettings.starters, resolved via "
    "src/api/league_registry.py; live sleeper.rosterPositions takes precedence",
    "config/leagues/registry.json; src/api/league_registry.py",
    "leagueKey",
    "slot counts",
    "integers",
    "F-055, F-050, F-061, src/bdvm/league_config.py",
    "leagueKey-scoped per CLAUDE.md",
    "schemaVersion 1",
    "tests/api/test_league_registry.py",
    "operator-maintained and known to drift — hence the live-host precedence rule",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-061",
    "Positional need / demand model (trade suggestions)",
    "starter_needs_for_league(key) derives base slots + flex allocation in "
    "RB->WR->TE order; dynasty_main {QB2 RB3 WR4 TE2 DL3 LB3 DB3}, "
    "dynasty_new {QB2 RB3 WR4 TE1}",
    "src/trade/suggestions.py:39-58, :64-146",
    "registry rosterSettings",
    "starter demand counts",
    "integers",
    "POST /api/trade/suggestions",
    "a demand model, not a slot count — superflex wants a second startable QB",
    "-",
    "tests/trade/",
    "the derivation reproduces the old hardcoded constant for dynasty_main",
    "-",
    "THREE sites (:882 rank_score, :921 rank_score_breakdown, :1026 "
    "_generate_sell_high) still read the hardcoded DEFAULT_STARTER_NEEDS instead of "
    "the derived per-league map",
    "-",
    "Implemented but defective",
)
add(
    "F-062",
    "Position need deficit (roster intel)",
    "deficit = replacement-level occupant's contribution - actual contribution; "
    "positive means acquire a starter",
    "src/roster_intel/engine.py::position_needs:137-173",
    "F-051 marginals + F-040 replacement levels",
    "ROS points",
    "points",
    "/api/gameplan",
    "answers 'am I below replacement here' in lineup-points, not board value",
    "-",
    "tests/roster_intel/",
    "needs F-040 supplied; without it tiers default to developmental",
    "-",
    "-",
    "F-061 (different units entirely: points vs slot counts)",
    "Duplicate or conflicting implementation",
)
add(
    "F-063",
    "Positional scarcity delta (team impact)",
    "per-position starter-vs-replacement scarcity delta for a proposed trade",
    "src/trade/team_impact.py:476 (516L)",
    "roster before/after, replacement levels",
    "value points",
    "0-9999",
    "POST /api/trade/simulate",
    "-",
    "-",
    "tests/trade/",
    "-",
    "-",
    "-",
    "F-062",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 8. CONTENDER / REBUILDER — SIX CLASSIFIERS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-070",
    "Team phase (frontend, value x age)",
    "isHighValue = totalValue(top 25) > league median; isYounger = medianAge < league "
    "median; high+young=Win-now, high+old=Contender, low+young=Rebuild, else Mixed",
    "frontend/lib/team-phase.js::classifyPhase:79-92",
    "rankDerivedValue + age from contract rows, sleeper.teams",
    "labels",
    "4 categories",
    "/phases",
    "-",
    "-",
    "frontend/__tests__/",
    "median split forces ~50/50 on each axis regardless of spread",
    "-",
    "-",
    "F-071..F-075 — SIX classifiers of the same concept (prior audit claimed three)",
    "Duplicate or conflicting implementation",
)
add(
    "F-071",
    "Team direction (ROS, 7 labels)",
    "Strong Buyer if playoff>=0.75 AND champ>=0.10; Buyer >=0.60/>=0.05; Selective "
    "Buyer 0.45-0.60; Hold 0.35-0.55; Selective Seller 0.20-0.40; Seller <0.25 AND "
    "<0.02; Strong Seller <0.10 AND <0.01 AND age-heavy (vetCount>=4)",
    "src/ros/direction.py::classify_team:53-... (162L)",
    "F-072 playoff odds, F-076 championship odds, F-054 strength, position-aware "
    "veteran ages (QB32 RB26 WR29 TE30 DL30 LB29 DB29)",
    "labels",
    "7 categories",
    "/api/public/league/rosTradeDeadline, /league trade-deadline tab",
    "spec mapping with deliberately overlapping bands, resolved strongest-first",
    "-",
    "tests/ros/",
    "consumes the odds engine that returns hard 0/1 in preseason (F-072)",
    "-",
    "-",
    "F-070, F-072..F-075",
    "Duplicate or conflicting implementation",
)
add(
    "F-072",
    "Competitive window (5-state softmax)",
    "affinity = -(2.0*(comp - c_anchor)^2 + 1.0*(traj - t_anchor)^2); "
    "softmax at temperature 0.18 over 5 anchors",
    "src/roster_intel/window.py:85-104, :285-300 (compute_window)",
    "championship-odds percentile (or lineup-score percentile), value-weighted lineup "
    "age mapped on [22,32]",
    "probabilities",
    "5 states summing to 1",
    "/api/gameplan",
    "softmax rather than thresholds — 'a team one point either side of a cut flips "
    "category while its neighbour does not move at all'",
    "-",
    "tests/roster_intel/",
    "ORDERING_CAVEAT: retool vs productive_struggle ordering is explicitly soft",
    "-",
    "-",
    "F-070, F-071, F-073..F-075",
    "Duplicate or conflicting implementation",
)
add(
    "F-073",
    "BDVM direction (capital ratio, league-relative)",
    "rel = (contender_capital/rebuilder_capital) / league median ratio; "
    "rel > _CONTEND_RATIO -> contend, rel < _REBUILD_RATIO -> rebuild, else retool",
    "src/bdvm/roster.py::_directions_relative:63-92, strategy_for_direction:94-95",
    "BDVM strategy capitals",
    "labels",
    "3 categories",
    "/api/bdvm/roster, /bdvm",
    "the absolute rule (ratio vs 1.15) saturated — all twelve rosters read 'contend'",
    "-",
    "tests/bdvm/",
    "documented judgment call; the absolute ratio is still exposed per roster",
    "-",
    "-",
    "F-070..F-072, F-074, F-075",
    "Duplicate or conflicting implementation",
)
add(
    "F-074",
    "Player-level strategy tag",
    "rookie or years_exp<=2 -> 'rebuilder'; years_exp>=8 -> 'contender'; else 'neutral'",
    "src/trade/suggestions.py::_strategy_for_player:803-808",
    "rookie flag, years_exp",
    "labels",
    "3 categories",
    "POST /api/trade/suggestions",
    "-",
    "-",
    "tests/trade/",
    "years_exp is a proxy for age; a 24-year-old 3rd-year WR reads 'neutral'",
    "-",
    "-",
    "F-070..F-073, F-075",
    "Duplicate or conflicting implementation",
)
add(
    "F-075",
    "Roster tier (tercile)",
    "sort by F-056 score; top ceil(n/3) contender, bottom third rebuilder, rest middle",
    "frontend/lib/league-analysis.js:1146-1152",
    "F-056 score",
    "labels",
    "3 categories",
    "/rosters",
    "-",
    "-",
    "frontend/__tests__/",
    "forces a fixed 4/4/4 split in a 12-team league",
    "-",
    "-",
    "F-070..F-074",
    "Duplicate or conflicting implementation",
)

# ─────────────────────────────────────────────────────────────────────
# 9. PLAYOFF / CHAMPIONSHIP ODDS — TWO ENGINES
# ─────────────────────────────────────────────────────────────────────
add(
    "F-080",
    "Playoff odds v1 (empirical Monte Carlo)",
    "sample each owner's future weekly score from their own empirical scored-week "
    "distribution; 10,000 sims; top playoff_spots by (wins, PF)",
    "src/public_league/playoff_odds.py (build_section)",
    "PublicLeagueSnapshot weekly scores + posted/inferred schedule",
    "probability",
    "0..1",
    "GET /api/public/league/playoffOdds, /league Playoff Odds tab",
    "self-contained, no modelling library, every input explicit",
    "public-league/2026-04-18.v1",
    "tests/public_league/",
    "an owner with <2 scored weeks falls back to the league-wide distribution",
    "-",
    "-",
    "F-081 (measured live: 7 playoff spots vs 6, 12 owners vs 8, contradicts on 2 teams)",
    "Implemented but defective",
)
add(
    "F-081",
    "Playoff odds v2 (ROS-blended Monte Carlo)",
    "shifted_mean = empirical_mean * (1 + ROS_BLEND*(ros_strength_z - 1)) with "
    "ROS_BLEND=0.20; sd *= 1.10 best-ball variance bump (depth_aware); 2000 sims",
    "src/ros/playoff_sim.py (1074L; reuses playoff_odds._season_weekly_scores:468 and "
    "_posted_future_matchups:550)",
    "F-054 team strength + empirical distribution + PointsModel",
    "probability",
    "0..1",
    "GET /api/public/league/rosPlayoffOdds, /league (settings.useRosPlayoffOdds " "defaults TRUE)",
    "'when ROS data is available it provides a forward-looking signal pure history "
    "cannot capture'",
    "-",
    "tests/ros/",
    "pointsModelSource == 'fallback-constants' live — no fitted points model exists",
    "-",
    "emits only 8 of 12 owners; disagrees with v1 on playoff seats (6 vs 7)",
    "F-080",
    "Implemented but defective",
)
add(
    "F-082",
    "Championship odds (ROS bracket MC)",
    "bracket simulation over F-081 seeds; 10,000 sims; emits championship / finals / "
    "semifinal odds + contenderTier",
    "src/ros/championship.py (304L)",
    "F-081 seed distribution, F-054",
    "probability",
    "0..1",
    "GET /api/public/league/rosChampionship, F-071, F-072",
    "no v1 equivalent",
    "-",
    "tests/ros/",
    "inherits F-081's degeneracy: live payload shows Roy at playoffOdds 1.0 and "
    "championshipOdds 0.0",
    "-",
    "-",
    "-",
    "Implemented but defective",
)
add(
    "F-083",
    "Expected wins / luck score",
    "expected wins from all-play win share vs actual wins",
    "src/public_league/luck.py (378L)",
    "weekly scores across the league",
    "wins",
    "0..games",
    "/league Luck tab, F-062 luck_regression component",
    "-",
    "-",
    "tests/public_league/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 10. POWER RANKINGS — TWO ENGINES
# ─────────────────────────────────────────────────────────────────────
add(
    "F-090",
    "Power ranking v1",
    "power = 100 * (0.50*PPG percentile + 0.25*last-3-game avg percentile "
    "+ 0.25*all-play win share)",
    "src/public_league/power.py:45-47, :141",
    "weekly scored results, per-week active owners",
    "power score",
    "0..100",
    "GET /api/public/league/power, /league Power tab",
    "percentiles normalized within each week's active owners",
    "public-league/2026-04-18.v1",
    "tests/public_league/",
    "requires scored games; with none it falls back to the last scored season",
    "-",
    "measured live: 10 owners, and Jason scores exactly 0.0 because F-100 returns a "
    "hard 0.0 at the population minimum",
    "F-091",
    "Duplicate or conflicting implementation",
)
add(
    "F-091",
    "Power ranking v2 (ROS)",
    "weighted sum of 9 components: team_ros_strength .38, ppg .18, recent .12, "
    "wl_record .10, all_play .08, streak .05, schedule_adjusted .04, roster_health "
    ".03, luck_regression .02; missing components dropped and weights renormalized",
    "src/ros/power_v2.py:65-75, :99-108 (524L)",
    "F-054 + season results",
    "power score",
    "0..100",
    "GET /api/public/league/rosPower, /league Power tab when "
    "settings.useRosPowerRankings (defaults TRUE)",
    "'coexists with the existing power section; the frontend swaps between them'",
    "-",
    "tests/ros/",
    "in preseason 7 of 9 weights are missing — the live payload runs on "
    "team_ros_strength .38 + roster_health .03 only",
    "-",
    "measured live: 12 owners vs v1's 10, mean |rank shift| 2.8, max 7 " "(Jason 10th -> 3rd)",
    "F-090",
    "Duplicate or conflicting implementation",
)

# ─────────────────────────────────────────────────────────────────────
# 11. PERCENTILE HELPERS — FIVE DEFINITIONS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-100",
    "Percentile helper (public_league/power)",
    "(below + (equal-1)*0.5) / (n-1); returns 0.5 when n<=1",
    "src/public_league/power.py::_percentile_rank:52-61",
    "population, target",
    "percentile",
    "0.0 .. 1.0 inclusive",
    "F-090",
    "midrank tiebreak",
    "-",
    "tests/public_league/",
    "reaches a literal 0.0 and 1.0 — the league minimum scores zero",
    "-",
    "-",
    "F-101..F-104",
    "Duplicate or conflicting implementation",
)
add(
    "F-101",
    "Percentile helper (sharp/score)",
    "(below + 0.5*equal) / n; returns 0.5 on an empty population",
    "src/sharp/score.py::percentile_rank:191-203",
    "population, value",
    "percentile",
    "0.5/n .. (n-0.5)/n",
    "the 0.85 sharp qualification bar (F-110)",
    "'an all-identical population carries no information and must not read as "
    "universally elite'",
    "config/sharp/scoring_v2.json",
    "tests/sharp/",
    "can never return 0.0 or 1.0 — at n=12 the extremes are 0.0417 and 0.9583",
    "-",
    "-",
    "F-100, F-102..F-104",
    "Duplicate or conflicting implementation",
)
add(
    "F-102",
    "Percentile helper (ros/power_v2)",
    "(below + 0.5*same) / len(eligible); returns 0.0 on an empty population",
    "src/ros/power_v2.py::_percentile:99-108",
    "population, target",
    "percentile",
    "0.0 or 0.5/n .. (n-0.5)/n",
    "F-091",
    "-",
    "-",
    "tests/ros/",
    "an UNMEASURABLE percentile returns 0.0 (worst in league), where F-100 and F-101 "
    "return 0.5 (neutral)",
    "-",
    "-",
    "F-100, F-101, F-103, F-104",
    "Duplicate or conflicting implementation",
)
add(
    "F-103",
    "Percentile helper (roster_intel/window, inline x2)",
    "(below + 0.5*ties) / len(pop) — written out twice inline, not extracted",
    "src/roster_intel/window.py:228-231 and :238-241",
    "championship odds map, or lineup scores map",
    "percentile",
    "0.5/n..(n-0.5)/n",
    "F-072 competitiveness axis",
    "-",
    "-",
    "tests/roster_intel/",
    "identical to F-101 but duplicated inline rather than imported",
    "-",
    "-",
    "F-101",
    "Duplicate or conflicting implementation",
)
add(
    "F-104",
    "Elite threshold index (roster_intel/profiles)",
    "vals[max(0, round(len(vals) * ELITE_PERCENTILE) - 1)] — banker's rounding index, "
    "not a percentile rank",
    "src/roster_intel/profiles.py:86-89",
    "position value pool",
    "value point",
    "a pool element",
    "F-062 player tiering",
    "'elite is a distribution percentile, not a replacement level'",
    "-",
    "tests/roster_intel/",
    "round() is banker's rounding, so the index steps non-monotonically with n",
    "-",
    "-",
    "F-100..F-103",
    "Duplicate or conflicting implementation",
)

# ─────────────────────────────────────────────────────────────────────
# 12. TRADE FAIRNESS / VALUE ADJUSTMENT / GRADES
# ─────────────────────────────────────────────────────────────────────
add(
    "F-110",
    "KTC Value Adjustment (JS original)",
    "ktcProcessV / ktcReverseAdjust / ktcAdjustPackage — verbatim port of KTC's "
    "site.min.js; MAX 10000, T reference 10041, variance 5%",
    "frontend/lib/trade-logic.js::ktcAdjustPackage",
    "two arrays of raw values",
    "value points",
    "0-10000",
    "/trade TradeMeter",
    "the calculator the users compare against",
    "-",
    "frontend/__tests__/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-111",
    "KTC VA (Python port A)",
    "same algorithm; rounds with Python round() at :116 (ktc_reverse_adjust) and "
    ":319 (final value) — BANKER'S ROUNDING",
    "src/trade/ktc_va.py:116, :146-319, adjusted_pair_totals:322-349",
    "two value lists",
    "value points",
    "0-10000",
    "src/trade/suggestions.py:27, src/trade/angle.py:98, src/trade/monte_carlo.py:153",
    "'so /api/angle/find and suggestions do not grade with the legacy V2 formula'",
    "-",
    "tests/trade/test_ktc_va_python_port.py (asserts agreement to +/-1)",
    "the +/-1 tolerance in its own parity test is exactly the size of the defect it "
    "would otherwise catch",
    "-",
    "-",
    "F-110, F-112, F-113 — measured 38/20000 divergences vs F-112, max |diff| 1",
    "Duplicate or conflicting implementation",
)
add(
    "F-112",
    "KTC VA (Python port B)",
    "same algorithm; rounds with _js_round = floor(x+0.5) at :136, :144, :386",
    "src/trade/market_value_adjustment.py:33-36, :183-386",
    "two value lists",
    "value points",
    "0-10000",
    "src/trade/finder_value_adjustment.py:16 (installed onto the finder by "
    "src/trade/__init__.py:9)",
    "'line-for-line Python port of the authoritative frontend implementation'",
    "-",
    "tests/trade/test_finder_value_adjustment.py",
    "-",
    "-",
    "-",
    "F-110, F-111, F-113",
    "Duplicate or conflicting implementation",
)
add(
    "F-113",
    "KTC VA (Python port C)",
    "same algorithm; _js_round = floor(x+0.5) at :103-112, :188, :197, :387",
    "src/public_league/trade_grading.py:103-112, :225-387",
    "two value lists",
    "value points",
    "0-10000",
    "src/public_league/trade_grading.py:400 (public-league trade grades)",
    "docstring explicitly names the Python-round bug that F-111 still has",
    "-",
    "tests/fixtures/trade_grade_parity_cases.json",
    "-",
    "-",
    "-",
    "F-110, F-111, F-112",
    "Duplicate or conflicting implementation",
)
add(
    "F-114",
    "Trade letter grade",
    "pct thresholds 3 / 8 / 15 / 25 / 40 -> A(fair) A(slight) A A A+ ... down to F",
    "src/public_league/trade_grading.py:48-76; " "frontend/lib/league-analysis.js:87-92",
    "VA-adjusted side totals",
    "letter",
    "A+ .. F",
    "/league Activity tab (Python), /rosters (JS)",
    "registry claims parity pinned by tests/fixtures/trade_grade_parity_cases.json",
    "-",
    "tests/public_league/test_trade_grading.py + the shared fixture",
    "the JS copy re-states the thresholds as literals rather than importing them",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-115",
    "Trade fairness label (suggestions)",
    "|gap| < 256 -> even; < 769 -> lean; else stretch",
    "src/trade/suggestions.py::_fairness_label:794-801",
    "VA-adjusted gap",
    "label",
    "3 categories",
    "POST /api/trade/suggestions",
    "-",
    "-",
    "tests/trade/",
    "absolute point thresholds on a 0-9999 scale — a 256 gap means something "
    "different at the top of the board than at the bottom",
    "-",
    "-",
    "F-114 (percentage-based)",
    "Duplicate or conflicting implementation",
)
add(
    "F-116",
    "Trade Monte Carlo win probability",
    "correlated draws (same_team_rho / same_pos_group_rho scalars) -> winProbA, "
    "meanDelta; symmetrized by averaging both directions",
    "src/trade/monte_carlo.py (387L); src/trade/symmetrize.py (229L)",
    "per-asset p10/p50/p90",
    "probability",
    "0..1",
    "POST /api/trade/simulate-mc, /trade",
    "'sim(A,B).winProbA == 1 - sim(B,A).winProbA' enforced by averaging",
    "-",
    "tests/trade/",
    "uniform rho scalars under-capture reality (F-117 is the unused alternative)",
    "consolidation adjustment (F-111) is applied on top of the p50 draws",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-117",
    "Correlation matrix (MC alternative)",
    "rule ladder 1.00/0.55/0.35/0.25/0.15/0.00, ceiling max_rho 0.85, " "Cholesky-decomposed",
    "src/trade/correlation_matrix.py (170L)",
    "player team + position",
    "correlation",
    "0..0.85",
    "NONE in production — no caller outside tests",
    "'an alternative to the two-scalar model' the sampler can consume",
    "-",
    "tests/trade/",
    "-",
    "-",
    "-",
    "F-116",
    "Scaffolded only",
)
add(
    "F-118",
    "Consolidation suggestion",
    "min_target = combined * CONSOLIDATION_MIN_UPGRADE_RATIO (0.70); stretch kept if "
    "VA-adjusted gap / give_total <= 0.30",
    "src/trade/suggestions.py:167-170, :1146-1212, :1429-1446",
    "surplus players, target pool",
    "value points",
    "0-9999",
    "POST /api/trade/suggestions, /trade",
    "'prevents consolidation from showing 6 different pairs all targeting Bijan'",
    "-",
    "tests/trade/",
    "0.70 and 0.30 are priors",
    "-",
    "-",
    "F-119",
    "Implemented and verified",
)
add(
    "F-119",
    "Consolidation pricing (BDVM)",
    "package_value = (Sum v^theta)^(1/theta) - roster_spot_cost * overflow; "
    "theta > 1 prices consolidation",
    "src/bdvm/trade_math.py:4, :35-38 (91L)",
    "per-asset strategy values, theta, C_spot",
    "fundamental value",
    "model-scaled",
    "POST /api/bdvm/trade-eval, GET /api/bdvm/trades",
    "BDVM section 3.13 — a CES aggregator, never a plain sum",
    "paramSetId",
    "tests/bdvm/test_trade_eval.py",
    "theta and C_spot are labelled priors in config/bdvm/params_v1.json",
    "-",
    "-",
    "F-118 (same concept, incompatible math and units)",
    "Duplicate or conflicting implementation",
)
add(
    "F-120",
    "Roster-spot cost",
    "spot_cost * overflow, subtracted from the CES core",
    "src/bdvm/trade_math.py:35-38",
    "config/bdvm/params_v1.json roster_spot_cost",
    "fundamental value",
    "model-scaled",
    "F-119",
    "the ONLY roster-spot cost in the tree",
    "paramSetId",
    "tests/bdvm/",
    "a prior, not a measurement",
    "-",
    "-",
    "-",
    "Blocked by data (data/bdvm/ absent)",
)
add(
    "F-121",
    "Trade acceptance estimate",
    "trade_acceptance_estimate + acceptanceConfidence, capped below 1.0 while no "
    "rejection data exists",
    "src/roster_intel/partner.py:174-182, :445-478 (see also :15-28)",
    "completed trades (activity), roster fit, window alignment",
    "plausibility",
    "0..1, ceiling < 1",
    "/api/gameplan packages.frontier[].acceptancePlausibility",
    "'Sleeper records only the numerator (accepted trades) and never the denominator "
    "-> an acceptance RATE is statistically unidentifiable'",
    "-",
    "tests/roster_intel/",
    "explicitly never renamed to 'probability'; ships with acceptanceCaveat attached",
    "-",
    "package fit and acceptance plausibility are anti-correlated BY CONSTRUCTION and "
    "the payload says so",
    "-",
    "Implemented and verified",
)
add(
    "F-122",
    "Arbitrage edge (finder)",
    "board value (rankDerivedValue) vs per-market retail anchor; gate "
    "MARKET_TOP_N_FILTER=150 ranked WITHIN each market (ktcSfTep offense+picks, "
    "idpTradeCalc IDP)",
    "src/trade/finder.py:111, :181, :245 (board_values_from_contract)",
    "canonical board + retail boards",
    "value points",
    "0-9999",
    "POST /api/trade/finder, /arbitrage",
    "'the market number is load-bearing in its arithmetic'",
    "metadata.valueSource stamps which scale produced a run",
    "tests/test_trade_finder.py",
    "assets the board declines to price are counted in "
    "metadata.assetsUnpricedByBoard (202 on a real payload), never dropped silently",
    "-",
    "-",
    "F-123 (deliberately different GATE, same value)",
    "Implemented and verified",
)
add(
    "F-123",
    "Board quality gate (suggestions)",
    "BOARD_TOP_N_FILTER = 150 against OUR blended board (display_value order)",
    "src/trade/suggestions.py (_assign_board_ranks)",
    "canonical board",
    "rank ordinal",
    "1..150",
    "POST /api/trade/suggestions",
    "'suggestions only needs an asset-quality gate, which our own board answers for "
    "IDP and picks no retail board covers'",
    "boardTopNFilter (ktc* names survive as deprecated aliases)",
    "tests/trade/",
    "-",
    "-",
    "-",
    "F-122 (deliberate divergence)",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 13. BUY / SELL / SIGNALS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-130",
    "Buy/Sell/Hold (terminal, Python)",
    "priority-ordered boolean rule ladder; highest-priority firing rule owns the "
    "signal; default HOLD",
    "src/api/terminal.py::_evaluate_signal:875",
    "trend7, trend30, volatility MAD, value, news impact counts",
    "labels",
    "RISK/SELL/MONITOR/STRONG_HOLD/BUY/HOLD",
    "GET /api/terminal, / (home)",
    "shared rule table",
    "tests/fixtures/signal_parity_cases.json schemaVersion 1",
    "tests/api/test_signal_engine_parity.py",
    "-",
    "-",
    "-",
    "F-131 (parity-pinned)",
    "Implemented and verified",
)
add(
    "F-131",
    "Buy/Sell/Hold (frontend, JS)",
    "same rule ladder, same priorities, same tags",
    "frontend/lib/signal-engine.js::evaluate (RULES from :47)",
    "same context object",
    "labels",
    "same 6",
    "/rankings, /terminal components",
    "-",
    "same fixture",
    "frontend/__tests__/signal-engine-parity.test.js",
    "-",
    "-",
    "-",
    "F-130",
    "Implemented and verified",
)
add(
    "F-132",
    "Unified signal engine (news/usage/injury/transaction)",
    "verdict BUY/SELL/HOLD + confidence 0..1 + severity low/medium/high, combining "
    "value movement, usage z-scores, injury diffs, transaction activity",
    "src/news/unified_signal_engine.py",
    "rank drift, snap/target/carry share z, injury feed diff, league transactions",
    "verdict + confidence",
    "3 labels, confidence 0..1",
    "signal alerts sweep",
    "'single entry point for every BUY/SELL/HOLD decision emitted to users'",
    "-",
    "tests/news/",
    "the claim of being the single entry point is false — F-130/F-131, F-133, F-134 "
    "and F-135 all emit their own",
    "-",
    "-",
    "F-130, F-131, F-133, F-134, F-135",
    "Duplicate or conflicting implementation",
)
add(
    "F-133",
    "BDVM market signal",
    "alpha = fundamental - market; STRONG_BUY / BUY / HOLD / SELL / STRONG_SELL / "
    "NO_MARKET by alpha bands and market liquidity",
    "src/bdvm/market.py:307-351",
    "F-003 fundamental value, value-signal sources only",
    "labels",
    "6 categories",
    "/api/bdvm/values, /bdvm, /rankings Fund-gap tint, src/api/bdvm_signal_alerts.py",
    "'appending BDVM labels to the terminal detector's set would merge two different "
    "vocabularies'",
    "modelVersion + paramSetId",
    "tests/bdvm/, tests/api/test_bdvm_signal_alerts.py",
    "NO_MARKET is an absence and is never alerted on",
    "separate user_kv namespace (bdvmSignalAlertStateByLeague) so the two detectors "
    "cannot collide",
    "-",
    "F-130..F-132",
    "Blocked by data (data/bdvm/ absent)",
)
add(
    "F-134",
    "Consensus edge composite",
    "score = 100 * Sum(w_i * c_i) / Sum(w_i) over PRESENT components only "
    "(absent components dropped and weights renormalized); label Strong Buy at "
    ">= 60 (config strongBuy)",
    "src/consensus_edge/score.py:34, :155-... , :326-333",
    "mispricing, fair value, opportunity, sharp flow components",
    "score",
    "-100..100",
    "GET /api/consensus-edge/*, /consensus-edge",
    "'an opportunity signal on its own says nothing about mispricing — calling that "
    "a Buy would be a category error' (score None without a core component)",
    "config/consensus_edge params",
    "tests/consensus_edge/",
    "-",
    "-",
    "-",
    "F-130..F-133, F-135",
    "Missing at runtime — flag consensus_edge defaults off (ADR-023); code exists",
)
add(
    "F-135",
    "Sharp buy/sell tracker",
    "net add/drop movement across the sharp cohort, per window",
    "src/sharp/market.py (459L)",
    "F-140 cohort, normalized platform movements",
    "counts / net",
    "signed integers",
    "GET /api/sharp/market, /market/sharp-tracker",
    "cohort resolved through src/sharp/cohort.py::cohort_members — never a second list",
    "-",
    "tests/sharp/",
    "-",
    "-",
    "-",
    "F-130..F-134",
    "Implemented and verified",
)
add(
    "F-136",
    "Waiver upgrade tier",
    "gap thresholds -> smash / strong / considering; drop confidence classified by "
    "the gap to the BEST replacement",
    "frontend/lib/waiver-logic.js:43-58, :261-263, :268-302, :631-641",
    "board values of roster player vs best addable FA",
    "value points",
    "0-9999 gap",
    "/waivers",
    "'2000+ gap means dropping this player nets a starter-tier replacement'",
    "-",
    "frontend/__tests__/",
    "absolute point thresholds on a relative scale",
    "-",
    "-",
    "-",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 14. SHARP
# ─────────────────────────────────────────────────────────────────────
add(
    "F-140",
    "Sharp score",
    "weighted components (win rate, championship rate beta-binomial shrunk, "
    "consistency = SHARE of leagues above median, confidence) minus an explicit "
    "uncertainty penalty; percentile-normalized within the observed population; "
    "qualification bar is itself a percentile (0.85)",
    "src/sharp/score.py (+ config/sharp/scoring_v2.json)",
    "src/sharp/platform_records.py evidence; dynasty leagues >= 2 seasons only",
    "score + confidence",
    "0..1 each",
    "src/sharp/cohort.py::cohort_members -> F-135, F-141, roster_collect, "
    "scripts/crawl_sharp_activity.py",
    "docs/intel/SHARP_SCORE.md; every weight lives in config, nothing hardcoded",
    "config/sharp/scoring_v2.json",
    "tests/sharp/",
    "score and confidence are SEPARATE outputs; a manager must clear BOTH bars",
    "-",
    "the 0.52 win-rate floor is a VIABILITY gate, not the selector",
    "-",
    "Implemented and verified",
)
add(
    "F-141",
    "Sharp roster percentage",
    "unique eligible sharp rosters containing the player / total eligible sharp "
    "rosters that COULD contain him (denominator computed PER PLAYER by position "
    "family and league format)",
    "src/sharp/roster_percentage.py",
    "sharp_rosters / sharp_roster_assets tables, F-140 cohort",
    "percentage",
    "0..1",
    "GET /api/sharp/roster-percentage, /market/sharp-roster-percentage",
    "docs/sharp-roster-percentage/METHODOLOGY.md",
    "-",
    "tests/sharp/",
    "rosters, not people, are the denominator; formatUnknownRosters is reported "
    "rather than silently assumed",
    "counting rules enforced by primary keys, not caller discipline",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-142",
    "Super sharp score",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "no such construct exists anywhere in the tree "
    "(grep 'super.?sharp' over *.py *.js *.jsx *.md *.json returns nothing)",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Missing",
)

# ─────────────────────────────────────────────────────────────────────
# 15. TRANSACTION / INSIDER TRADING
# ─────────────────────────────────────────────────────────────────────
add(
    "F-150",
    "Transaction activity ranking",
    "per-window indexed queries; the board sorts on SINGLE-WINDOW volume",
    "src/intel/service.py (818L)",
    "platform ledger transactions",
    "counts",
    "integers",
    "GET /api/intel/*, /league/insider-trading",
    "replaced a nested-window sum",
    "-",
    "tests/audit/test_formula_registry.py::"
    "test_nested_windows_are_not_summed_into_the_board_ranking",
    "-",
    "trend_score = 3*net48h + 2*net7d + 1*net30d DOUBLE COUNTED nested windows; the "
    "module holding it (src/intel/aggregate.py) is deleted and the test forbids any "
    "sort on trendScore",
    "-",
    "-",
    "Blocked by data (data/intel/ + platform ledger DB absent)",
)
add(
    "F-151",
    "Trade activity alpha (public league)",
    "REPLACED — used to be sum(max(value,1) ** 1.65) per side",
    "src/public_league/activity.py:47-50 (comment only; the math is gone)",
    "-",
    "-",
    "-",
    "-",
    "'raising to 1.65 inflates a gap — a 10% linear edge is a ~16% alpha'",
    "-",
    "tests/public_league/",
    "-",
    "-",
    "-",
    "F-114 (replaced by it)",
    "Deprecated but still active",
)
add(
    "F-152",
    "Movement indicators (ticker)",
    "use the contract's stamped rankChange verbatim; null or 0 is 'quiet' and "
    "excluded from the ticker",
    "frontend/lib/market-movers.js",
    "rankChange stamped per scrape",
    "rank delta",
    "signed integer",
    "/ terminal ticker",
    "'a real per-scrape delta — we use it verbatim rather than recomputing'",
    "-",
    "frontend/__tests__/",
    "-",
    "-",
    "-",
    "F-153",
    "Implemented and verified",
)
add(
    "F-153",
    "Movement indicators (/trending)",
    "computeWindowTrend over rank_history for 1d / 7d / 30d windows; positive "
    "rankChange means improved (toward rank #1)",
    "frontend/lib/movers.js (WINDOW_OPTIONS :19)",
    "contract rows + rankHistory",
    "rank delta",
    "signed integer",
    "/trending",
    "-",
    "-",
    "frontend/__tests__/",
    "different window semantics from F-152 (per-scrape delta vs windowed trend) for "
    "the same word 'mover'",
    "-",
    "-",
    "F-152",
    "Duplicate or conflicting implementation",
)

# ─────────────────────────────────────────────────────────────────────
# 16. FAAB / WAIVERS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-160",
    "FAAB bid recommendation (canonical)",
    "_compute_faab_bid -> (aggressive, reasonable, lowball) as a share of remaining "
    "budget scaled by the value gap",
    "src/trade/waiver.py::_compute_faab_bid:97-103",
    "player value, roster gap, faab remaining (default 100)",
    "budget %",
    "0..100",
    "POST /api/waiver/faab-recommend, /waivers",
    "formula-registry faab-bid",
    "-",
    "tests/fixtures/faab_bid_parity_cases.json",
    "-",
    "-",
    "-",
    "F-161 (parity port)",
    "Implemented and verified",
)
add(
    "F-161",
    "FAAB bid (JS parity port)",
    "computeFaabHint — JS port of _compute_faab_bid with roundHalfUp",
    "frontend/lib/waiver-logic.js:851-873",
    "same",
    "budget %",
    "0..100",
    "/waivers",
    "-",
    "-",
    "same fixture",
    "-",
    "-",
    "-",
    "F-160",
    "Implemented and verified",
)
add(
    "F-162",
    "FAAB recommendation (per-pair, v2)",
    "layers on top of F-160: league historical position bids, league median winning "
    "bid, KTC crowd bid map, sleeper trending count",
    "src/trade/faab_recommender.py:43, :187-273, :312 (701L)",
    "F-160 baseline + F-163 league summary + adapters/ktc_crowd_faab",
    "budget %",
    "0..100",
    "POST /api/waiver/faab-recommend",
    "-",
    "-",
    "tests/trade/",
    "-",
    "the F-160 baseline is one input among four, not re-summed",
    "-",
    "F-160",
    "Implemented and verified",
)
add(
    "F-163",
    "League FAAB analytics",
    "summarize_league_faab — walks every season's waiver transactions for "
    "settings.waiver_bid, emits median + per-position winning bids",
    "src/api/faab_analytics.py:188 (331L)",
    "public-league snapshot transactions",
    "budget %",
    "0..100",
    "GET /api/public/league/faabAnalytics -> F-162",
    "lazy because the walk is O(seasons x weeks)",
    "-",
    "tests/api/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-164",
    "FAAB contention (rival bid estimation)",
    "exp_bid = min(exp_bid, opponent.faabRemaining) per opponent",
    "src/trade/faab_contention.py:15, :335 (497L)",
    "opponent rosters, needs, faab remaining",
    "budget %",
    "0..100",
    "POST /api/waiver/faab-recommend perOpponent block",
    "FAAB v2",
    "-",
    "tests/trade/",
    "-",
    "-",
    "-",
    "F-162",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 17. PICKS / DRAFT
# ─────────────────────────────────────────────────────────────────────
add(
    "F-170",
    "Pick value (canonical)",
    "blend -> multiplicative future-year discount (Phase 3a, BEFORE the sort) -> "
    "sort -> current-year slot picks tethered to the merged rookie pool (Phase 5.2b, "
    "OVERWRITES rankDerivedValue)",
    "src/api/data_contract.py (pick stages; _PICK_SLOT_RE:4284, discount cache:4295)",
    "config/weights/pick_year_discount.json, merged offense+IDP rookie pool",
    "value points",
    "0-9999",
    "/api/data, /draft, every trade engine",
    "CLAUDE.md 'Live Value Pipeline' steps 12-13 (corrected 2026-07-29)",
    "-",
    "tests/api/",
    "a tethered current-year pick never carries a discount (year offset 0 -> 1.0)",
    "the discount runs BEFORE tethering, so tethering overwrites it for current-year "
    "picks — order is load-bearing",
    "-",
    "F-171, F-172, F-173",
    "Implemented and verified",
)
add(
    "F-171",
    "Pick value (Sleeper-derived fallback)",
    "_pick_value_from_contract returns None on a miss; unpriced picks are EXCLUDED "
    "from the $1200 dollar normalization and emitted with dollarValue null + "
    "isUnpriced true",
    "src/api/draft_capital_fallback.py",
    "that league's own Sleeper rosters + traded picks, contract pick values",
    "auction dollars",
    "$1200 pool",
    "GET /api/draft-capital (non-default league)",
    "the flat 7000/4000/2000/1200-by-round table was REMOVED (audit finding C1)",
    "-",
    "tests/api/test_draft_capital_fallback.py, " "tests/api/test_draft_capital_data_not_ready.py",
    "coveredPickYears is derived from what was actually priced, not the loop bounds",
    "the removed table diluted the $1200 pool with invented values for every "
    "next-year pick, shifting every team's auctionDollars",
    "-",
    "F-170",
    "Implemented and verified",
)
add(
    "F-172",
    "Pick value (legacy calibration curve)",
    "_pick_curve_value(info, current_year) — a pick curve inside the retired "
    "canonical calibration path",
    "src/canonical/calibration.py:159, called only from :356 inside the same module",
    "pick name + year",
    "value points",
    "0-9999",
    "NONE — zero production references (verified by symbol scan over src/, " "server.py, scripts/)",
    "legacy",
    "-",
    "tests/canonical/test_calibration.py",
    "-",
    "-",
    "-",
    "F-170",
    "Scaffolded only",
)
add(
    "F-173",
    "Pick value (BDVM outcome EV)",
    "pick value = EV over an outcome distribution (hit% / median / ceiling) per " "draft slot",
    "src/bdvm/picks.py (125L), config/bdvm pick outcomes",
    "draft-slot priors",
    "fundamental value",
    "model-scaled",
    "/api/bdvm/values pick rows, /draft 'Fundamental pick values (BDVM)' panel",
    "BDVM section 5.12 / prompt section 9 — a fundamental concept, not a market one",
    "paramSetId",
    "tests/bdvm/",
    "the module itself calls these 'placeholder priors'",
    "-",
    "-",
    "F-170",
    "Blocked by data (data/bdvm/ absent)",
)
add(
    "F-174",
    "Pick projector (future pick -> slot)",
    "future-pick -> projected-draft-slot mapping from ROS standings projection",
    "src/ros/pick_projection.py (252L)",
    "F-081 projected standings",
    "draft slot",
    "1.01..6.12",
    "GET /api/ros/pick-projections",
    "-",
    "-",
    "tests/ros/",
    "inherits F-081's preseason degeneracy",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-175",
    "Rookie anchor",
    "_ROOKIE_ANCHOR_LEAGUE_SIZE_DEFAULT = 12, _ROOKIE_ANCHOR_ROUNDS = 6",
    "src/api/data_contract.py:5885-5886",
    "rookie source ladders",
    "rank ordinal",
    "72 slots",
    "F-170 tethering",
    "-",
    "-",
    "tests/api/",
    "hardcoded 12-team / 6-round; dynasty_new is a 10-team league",
    "-",
    "the live contract carries 72 current-year slot picks (12 x 6) — this is what "
    "made the removed F-171 table fire on every next-year pick",
    "-",
    "Implemented and verified",
)
add(
    "F-176",
    "Draft auction power",
    "effective auction power — relative draft-capital concentration lens",
    "src/api/auction_power.py (170L); frontend/lib/auction-power.js",
    "per-team pick dollar values",
    "auction dollars",
    "$1200 pool",
    "GET /api/draft-capital, /draft",
    "-",
    "-",
    "tests/api/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-177",
    "Draft board tiering",
    "{key: 'A', label: 'Starter', min: 25} ... letter buckets by value threshold",
    "frontend/lib/draft-logic.js:76",
    "rookie board values",
    "letter",
    "A..",
    "/draft RookieBoard",
    "-",
    "-",
    "frontend/__tests__/components/DraftBoardSort.test.jsx",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-178",
    "Perfect draft",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "no such construct exists (grep 'perfect.?draft' over *.py *.js *.jsx: nothing)",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Missing",
)

# ─────────────────────────────────────────────────────────────────────
# 18. TIERS / CONFIDENCE / FRESHNESS
# ─────────────────────────────────────────────────────────────────────
add(
    "F-180",
    "Tier detection (live)",
    "rolling-median gap detection over the sorted value series",
    "src/canonical/player_valuation.py::detect_tiers:202 (_rolling_median:189)",
    "sorted values + player ids",
    "tier ids",
    "1..N",
    "src/api/data_contract.py:2029-2033 (compact_ranks_and_tiers)",
    "-",
    "-",
    "tests/canonical/",
    "-",
    "-",
    "-",
    "F-181",
    "Implemented and verified",
)
add(
    "F-181",
    "Tier detection (effect-size)",
    "_pool_normalized_gap(tier_mean, candidate, pool_sd) with grid-searched "
    "thresholds + drift detection",
    "src/scoring/tiering.py::detect_tiers:201, stamp_tiers_on_players:226, "
    "fit_thresholds_grid_search:253, detect_threshold_drift:314",
    "position rows + fitted thresholds",
    "tier ids",
    "1..N",
    "scripts/refit_tier_thresholds.py ONLY",
    "the positional_tiers flag is marked NO_GATE in feature_flags.py:410",
    "-",
    "tests/scoring/",
    "-",
    "-",
    "-",
    "F-180 (same function name, different math, different consumers)",
    "Scaffolded only",
)
add(
    "F-182",
    "Confidence bucket (contract)",
    "_CONFIDENCE_PERCENTILE_HIGH 0.08 / MEDIUM 0.20; " "_CONFIDENCE_SPREAD_HIGH 30 / MEDIUM 80",
    "src/api/data_contract.py:112-118",
    "cross-source percentile spread",
    "labels",
    "high/medium/low",
    "/api/data every row, F-026 corridor bucketing, /rankings",
    "-",
    "-",
    "tests/api/",
    "-",
    "-",
    "-",
    "F-183, F-184",
    "Implemented and verified",
)
add(
    "F-183",
    "Confidence (source count)",
    "n>=6 high, n>=3 medium, else low",
    "src/trade/suggestions.py::_confidence_from_sources:811-816",
    "source count",
    "labels",
    "high/medium/low",
    "POST /api/trade/suggestions",
    "-",
    "-",
    "tests/trade/",
    "-",
    "-",
    "-",
    "F-182 (same three labels, entirely different input)",
    "Duplicate or conflicting implementation",
)
add(
    "F-184",
    "Market confidence (scraper)",
    "_market_confidence — scraper-side confidence over raw source coverage",
    "Dynasty Scraper.py::_market_confidence",
    "raw source presence",
    "labels/score",
    "-",
    "data/dynasty_data_*.json -> /api/data mirror fields",
    "formula-registry market-confidence, status documented-divergence",
    "-",
    "tests/api/test_market_confidence_wiring.py",
    "-",
    "-",
    "-",
    "F-182, F-183",
    "Duplicate or conflicting implementation",
)
add(
    "F-185",
    "Source-consensus value range (CI)",
    "confidence interval across sources — explicitly NOT a forecast",
    "src/canonical/confidence_intervals.py (261L)",
    "per-source votes",
    "value points",
    "0-9999 band",
    "gated by value_confidence_intervals, which feature_flags.py:409 marks NO_GATE",
    "-",
    "-",
    "tests/canonical/",
    "the flag defaults False AND gates nothing, so the gate is not the control",
    "-",
    "-",
    "-",
    "Scaffolded only",
)
add(
    "F-186",
    "Rank-history CI band",
    "rolling rankHistory band for the source-consensus CI",
    "src/canonical/rank_history_band.py (141L)",
    "rank history",
    "rank band",
    "ordinals",
    "/api/data/rank-history, PlayerRankHistoryChart",
    "-",
    "-",
    "tests/canonical/",
    "-",
    "-",
    "-",
    "F-185",
    "Implemented and verified",
)
add(
    "F-187",
    "Data freshness guard",
    "is_fresh_for_alerts(week, year, now) — false until Thursday (weekday 3) "
    "US/Eastern, after pfr + nflverse republish",
    "src/nfl_data/freshness.py:_SAFE_WEEKDAY=3 (96L)",
    "NFL week, year, wall clock in America/New_York",
    "boolean",
    "-",
    "signal alerts sweep, nfl_data ingest",
    "'do not trust current-week data until Thursday local NFL day'",
    "-",
    "tests/nfl_data/",
    "one global republish deadline for every nflverse table",
    "-",
    "-",
    "F-188",
    "Implemented and verified",
)
add(
    "F-188",
    "Source staleness",
    "_SOURCE_MAX_AGE_HOURS per source; _DEFAULT_SOURCE_ROW_FLOORS; "
    "_DEFAULT_TOP50_COVERAGE_FLOORS; _PICK_COUNT_FLOOR 100; "
    "_PAYLOAD_SIZE_FLOOR_BYTES 2,000,000",
    "src/api/data_contract.py:589, :646, :756, :764, :773",
    "source CSV mtimes + row counts",
    "hours / rows / bytes",
    "-",
    "/api/scaffold/status, source-health alerts, /tools/source-health",
    "-",
    "config/sources",
    "tests/api/",
    "-",
    "-",
    "-",
    "F-187",
    "Implemented and verified",
)
add(
    "F-189",
    "Source disagreement flags",
    "_DISAGREEMENT_BASE_THRESHOLD 0.10 (caution), _SUSPICIOUS_PCT_BASE_THRESHOLD "
    "0.20 (anomaly), depth allowance cap 0.25, "
    "_SUSPICIOUS_DISAGREEMENT_THRESHOLD 150 ranks",
    "src/api/data_contract.py:160-162, :191",
    "per-source rank spread",
    "flags",
    "boolean",
    "/rankings caution badges, /tools/source-health",
    "-",
    "-",
    "tests/api/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)

# ─────────────────────────────────────────────────────────────────────
# 19. PUBLIC LEAGUE — AWARDS / RECORDS / FRANCHISE / MISC
# ─────────────────────────────────────────────────────────────────────
add(
    "F-190",
    "Awards / award races",
    "VORP over F-041 replacement, plus per-award rule sets (League MVP, Playoff MVP, " "…)",
    "src/public_league/awards.py (2343L)",
    "Sleeper matchup players_points, F-041",
    "fantasy points / VORP",
    "points",
    "GET /api/public/league/awards, /league Awards tab",
    "-",
    "public-league/2026-04-18.v1",
    "tests/public_league/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-191",
    "Records",
    "per-category all-time extremes over every scored week in the snapshot",
    "src/public_league/records.py (488L)",
    "PublicLeagueSnapshot",
    "points / margins",
    "-",
    "GET /api/public/league/records, /league Records tab",
    "-",
    "-",
    "tests/public_league/",
    "-",
    "-",
    "-",
    "F-192",
    "Implemented and verified",
)
add(
    "F-192",
    "Streaks / records-in-reach",
    "active streak detection + distance-to-record",
    "src/public_league/streaks.py (581L)",
    "same snapshot",
    "counts",
    "-",
    "GET /api/public/league/streaks",
    "-",
    "-",
    "tests/public_league/",
    "-",
    "-",
    "-",
    "F-191",
    "Implemented and verified",
)
add(
    "F-193",
    "Franchise rankings",
    "per-owner all-time rollup (record, titles, playoff appearances, award shelf)",
    "src/public_league/franchise.py (299L)",
    "multi-season snapshot",
    "counts / rates",
    "-",
    "GET /api/public/league/franchise, /league/franchise/[owner]",
    "-",
    "-",
    "tests/public_league/",
    "'award shelf placeholder (later prompt wires real awards)' — self-declared "
    "placeholder at :11",
    "-",
    "-",
    "-",
    "Partially implemented",
)
add(
    "F-194",
    "Superlatives / rivalries",
    "per-pair head-to-head aggregates and league superlatives",
    "src/public_league/superlatives.py (211L), src/public_league/rivalries.py (210L)",
    "snapshot matchups",
    "counts",
    "-",
    "/league Superlatives, /league/rivalry/[pair]",
    "-",
    "-",
    "tests/public_league/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-195",
    "Team assignment (fantasy team -> NFL teams)",
    "tiered point model over the roster (starting QB, skill starters/committee, "
    "rookie draft capital, IDP starters); NFL teams scoring >= assignmentMinPoints "
    "(15) qualify; max maxTeamsPerOwner (3) per owner, favorite always counts",
    "src/api/team_assignment.py (510L)",
    "league rosters + a favorites key",
    "points",
    ">= 15 to qualify",
    "GET /api/public/league/teamAssignment, /league?tab=teamAssignment",
    "-",
    "-",
    "tests/api/",
    "the point tiers are priors; debug block carries per-player contributions",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-196",
    "Injury impact",
    "injury-status -> value impact model (position-based, not league-based)",
    "src/api/injury_impact.py (336L)",
    "injury feed status, position",
    "value points",
    "0-9999 delta",
    "/api/data injury fields, /rankings",
    "CLAUDE.md: injury-impact follows scoring profile, not leagueKey",
    "-",
    "tests/api/",
    "-",
    "-",
    "-",
    "-",
    "Implemented and verified",
)
add(
    "F-197",
    "League comparison improvement score",
    "0.??*... + 0.10*replacement_adj (IMPROVED_WEIGHT_REPL_ADJ) over per-position " "metrics",
    "src/league_comparison/metrics.py:13-16, :195, :248-259",
    "two scoring systems' realized points",
    "score",
    "-",
    "GET /api/league-comparison, /league-comparison",
    "'picks up replacement-end compression'",
    "-",
    "tests/league_comparison/",
    "-",
    "-",
    "-",
    "F-043",
    "Implemented and verified",
)
add(
    "F-198",
    "Schedule structure (BDVM)",
    "NFL schedule -> per-team ROS week structures (byes, playoff weeks)",
    "src/bdvm/schedule.py (112L)",
    "NFL schedule",
    "week sets",
    "1..18",
    "src/bdvm/ros.py, src/bdvm/engine.py",
    "-",
    "-",
    "tests/bdvm/",
    "-",
    "-",
    "-",
    "-",
    "Blocked by data (data/bdvm/ absent)",
)
add(
    "F-199",
    "Schedule optimization",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "no schedule OPTIMIZER exists. F-198 is schedule structure, F-083 is schedule "
    "luck, F-091's schedule_adjusted is a power component. Nothing optimizes a "
    "schedule.",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Missing",
)
add(
    "F-200",
    "Money / ROI",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "no entry fees, payouts, prizes or ROI anywhere. The single 'ROI' string in the "
    "tree is a comment in frontend/lib/draft-logic.js:2286 about valueVsFair.",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Missing",
)
add(
    "F-201",
    "In-season posterior blend (BDVM)",
    "w = n_prior/(n_prior + weeks) with n_prior 6 offense / 8 IDP; sigma shrinks by "
    "sqrt(w_prior); ROS drops already-played weeks via current_week",
    "src/bdvm/actuals.py, blend_ros_mu",
    "nflverse weekly rows scored under the league's exact settings",
    "PPG",
    "PPG",
    "/api/bdvm/*",
    "BDVM section 8.4",
    "-",
    "tests/bdvm/test_inseason.py",
    "the actuals season is the CALENDAR NFL season, never currentDraftYear",
    "current_week is uncapped so after week 18 ROS sums zero — cannot double-count "
    "the banked final week",
    "-",
    "-",
    "Blocked by data (data/bdvm/ absent)",
)
add(
    "F-202",
    "Auto news -> event confidence",
    "confidence = 0.45 (< 0.5) so effective_impact suppresses every non-sigma "
    "channel AND clamps sigma_mult >= 1.0",
    "src/bdvm/news_events.py",
    "aggregated headlines",
    "confidence",
    "0.45 fixed",
    "data/bdvm/events/<season>.json -> F-003",
    "'a headline can widen uncertainty but can NEVER move a mean or narrow sigma'",
    "-",
    "tests/bdvm/test_news_events.py",
    "raising confidence is a human edit",
    "same-fact suppression: one (playerKey, eventType) per 14 days, so N providers "
    "!= N sigma wideners",
    "-",
    "-",
    "Blocked by data (data/bdvm/ absent)",
)

# Normalize the verdict column to the AUDIT_PROTOCOL vocabulary exactly, moving any
# parenthetical detail into the assumptions column so no information is lost.
_VOCAB_FIX = {
    "Blocked by data (data/bdvm/ absent)": ("Blocked by data", "absent path: data/bdvm/"),
    "Blocked by data (data/bdvm/ absent in this container)": (
        "Blocked by data",
        "absent path: data/bdvm/",
    ),
    "Blocked by data (data/intel/ + platform ledger DB absent)": (
        "Blocked by data",
        "absent paths: data/intel/ and the platform ledger DB",
    ),
    "Duplicate or conflicting implementation (currently in agreement)": (
        "Duplicate or conflicting implementation",
        "the two copies agree numerically at HEAD",
    ),
    "Missing at runtime — flag consensus_edge defaults off (ADR-023); code exists": (
        "Implemented but disconnected",
        "feature flag consensus_edge defaults off per ADR-023",
    ),
}
for row in R:
    fix = _VOCAB_FIX.get(row["verdict"])
    if fix:
        row["verdict"] = fix[0]
        extra = fix[1]
        row["assumptions"] = (
            extra if row["assumptions"] in ("-", "") else f"{row['assumptions']}; {extra}"
        )

csv_path = pathlib.Path(__file__).with_name("formula-inventory.csv")
with csv_path.open("w", newline="", encoding="utf-8") as fh:
    w = csv.DictWriter(fh, fieldnames=COLS, quoting=csv.QUOTE_ALL)
    w.writeheader()
    for row in R:
        w.writerow(row)
print(f"wrote {csv_path} rows={len(R)}")

verdicts: dict[str, int] = {}
for row in R:
    verdicts[row["verdict"]] = verdicts.get(row["verdict"], 0) + 1
for k, v in sorted(verdicts.items(), key=lambda kv: -kv[1]):
    print(f"  {v:3d}  {k}")
