"""Game Day U7 — the UI's fixtures ARE the API's output (UI/API agreement).

``frontend/__tests__/fixtures/game-day/*.json`` are what the Game Day
component tests render.  They are generated by :mod:`tests.game_day.ui_payloads`
from the U4 replay captures through the real endpoint assembly; this test
regenerates every scenario and requires byte equality, so a backend change
to anything the UI reads fails here until the fixtures (and therefore the
frontend tests) are regenerated with it::

    python -m tests.game_day.ui_payloads
"""

from __future__ import annotations

import pytest

from tests.game_day import ui_payloads


@pytest.mark.parametrize("name", sorted(ui_payloads.SCENARIOS))
def test_committed_ui_fixture_matches_the_endpoint(name):
    path = ui_payloads.fixture_path(name)
    assert path.exists(), f"missing {path}; run python -m tests.game_day.ui_payloads"
    expected = ui_payloads.serialize(ui_payloads.build(name))
    assert path.read_text(encoding="utf-8") == expected, (
        f"{path.name} is stale against the backend; regenerate with "
        "python -m tests.game_day.ui_payloads"
    )


def test_fixtures_cover_every_state_the_ui_renders():
    built = {name: ui_payloads.build(name) for name in ("pregame", "overtime", "week-final")}
    assert built["pregame"]["mode"] == "pregame"
    assert built["overtime"]["probabilityState"] == "LIVE_PROGRESS_UNAVAILABLE"
    assert "overtime" in built["overtime"]["progressUnavailableReasons"]
    assert built["week-final"]["mode"] == "final"
    assert built["week-final"]["team"]["result"] in {"WIN", "LOSS", "TIE"}


def test_expected_margin_is_the_difference_of_the_two_expected_finals():
    """``expectedMarginVsOpponent`` is a pure projection of values already computed."""
    payload = ui_payloads.build("halftime")
    team = payload["team"]["outcome"]
    opp = payload["opponent"]["outcome"]
    assert team["expectedMarginVsOpponent"] == pytest.approx(
        team["expectedFinalBestBall"] - opp["expectedFinalBestBall"], abs=0.011
    )
    assert opp["expectedMarginVsOpponent"] == pytest.approx(
        -team["expectedMarginVsOpponent"], abs=0.011
    )
