"""Platform-neutral ingestion contracts for Sharp Tracker sources."""

from src.platforms.base import (
    PLATFORM_FFPC,
    PLATFORM_SLEEPER,
    IDENTITY_GLOBAL_UNVERIFIED,
    IDENTITY_GLOBAL_VERIFIED,
    IDENTITY_LEAGUE_SCOPED_TEAM,
    IDENTITY_NAME_ONLY,
    QUALIFICATION_AUTOMATED,
    QUALIFICATION_CURATED,
    QUALIFICATION_INSUFFICIENT,
    QUALIFICATION_PROVISIONAL,
    NormalizedBatch,
    NormalizedLeague,
    NormalizedManager,
    NormalizedManagerSeason,
    NormalizedMembership,
    NormalizedMovement,
    NormalizedTransaction,
    PlatformAdapter,
    scoped_key,
)

__all__ = [
    "PLATFORM_FFPC",
    "PLATFORM_SLEEPER",
    "IDENTITY_GLOBAL_UNVERIFIED",
    "IDENTITY_GLOBAL_VERIFIED",
    "IDENTITY_LEAGUE_SCOPED_TEAM",
    "IDENTITY_NAME_ONLY",
    "QUALIFICATION_AUTOMATED",
    "QUALIFICATION_CURATED",
    "QUALIFICATION_INSUFFICIENT",
    "QUALIFICATION_PROVISIONAL",
    "NormalizedBatch",
    "NormalizedLeague",
    "NormalizedManager",
    "NormalizedManagerSeason",
    "NormalizedMembership",
    "NormalizedMovement",
    "NormalizedTransaction",
    "PlatformAdapter",
    "scoped_key",
]
