"""12-manager load rehearsal for the rookie auction room — LOCAL ONLY.

What it does
------------
Spawns a throwaway uvicorn process on an ephemeral ``127.0.0.1`` port with a
temporary auction store (``RISKIT_AUCTION_DB``), creates a MOCK room with 12
human-account seats (the site-owner commissioner plus 11 accounts created
through the room's own invite flow — random per-run passwords, no real
credentials), starts it, opens 12 lots, and then drives it for ``--duration``
seconds with:

* 12 manager clients, each holding 2-3 "tabs" that run their own
  ``GET /view?after=<rev>&wait=25`` long-poll loops (mirroring
  ``frontend/lib/auction-client.js``: first snapshot, then long-poll, drop
  responses older than the revision held);
* a concurrent bidding burst per manager (random proxy maxima, raises, $0
  bids, withdrawals, nominations, deliberate idempotent replays and
  idempotency conflicts), with the frontend's unknown-outcome retry rule
  (receipt lookup, same Idempotency-Key);
* concurrent ``GET /advice-context`` (Perfect Draft) and notification-state /
  inbox reads;
* a reconnect chaos loop (kill one tab's poll mid-flight, restart it);
* commissioner mock-clock jumps so lots settle during the run;
* an ``/api/health`` ping loop (event-loop responsiveness) and a server
  process sampler (CPU, RSS, handles/FDs).

Afterwards it verifies invariants from a FRESH read — over HTTP, and again
directly from the SQLite file after the server is hard-killed (crash-style
stop): no seat overspent (committed <= balance, spendable >= 0), one winner
per settled player, no duplicate idempotency operation, no lost acknowledged
action, replay of the command log reproduces the room.

What it does NOT measure
------------------------
The app under test is a SHIM: the real ``src/auction`` router, store, engine
and runtime, mounted on a bare FastAPI app with GZip (as production), plus a
stub ``server`` module (site-owner session check against a random per-run
token, the contract loaded from a local export).  It does NOT load the rest
of ``server.py`` (scrapes, other routes, their middleware and memory), and
there is no nginx in front.  Production sits behind nginx (``/api/``
buffering, a proxy read timeout) on a different host.  Treat the numbers as
the auction code path's own capacity on this machine, not a production SLO.

The shim also wraps ``Store.write`` / ``Store.read`` / the store's writer
lock with timers (measurement only, inside the throwaway process) so SQLite
lock waits and transaction hold times can be reported.  No ``src/`` file is
modified.

Usage
-----
    python scripts/auction_load_rehearsal.py                 # 120 s default
    python scripts/auction_load_rehearsal.py --duration 60 --json-out out.json

Exit codes: 0 = invariants held; 1 = invariant violation; 2 = harness/setup
failure; 3 = a performance target missed (only with ``--strict-targets``).
"""

from __future__ import annotations

import argparse
import asyncio
import bisect
import hashlib
import json
import math
import os
import random
import re
import secrets
import shutil
import signal
import socket
import sqlite3
import ssl
import subprocess
import sys
import tempfile
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]

try:
    import httpx
except ImportError:  # pragma: no cover - dev dependency
    print("httpx is required (pip install -r requirements-dev.txt)", file=sys.stderr)
    raise SystemExit(2) from None

try:  # optional
    import psutil  # type: ignore
except ImportError:  # pragma: no cover
    psutil = None

EXIT_OK, EXIT_INVARIANT, EXIT_SETUP, EXIT_TARGET = 0, 1, 2, 3
SEATS = 12
EVENT_LIMIT = 150  # api._view asks events_for(limit=150)
_REV_RE = re.compile(rb'^\{"revision":(\d+)')
# Environment variables never passed to the throwaway server.
_SCRUB_RE = re.compile(
    r"(VAPID|SMTP|PUSH|EMAIL|MAIL_|PASSWORD|SECRET|TOKEN|API_KEY|SLEEPER|E2E_|DEPLOY|GITHUB|AWS_|RISKIT_AUCTION)",
    re.I,
)
# One shared SSL context: httpx builds (and loads the CA bundle into) a new
# context per client otherwise -- ~200 ms of synchronous work each on Windows,
# which stalls this harness's own event loop and inflates every measurement.
_SSL = ssl.create_default_context()
DEFAULT_BUDGETS = [250, 180, 150, 120, 100, 90, 80, 60, 50, 40, 25, 0]

# ---------------------------------------------------------------------------
# The throwaway app (written to the temp dir and served by uvicorn)
# ---------------------------------------------------------------------------

SHIM_SOURCE = r'''
"""Generated by scripts/auction_load_rehearsal.py.  LOCAL load-rehearsal app:
the real src/auction router/store/engine/runtime on a bare FastAPI app with a
stub ``server`` module.  Measurement wrappers only; nothing here ships."""
from __future__ import annotations

import asyncio
import hmac
import json
import os
import sqlite3
import sys
import threading
import time
import types
from contextlib import asynccontextmanager, contextmanager

REPO = os.environ["AUCTION_LOAD_REPO"]
if REPO not in sys.path:
    sys.path.insert(0, REPO)
_ADMIN = os.environ["AUCTION_LOAD_ADMIN_TOKEN"]
_OWNER = "loadtest-owner"

_fake = types.ModuleType("server")
_fake.PRIVATE_APP_ALLOWED_USERNAMES = frozenset({_OWNER})


def _get_auth_session(request):
    tok = request.cookies.get("jason_session") or ""
    if tok and hmac.compare_digest(tok, _ADMIN):
        return {"username": _OWNER, "displayName": "Load Owner"}
    return None


_fake._get_auth_session = _get_auth_session
with open(os.environ["AUCTION_LOAD_CONTRACT"], encoding="utf-8") as _fh:
    _fake.latest_contract_data = json.load(_fh)


async def _get_draft_capital(request):
    return {"season": 0, "teamTotals": []}


_fake.get_draft_capital = _get_draft_capital
sys.modules["server"] = _fake

from fastapi import FastAPI  # noqa: E402
from fastapi.middleware.gzip import GZipMiddleware  # noqa: E402

from src.auction import api as _auction_api  # noqa: E402
from src.auction import store as _store_mod  # noqa: E402

_LOCK = threading.Lock()
_MAX = 400_000
_STATS: dict = {}
_ERRORS: dict = {}


def _reset():
    with _LOCK:
        _STATS.clear()
        _ERRORS.clear()


def _rec(key, value):
    with _LOCK:
        lst = _STATS.setdefault(key, [])
        if len(lst) < _MAX:
            lst.append(value)


def _err(where, exc):
    msg = f"{where}: {type(exc).__name__}: {exc}"[:200]
    with _LOCK:
        _ERRORS[msg] = _ERRORS.get(msg, 0) + 1


_orig_write = _store_mod.Store.write
_orig_read = _store_mod.Store.read


@contextmanager
def _timed_write(self):
    t0 = time.perf_counter()
    try:
        with _orig_write(self) as conn:
            t1 = time.perf_counter()
            _rec("write_acquire", t1 - t0)
            try:
                yield conn
            finally:
                t2 = time.perf_counter()
                _rec("write_hold", t2 - t1)
        _rec("write_commit", time.perf_counter() - t2)
    except sqlite3.Error as exc:
        _err("write", exc)
        raise


@contextmanager
def _timed_read(self):
    t0 = time.perf_counter()
    try:
        with _orig_read(self) as conn:
            _rec("read_open", time.perf_counter() - t0)
            yield conn
    except sqlite3.Error as exc:
        _err("read", exc)
        raise


_store_mod.Store.write = _timed_write
_store_mod.Store.read = _timed_read


class _TimedLock:
    """Wraps the store's process-wide writer RLock to time contention."""

    def __init__(self, inner):
        self._inner = inner

    def acquire(self, *a, **k):
        t0 = time.perf_counter()
        ok = self._inner.acquire(*a, **k)
        _rec("writer_lock_wait", time.perf_counter() - t0)
        return ok

    def release(self):
        self._inner.release()

    def __enter__(self):
        self.acquire()
        return self

    def __exit__(self, *exc):
        self.release()
        return False


async def _lag_probe():
    while True:
        t0 = time.perf_counter()
        await asyncio.sleep(0.05)
        _rec("loop_lag", time.perf_counter() - t0 - 0.05)


@asynccontextmanager
async def _lifespan(app):
    from src.auction import runtime
    from src.auction.store import get_store

    st = get_store()
    st._lock = _TimedLock(st._lock)
    task = runtime.start()
    lag = asyncio.create_task(_lag_probe())
    yield
    lag.cancel()
    if task is not None:
        task.cancel()


app = FastAPI(lifespan=_lifespan)
app.add_middleware(GZipMiddleware, minimum_size=1024)
app.include_router(_auction_api.router)


@app.get("/api/health")
async def _health():
    return {"status": "ok", "t": time.time()}


def _summary(values):
    if not values:
        return {"n": 0}
    v = sorted(values)

    def q(p):
        k = (len(v) - 1) * p
        lo = int(k)
        hi = min(lo + 1, len(v) - 1)
        return v[lo] + (v[hi] - v[lo]) * (k - lo)

    return {"n": len(v), "p50": q(0.5), "p95": q(0.95), "p99": q(0.99), "max": v[-1],
            "sum": sum(v)}


@app.get("/api/_load/metrics")
async def _metrics():
    with _LOCK:
        stats = {k: list(v) for k, v in _STATS.items()}
        errors = dict(_ERRORS)
    return {
        "pid": os.getpid(),
        "threads": threading.active_count(),
        "stats": {k: _summary(v) for k, v in stats.items()},
        "errors": errors,
    }


@app.post("/api/_load/reset")
async def _reset_route():
    _reset()
    return {"ok": True}
'''

# Builds the contract from a local export in a SUBPROCESS (keeps the harness
# process lean).  Same builder the server uses.
_BUILD_CONTRACT = r"""
import json, sys
sys.path.insert(0, sys.argv[3])
from src.api.data_contract import build_api_data_contract
with open(sys.argv[1], encoding="utf-8") as fh:
    raw = json.load(fh)
contract = build_api_data_contract(raw)
with open(sys.argv[2], "w", encoding="utf-8") as fh:
    json.dump(contract, fh)
"""


def synthetic_contract() -> dict:
    """Same shape the tests use: 12 teams, a rookie class, one veteran."""
    teams = [
        {"name": f"Owner{i}", "sleeperTeamName": f"Team {i}", "ownerId": f"u{i}", "roster_id": i}
        for i in range(1, SEATS + 1)
    ]
    rows = [
        {
            "playerId": f"99{i}",
            "canonicalName": f"Rookie {i}",
            "position": ("WR", "RB", "QB", "TE")[i % 4],
            "rookie": True,
            "rankDerivedValue": 6000 - i * 40,
        }
        for i in range(1, 121)
    ]
    rows.append(
        {
            "playerId": "1",
            "canonicalName": "Veteran",
            "position": "QB",
            "rookie": False,
            "rankDerivedValue": 9000,
        }
    )
    return {"sleeper": {"teams": teams}, "playersArray": rows, "meta": {}}


# ---------------------------------------------------------------------------
# Small utilities
# ---------------------------------------------------------------------------


def now() -> float:
    # perf_counter: high resolution and one system-wide clock for this process.
    return time.perf_counter()


def pct(values: list[float], p: float) -> float | None:
    if not values:
        return None
    v = sorted(values)
    k = (len(v) - 1) * p
    lo = int(k)
    hi = min(lo + 1, len(v) - 1)
    return v[lo] + (v[hi] - v[lo]) * (k - lo)


def dist(values: list[float]) -> dict:
    if not values:
        return {"n": 0, "p50": None, "p95": None, "p99": None, "max": None}
    return {
        "n": len(values),
        "p50": pct(values, 0.5),
        "p95": pct(values, 0.95),
        "p99": pct(values, 0.99),
        "max": max(values),
    }


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def new_key() -> str:
    return "lt_" + secrets.token_hex(12)


def scrubbed_env() -> dict:
    return {k: v for k, v in os.environ.items() if not _SCRUB_RE.search(k)}


# ---------------------------------------------------------------------------
# Server process stats (psutil, else /proc, else Win32 via ctypes)
# ---------------------------------------------------------------------------


class ProcStats:
    def __init__(self, pid: int):
        self.pid = pid
        self.method = "unavailable"
        self.handle_label = "open FDs"
        self._p = None
        self._h = None
        if psutil is not None:
            try:
                self._p = psutil.Process(pid)
                self.method = "psutil"
                if os.name == "nt":
                    self.handle_label = "open handles (Windows handle count, not POSIX FDs)"
                return
            except Exception:  # noqa: BLE001
                self._p = None
        if sys.platform.startswith("linux") and Path(f"/proc/{pid}/stat").exists():
            self.method = "procfs"
            self._tck = os.sysconf("SC_CLK_TCK")
            return
        if os.name == "nt":
            try:
                import ctypes
                from ctypes import wintypes

                self._ct = ctypes
                self._wt = wintypes
                self._k32 = ctypes.WinDLL("kernel32", use_last_error=True)
                self._k32.OpenProcess.restype = wintypes.HANDLE
                h = self._k32.OpenProcess(0x1000, False, pid)  # QUERY_LIMITED_INFORMATION
                if h:
                    self._h = h
                    self.method = "win32-ctypes"
                    self.handle_label = "open handles (Windows handle count, not POSIX FDs)"
            except Exception:  # noqa: BLE001
                self._h = None

    def sample(self) -> dict | None:
        try:
            if self.method == "psutil":
                ct = self._p.cpu_times()
                out = {
                    "cpu_s": ct.user + ct.system,
                    "rss": self._p.memory_info().rss,
                    "threads": self._p.num_threads(),
                }
                try:
                    out["fds"] = self._p.num_fds() if os.name != "nt" else self._p.num_handles()
                except Exception:  # noqa: BLE001
                    out["fds"] = None
                return out
            if self.method == "procfs":
                with open(f"/proc/{self.pid}/stat", encoding="ascii") as fh:
                    parts = fh.read().rsplit(")", 1)[1].split()
                cpu = (int(parts[11]) + int(parts[12])) / self._tck
                threads = int(parts[17])
                rss = None
                with open(f"/proc/{self.pid}/status", encoding="ascii") as fh:
                    for line in fh:
                        if line.startswith("VmRSS:"):
                            rss = int(line.split()[1]) * 1024
                try:
                    fds = len(os.listdir(f"/proc/{self.pid}/fd"))
                except OSError:
                    fds = None
                return {"cpu_s": cpu, "rss": rss, "fds": fds, "threads": threads}
            if self.method == "win32-ctypes":
                ct, wt = self._ct, self._wt

                class FILETIME(ct.Structure):
                    _fields_ = [("lo", wt.DWORD), ("hi", wt.DWORD)]

                class PMC(ct.Structure):
                    _fields_ = [
                        ("cb", wt.DWORD),
                        ("PageFaultCount", wt.DWORD),
                        ("PeakWorkingSetSize", ct.c_size_t),
                        ("WorkingSetSize", ct.c_size_t),
                        ("QuotaPeakPagedPoolUsage", ct.c_size_t),
                        ("QuotaPagedPoolUsage", ct.c_size_t),
                        ("QuotaPeakNonPagedPoolUsage", ct.c_size_t),
                        ("QuotaNonPagedPoolUsage", ct.c_size_t),
                        ("PagefileUsage", ct.c_size_t),
                        ("PeakPagefileUsage", ct.c_size_t),
                    ]

                c, e, k, u = FILETIME(), FILETIME(), FILETIME(), FILETIME()
                if not self._k32.GetProcessTimes(
                    self._h, ct.byref(c), ct.byref(e), ct.byref(k), ct.byref(u)
                ):
                    return None
                cpu = (((k.hi << 32) | k.lo) + ((u.hi << 32) | u.lo)) / 1e7
                pmc = PMC()
                pmc.cb = ct.sizeof(PMC)
                rss = None
                if self._k32.K32GetProcessMemoryInfo(self._h, ct.byref(pmc), pmc.cb):
                    rss = int(pmc.WorkingSetSize)
                hc = wt.DWORD()
                fds = (
                    int(hc.value)
                    if self._k32.GetProcessHandleCount(self._h, ct.byref(hc))
                    else None
                )
                return {"cpu_s": cpu, "rss": rss, "fds": fds, "threads": None}
        except Exception:  # noqa: BLE001
            return None
        return None


# ---------------------------------------------------------------------------
# Records
# ---------------------------------------------------------------------------


@dataclass
class Cmd:
    manager: int
    kind: str
    purpose: str
    key: str
    body: dict
    t_send: float
    t_ack: float | None = None
    status: int | None = None
    error: str | None = None
    revision: int | None = None
    replayed: bool = False
    noop: bool = False
    attempts: int = 0
    via_receipt: bool = False
    transport_error: str | None = None


@dataclass
class Manager:
    idx: int
    seat: str
    handle: str
    user_id: int | None = None
    cookie: str = ""
    latest: dict | None = None
    latest_rev: int = -1
    parsed_rev: int = -1
    event_gaps: int = 0
    tab_count: int = 2
    tab_tasks: dict = field(default_factory=dict)


class Harness:
    def __init__(self, args: argparse.Namespace):
        self.a = args
        self.rng = random.Random(args.seed)
        self.run_id = secrets.token_hex(3)
        self.tmp = Path(tempfile.mkdtemp(prefix="auction_load_"))
        self.db_path = self.tmp / "auction" / "auction.sqlite"
        self.log_path = self.tmp / "server.log"
        self.admin_token = secrets.token_urlsafe(32)
        self.port = args.port or free_port()
        self.base = f"http://127.0.0.1:{self.port}"
        self.origin = self.base
        self.proc: subprocess.Popen | None = None
        self.server_pid: int | None = None
        self.log_fh = None
        self.room: str = ""
        self.pool_ids: list[str] = []
        self.managers: list[Manager] = []
        self.contract_kind = ""
        # measurements
        self.cmds: list[Cmd] = []
        self.obs: dict[tuple[int, int], list[tuple[float, int]]] = defaultdict(list)
        self.http_status: Counter = Counter()
        self.error_codes: Counter = Counter()
        self.transport_errors: Counter = Counter()
        self.locked_bodies = 0
        self.retries = 0
        self.receipt_lookups = 0
        self.out_of_order = 0
        self.poll_unchanged = 0
        self.reconnects: list[float] = []
        self.advice: list[tuple[float, int | None, str | None, str | None]] = []
        self.notify: list[tuple[float, int | None]] = []
        self.health: list[tuple[float, float | None]] = []
        self.health_baseline: list[float] = []
        self.clock_jumps: list[tuple[float, int | None]] = []
        self.client_lag: list[float] = []
        self.proc_samples: list[tuple[float, dict]] = []
        self.server_threads: list[int] = []
        self.replay_checks = Counter()
        self.violations: list[str] = []
        self.notes: list[str] = []
        self.t_load0 = 0.0
        self.t_load1 = 0.0
        self.stop_load = asyncio.Event()
        self.stop_polls = asyncio.Event()
        self.nomination_setup: dict = {}

    # -- server lifecycle ---------------------------------------------------

    def prepare_contract(self) -> Path:
        mode = self.a.contract
        export = None
        if mode in ("auto", "export"):
            if self.a.export_path:
                export = Path(self.a.export_path)
            else:
                cands = sorted((REPO / "exports" / "latest").glob("dynasty_data_*.json"))
                export = cands[-1] if cands else None
            if export is None or not export.exists():
                if mode == "export":
                    raise RuntimeError("no local export found for --contract export")
                export = None
        if export is None:
            path = self.tmp / "contract.json"
            path.write_text(json.dumps(synthetic_contract()), encoding="utf-8")
            self.contract_kind = "synthetic (12 teams, 120 rookies, no real rosters)"
            return path
        digest = hashlib.sha256(export.read_bytes()).hexdigest()[:16]
        cache_dir = Path(tempfile.gettempdir()) / "auction_load_contract_cache"
        cache_dir.mkdir(parents=True, exist_ok=True)
        cached = cache_dir / f"contract_{digest}.json"
        if not cached.exists():
            print(f"[setup] building contract from {export.name} (one-time, ~30-60 s) ...")
            part = cached.with_suffix(".part")
            subprocess.run(
                [sys.executable, "-c", _BUILD_CONTRACT, str(export), str(part), str(REPO)],
                cwd=str(self.tmp),
                env=scrubbed_env(),
                check=True,
                timeout=900,
            )
            part.replace(cached)
        self.contract_kind = f"local export {export.name} (built contract, cached {cached.name})"
        return cached

    def start_server(self, contract_path: Path) -> None:
        (self.tmp / "auction_load_app.py").write_text(SHIM_SOURCE, encoding="utf-8")
        env = scrubbed_env()
        env.update(
            {
                "PYTHONPATH": str(REPO),
                "PYTHONUNBUFFERED": "1",
                "RISKIT_AUCTION_DB": str(self.db_path),
                "JASON_AUTH_COOKIE_SECURE": "0",
                "RISKIT_FEATURE_ROOKIE_AUCTION": "1",
                "RISKIT_FEATURE_PERFECT_DRAFT": "1",
                "AUCTION_LOAD_ADMIN_TOKEN": self.admin_token,
                "AUCTION_LOAD_CONTRACT": str(contract_path),
                "AUCTION_LOAD_REPO": str(REPO),
            }
        )
        cmd = [
            sys.executable,
            "-m",
            "uvicorn",
            "auction_load_app:app",
            "--app-dir",
            str(self.tmp),
            "--host",
            "127.0.0.1",
            "--port",
            str(self.port),
            "--log-level",
            self.a.server_log_level,
        ]
        self.log_fh = open(self.log_path, "wb")  # noqa: SIM115
        kw: dict[str, Any] = {}
        if os.name == "nt":
            kw["creationflags"] = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
        self.proc = subprocess.Popen(
            cmd, cwd=str(self.tmp), env=env, stdout=self.log_fh, stderr=subprocess.STDOUT, **kw
        )

    async def wait_ready(self) -> None:
        deadline = time.monotonic() + self.a.startup_timeout
        async with httpx.AsyncClient(base_url=self.base, verify=_SSL, timeout=5) as c:
            while time.monotonic() < deadline:
                if self.proc and self.proc.poll() is not None:
                    raise RuntimeError(f"server exited early (code {self.proc.returncode})")
                try:
                    r = await c.get("/api/_load/metrics")
                    if r.status_code == 200:
                        self.server_pid = int(r.json()["pid"])
                        return
                except httpx.HTTPError:
                    pass
                await asyncio.sleep(0.5)
        raise RuntimeError("server did not become ready in time")

    def kill_server(self) -> None:
        """Crash-style stop: acknowledged actions must survive a hard kill."""
        pids = [p for p in (self.server_pid, self.proc.pid if self.proc else None) if p]
        for pid in dict.fromkeys(pids):
            try:
                os.kill(pid, signal.SIGKILL if hasattr(signal, "SIGKILL") else signal.SIGTERM)
            except OSError:
                pass
        if self.proc:
            try:
                self.proc.wait(timeout=15)
            except subprocess.TimeoutExpired:
                self.proc.kill()
        if self.log_fh:
            self.log_fh.close()
            self.log_fh = None

    # -- HTTP plumbing --------------------------------------------------------

    def client(self, cookie: str | None = None, *, extra_cookie: str | None = None):
        headers = {"Origin": self.origin}
        cookies = []
        if cookie:
            cookies.append(f"cu_auction_session={cookie}")
        if extra_cookie:
            cookies.append(extra_cookie)
        if cookies:
            headers["Cookie"] = "; ".join(cookies)
        return httpx.AsyncClient(
            base_url=self.base,
            verify=_SSL,
            headers=headers,
            timeout=httpx.Timeout(60.0, connect=10.0),
            limits=httpx.Limits(max_connections=20, max_keepalive_connections=10),
        )

    async def call(
        self, c, method: str, path: str, category: str, *, timeout: float = 30.0, **kw
    ) -> tuple[int | None, bytes, str | None]:
        try:
            r = await c.request(method, path, timeout=timeout, **kw)
        except httpx.HTTPError as exc:
            name = type(exc).__name__
            self.transport_errors[f"{category}:{name}"] += 1
            self.http_status[(category, "transport")] += 1
            return None, b"", name
        self.http_status[(category, r.status_code)] += 1
        body = r.content
        if r.status_code >= 400:
            try:
                code = json.loads(body).get("error")
            except (ValueError, AttributeError):
                code = None
            self.error_codes[(category, r.status_code, code)] += 1
            if b"locked" in body.lower():
                self.locked_bodies += 1
        return r.status_code, body, None

    # -- setup ------------------------------------------------------------------

    async def setup(self) -> None:
        owner = self.client(extra_cookie=f"jason_session={self.admin_token}")
        try:
            r = await owner.post("/api/auction/auth/site-owner")
            if r.status_code != 200:
                raise RuntimeError(f"site-owner bridge failed: {r.status_code} {r.text[:200]}")
            owner_cookie = r.cookies.get("cu_auction_session")
            owner_user = r.json()["user"]
        finally:
            await owner.aclose()
        m0 = Manager(0, "S1", "owner", user_id=owner_user.get("id"), cookie=owner_cookie)
        self.managers = [m0]
        oc = self.client(owner_cookie)
        try:
            body = {
                "name": f"Load rehearsal {self.run_id}",
                "preset": "fast",
                "seatSource": "league",
                "budgetSource": "equal",
                "equalAmount": 100,
                "bots": False,
                "seed": self.a.seed,
            }
            r = await oc.post("/api/auction/rooms", json=body)
            if r.status_code != 200:
                body["seatSource"] = "generic"
                r = await oc.post("/api/auction/rooms", json=body)
            if r.status_code != 200:
                raise RuntimeError(f"create room failed: {r.status_code} {r.text[:200]}")
            self.room = r.json()["roomId"]
            budgets = (
                [int(x) for x in self.a.budgets.split(",")] if self.a.budgets else DEFAULT_BUDGETS
            )
            if len(budgets) != SEATS:
                raise RuntimeError("--budgets needs exactly 12 comma-separated integers")
            for i, b in enumerate(budgets):
                await self._setup_cmd(
                    oc,
                    {
                        "kind": "set_seat",
                        "seat": f"S{i + 1}",
                        "patch": {"opening_budget": b},
                        "reason": "load rehearsal budget",
                    },
                )
            await self._setup_cmd(
                oc,
                {
                    "kind": "configure",
                    "rules": {
                        "auction_active_seconds": self.a.lot_seconds,
                        "extension_active_seconds": self.a.extension_seconds,
                    },
                },
            )
            # 11 more humans through the room's own invite flow.
            for i in range(1, SEATS):
                handle = f"load{self.run_id}m{i + 1:02d}"
                r = await oc.post(
                    f"/api/auction/rooms/{self.room}/invites",
                    json={"seat": f"S{i + 1}", "intendedHandle": handle, "ttlHours": 2},
                )
                if r.status_code != 200:
                    raise RuntimeError(f"invite failed: {r.status_code} {r.text[:200]}")
                token = r.json()["joinPath"].split("token=")[1]
                async with self.client() as nc:
                    r2 = await nc.post(
                        "/api/auction/invites/claim",
                        json={
                            "token": token,
                            "handle": handle,
                            "password": secrets.token_urlsafe(18),
                        },
                    )
                if r2.status_code != 200:
                    raise RuntimeError(f"claim failed: {r2.status_code} {r2.text[:200]}")
                self.managers.append(
                    Manager(
                        i,
                        f"S{i + 1}",
                        handle,
                        user_id=r2.json()["user"].get("id"),
                        cookie=r2.cookies.get("cu_auction_session"),
                    )
                )
            await self._setup_cmd(oc, {"kind": "start"})
            r = await oc.get(f"/api/auction/rooms/{self.room}/pool")
            self.pool_ids = sorted(r.json()["players"].keys())
        finally:
            await oc.aclose()
        for m in self.managers:
            m.tab_count = self.rng.randint(self.a.tabs_min, self.a.tabs_max)
        # All 12 nominate at once (the opening burst).
        picks = self.rng.sample(self.pool_ids, SEATS)
        clients = [self.client(m.cookie) for m in self.managers]
        try:
            t0 = now()
            recs = await asyncio.gather(
                *[
                    self.command(m, c, {"kind": "nominate", "player": p}, "setup_nominate")
                    for m, c, p in zip(self.managers, clients, picks, strict=True)
                ]
            )
            self.nomination_setup = {
                "wall_s": now() - t0,
                "accepted": sum(1 for r in recs if r.status == 200),
            }
            r = await clients[0].get(f"/api/auction/rooms/{self.room}/view")
            open_count = r.json()["public"]["open_count"]
        finally:
            for c in clients:
                await c.aclose()
        self.nomination_setup["open_lots"] = open_count
        if open_count != SEATS:
            raise RuntimeError(f"expected 12 open lots after the opening burst, got {open_count}")

    async def _setup_cmd(self, c, body: dict) -> None:
        r = await c.post(
            f"/api/auction/rooms/{self.room}/commands",
            json=body,
            headers={"Idempotency-Key": new_key()},
        )
        if r.status_code != 200:
            raise RuntimeError(f"{body['kind']} failed: {r.status_code} {r.text[:200]}")

    # -- commands (mirrors frontend sendCommand) --------------------------------

    async def command(self, m: Manager, c, body: dict, purpose: str, key: str | None = None) -> Cmd:
        rec = Cmd(m.idx, body["kind"], purpose, key or new_key(), body, t_send=now())
        path = f"/api/auction/rooms/{self.room}/commands"
        for i in range(3):
            rec.attempts += 1
            st, raw, terr = await self.call(
                c, "POST", path, "command", json=body, headers={"Idempotency-Key": rec.key}
            )
            if st is not None and st < 502:
                rec.status = st
                self._fill(rec, raw)
                break
            rec.transport_error = terr or f"http_{st}"
            # Unknown outcome: ask whether it committed before re-sending.
            self.receipt_lookups += 1
            rst, rraw, _ = await self.call(
                c, "GET", f"/api/auction/rooms/{self.room}/receipts/{rec.key}", "receipt"
            )
            if rst == 200:
                receipt = json.loads(rraw)
                rec.status = int(receipt["status"])
                rec.revision = receipt.get("revision")
                res = receipt.get("result") or {}
                rec.noop = bool(res.get("noop"))
                rec.error = res.get("error")
                rec.via_receipt = True
                break
            if i < 2:
                self.retries += 1
                await asyncio.sleep(0.4 * (i + 1))
        rec.t_ack = now()
        self.cmds.append(rec)
        return rec

    @staticmethod
    def _fill(rec: Cmd, raw: bytes) -> None:
        try:
            js = json.loads(raw)
        except ValueError:
            return
        rec.revision = js.get("revision")
        rec.replayed = bool(js.get("replayed"))
        rec.noop = bool(js.get("noop"))
        rec.error = js.get("error")

    # -- tabs (long-poll clients) -------------------------------------------------

    def _observe(self, m: Manager, tab: int, raw: bytes, prev: int) -> int:
        t = now()
        mt = _REV_RE.match(raw[:40])
        if mt:
            rev = int(mt.group(1))
        else:
            try:
                rev = int(json.loads(raw)["revision"])
            except (ValueError, KeyError, TypeError):
                return prev
        self.obs[(m.idx, tab)].append((t, rev))
        if rev < prev:
            self.out_of_order += 1  # dropped, exactly like the frontend
            return prev
        if rev == prev:
            self.poll_unchanged += 1
        if rev > m.latest_rev:
            try:
                view = json.loads(raw)
            except ValueError:
                return rev
            evs = view.get("events") or []
            if m.parsed_rev >= 0 and len(evs) >= EVENT_LIMIT:
                oldest = min(int(e["revision"]) for e in evs)
                if oldest > m.parsed_rev + 1:
                    m.event_gaps += 1
            m.latest = view
            m.latest_rev = rev
            m.parsed_rev = rev
        return rev

    async def tab_loop(self, m: Manager, tab: int, reconnect_t0: float | None = None) -> None:
        c = self.client(m.cookie)
        rev = -1
        view_path = f"/api/auction/rooms/{self.room}/view"
        try:
            while not self.stop_polls.is_set():
                st, raw, _ = await self.call(c, "GET", view_path, "view_initial")
                if st == 200:
                    rev = self._observe(m, tab, raw, rev)
                    break
                await asyncio.sleep(2.0)
            if reconnect_t0 is not None:
                self.reconnects.append(now() - reconnect_t0)
            failures = 0
            wait = self.a.poll_wait
            while not self.stop_polls.is_set():
                st, raw, _ = await self.call(
                    c,
                    "GET",
                    f"{view_path}?after={rev}&wait={wait}",
                    "view_poll",
                    timeout=wait + 20,
                )
                if st == 200:
                    rev = self._observe(m, tab, raw, rev)
                    failures = 0
                else:
                    failures += 1
                    await asyncio.sleep(min(10.0, 1.0 * 2 ** min(failures, 4)))
        finally:
            await c.aclose()

    # -- load actors --------------------------------------------------------------

    def _in_burst(self) -> bool:
        if self.a.burst_every <= 0:
            return False
        el = now() - self.t_load0
        return (el % self.a.burst_every) < self.a.burst_seconds

    def _choose(self, m: Manager, rng: random.Random) -> tuple[dict, str] | None:
        v = m.latest
        if not v:
            return None
        pub = v.get("public") or {}
        priv = (v.get("me") or {}).get("private") or {}
        auctions = pub.get("auctions") or []
        taken = {a["player"] for a in auctions}
        avail = [p for p in self.pool_ids if p not in taken]
        open_lots = [a for a in auctions if a["status"] == "open"]
        balance = int(priv.get("balance") or 0)
        mine = {b["auction"]: b for b in priv.get("my_bids") or []}
        if priv.get("on_clock") and avail and rng.random() < 0.85:
            return {"kind": "nominate", "player": rng.choice(avail)}, "nominate_on_clock"
        r = rng.random()
        if not open_lots or r < 0.03:
            if not avail:
                return None
            return {"kind": "nominate", "player": rng.choice(avail)}, "nominate_off_clock"
        if rng.random() < 0.03:  # deliberately unaffordable (expected 409 over_balance)
            lot = rng.choice(open_lots)
            return {
                "kind": "bid",
                "auction": lot["id"],
                "max": balance + rng.randint(1, 20),
            }, "over_balance"
        if r < 0.10:
            zero = [a for a in open_lots if int(a["price"]) == 0 and a.get("leader") != m.seat]
            if zero:
                return {"kind": "bid", "auction": rng.choice(zero)["id"], "max": 0}, "zero_bid"
        # Managers bid where they can afford to; a few hot lots draw most action.
        afford = [a for a in open_lots if int(a["price"]) + 1 <= balance]
        if not afford:
            return None
        lot = rng.choice(afford[:4]) if rng.random() < 0.5 else rng.choice(afford)
        price = int(lot["price"])
        leading = lot.get("leader") == m.seat
        if r < 0.35:
            if leading and lot["id"] in mine:
                cur = int(mine[lot["id"]]["max"])
                if cur >= balance:
                    return None
                return {
                    "kind": "bid",
                    "auction": lot["id"],
                    "max": min(balance, cur + rng.randint(1, 15)),
                }, "leader_raise"
            return {"kind": "bid", "auction": lot["id"], "max": price + 1}, "min_raise"
        if r < 0.40:
            cand = [a for a in open_lots if a["id"] in mine and a.get("leader") != m.seat]
            if cand:
                return {"kind": "withdraw", "auction": rng.choice(cand)["id"]}, "withdraw"
        top = max(price + 1, int(balance * rng.random()))
        return {
            "kind": "bid",
            "auction": lot["id"],
            "max": rng.randint(price + 1, max(price + 1, top)),
        }, "proxy"

    async def bidder(self, m: Manager, n: int) -> None:
        rng = random.Random(self.a.seed * 1000 + m.idx * 10 + n)
        c = self.client(m.cookie)
        try:
            while not self.stop_load.is_set():
                mean = self.a.burst_interval if self._in_burst() else self.a.bid_interval
                await asyncio.sleep(rng.expovariate(1.0 / mean))
                if self.stop_load.is_set():
                    break
                choice = self._choose(m, rng)
                if choice is None:
                    continue
                body, purpose = choice
                rec = await self.command(m, c, body, purpose)
                if rec.status == 200 and not rec.replayed:
                    roll = rng.random()
                    if roll < self.a.replay_rate:
                        again = await self.command(m, c, body, "replay_same_key", key=rec.key)
                        ok = (
                            again.status == 200
                            and again.replayed
                            and again.revision == rec.revision
                        )
                        self.replay_checks["replay_ok" if ok else "replay_MISMATCH"] += 1
                        if not ok:
                            self.violations.append(
                                f"idempotent replay mismatch key={rec.key} first=(200,{rec.revision})"
                                f" again=({again.status},{again.revision},replayed={again.replayed})"
                            )
                    elif roll < self.a.replay_rate + self.a.conflict_rate and body["kind"] == "bid":
                        changed = {**body, "max": int(body["max"]) + 1}
                        again = await self.command(m, c, changed, "conflict_same_key", key=rec.key)
                        ok = again.status == 409 and again.error == "idempotency_conflict"
                        self.replay_checks["conflict_ok" if ok else "conflict_MISMATCH"] += 1
                        if not ok:
                            self.violations.append(
                                f"idempotency conflict not refused key={rec.key}"
                                f" got=({again.status},{again.error})"
                            )
        finally:
            await c.aclose()

    async def advice_loop(self, m: Manager) -> None:
        rng = random.Random(self.a.seed * 7 + m.idx)
        c = self.client(m.cookie)
        try:
            await asyncio.sleep(rng.random() * 2.0)  # everyone opens the room at once
            while not self.stop_load.is_set():
                t0 = now()
                st, raw, _ = await self.call(
                    c,
                    "GET",
                    f"/api/auction/rooms/{self.room}/advice-context",
                    "advice",
                    timeout=120,
                )
                lat = now() - t0
                a_status = reason = None
                if st == 200:
                    try:
                        js = json.loads(raw)
                        a_status, reason = js.get("status"), js.get("reason")
                    except ValueError:
                        pass
                self.advice.append((lat, st, a_status, reason))
                await asyncio.sleep(self.a.advice_interval * (0.5 + rng.random()))
        finally:
            await c.aclose()

    async def notify_loop(self, m: Manager) -> None:
        rng = random.Random(self.a.seed * 11 + m.idx)
        c = self.client(m.cookie)
        paths = ["/api/auction/notify/state", f"/api/auction/notify/inbox?roomId={self.room}"]
        try:
            i = 0
            await asyncio.sleep(rng.random() * 3.0)
            while not self.stop_load.is_set():
                t0 = now()
                st, _, _ = await self.call(c, "GET", paths[i % 2], "notify")
                self.notify.append((now() - t0, st))
                i += 1
                await asyncio.sleep(self.a.notify_interval * (0.5 + rng.random()))
        finally:
            await c.aclose()

    async def health_loop(self, sink: list, stop: asyncio.Event) -> None:
        async with httpx.AsyncClient(base_url=self.base, verify=_SSL, timeout=10) as c:
            while not stop.is_set():
                t0 = now()
                try:
                    r = await c.get("/api/health")
                    lat = now() - t0 if r.status_code == 200 else None
                    self.http_status[("health", r.status_code)] += 1
                except httpx.HTTPError as exc:
                    self.transport_errors[f"health:{type(exc).__name__}"] += 1
                    lat = None
                sink.append((t0, lat))
                await asyncio.sleep(max(0.0, self.a.health_interval - (now() - t0)))

    async def reconnect_loop(self) -> None:
        rng = random.Random(self.a.seed * 13)
        while not self.stop_load.is_set():
            await asyncio.sleep(self.a.reconnect_every)
            if self.stop_load.is_set():
                break
            m = rng.choice(self.managers)
            tab = rng.randrange(m.tab_count)
            task = m.tab_tasks.get(tab)
            if task is not None:
                task.cancel()
                try:
                    await task
                except (asyncio.CancelledError, Exception):  # noqa: BLE001
                    pass
            t0 = now()
            m.tab_tasks[tab] = asyncio.create_task(self.tab_loop(m, tab, reconnect_t0=t0))

    async def clock_loop(self) -> None:
        if self.a.clock_jump_every <= 0:
            return
        c = self.client(self.managers[0].cookie)
        try:
            while not self.stop_load.is_set():
                await asyncio.sleep(self.a.clock_jump_every)
                if self.stop_load.is_set():
                    break
                t0 = now()
                st, _, _ = await self.call(
                    c,
                    "POST",
                    f"/api/auction/rooms/{self.room}/clock",
                    "clock_jump",
                    json={"advanceSeconds": self.a.clock_jump_seconds},
                )
                self.clock_jumps.append((now() - t0, st))
        finally:
            await c.aclose()

    async def lag_loop(self, stop: asyncio.Event) -> None:
        while not stop.is_set():
            t0 = now()
            await asyncio.sleep(0.05)
            self.client_lag.append(now() - t0 - 0.05)

    async def sampler(self, stop: asyncio.Event, ps: ProcStats) -> None:
        async with httpx.AsyncClient(base_url=self.base, verify=_SSL, timeout=10) as c:
            while not stop.is_set():
                s = ps.sample()
                if s is not None:
                    self.proc_samples.append((now(), s))
                try:
                    r = await c.get("/api/_load/metrics")
                    self.server_threads.append(int(r.json()["threads"]))
                except (httpx.HTTPError, ValueError, KeyError):
                    pass
                await asyncio.sleep(1.0)

    # -- the run --------------------------------------------------------------------

    async def run_load(self) -> None:
        async with httpx.AsyncClient(base_url=self.base, verify=_SSL, timeout=10) as c:
            await c.post("/api/_load/reset")
        ps = ProcStats(self.server_pid or 0)
        self.proc_method = ps.method
        self.handle_label = ps.handle_label
        aux_stop = asyncio.Event()
        aux = [
            asyncio.create_task(self.health_loop(self.health, aux_stop)),
            asyncio.create_task(self.lag_loop(aux_stop)),
            asyncio.create_task(self.sampler(aux_stop, ps)),
        ]
        self.t_load0 = now()
        for m in self.managers:
            for tab in range(m.tab_count):
                m.tab_tasks[tab] = asyncio.create_task(self.tab_loop(m, tab))
        # Let every tab take its first snapshot before bidding.
        await asyncio.sleep(1.0)
        load = []
        for m in self.managers:
            for n in range(self.a.bidders_per_manager):
                load.append(asyncio.create_task(self.bidder(m, n)))
            load.append(asyncio.create_task(self.advice_loop(m)))
            load.append(asyncio.create_task(self.notify_loop(m)))
        load.append(asyncio.create_task(self.reconnect_loop()))
        load.append(asyncio.create_task(self.clock_loop()))
        await asyncio.sleep(self.a.duration)
        self.stop_load.set()
        self.t_load1 = now()
        print("[load] duration reached; stopping actors, draining in-flight commands ...")
        done, pending = await asyncio.wait(load, timeout=90)
        for t in pending:
            t.cancel()
        for t in done:
            if t.exception() is not None:
                self.notes.append(f"actor task error: {t.exception()!r}")
        # Drain: every tab should converge on the server's final revision.
        await self.drain()
        self.stop_polls.set()
        for m in self.managers:
            for t in m.tab_tasks.values():
                t.cancel()
            for t in m.tab_tasks.values():
                try:
                    await t
                except (asyncio.CancelledError, Exception):  # noqa: BLE001
                    pass
        async with httpx.AsyncClient(base_url=self.base, verify=_SSL, timeout=30) as c:
            self.server_metrics = (await c.get("/api/_load/metrics")).json()
        aux_stop.set()
        await asyncio.gather(*aux, return_exceptions=True)

    async def drain(self) -> None:
        c = self.client(self.managers[0].cookie)
        try:
            deadline = now() + self.a.drain_seconds
            final = None
            while now() < deadline:
                st, raw, _ = await self.call(
                    c, "GET", f"/api/auction/rooms/{self.room}/view", "final"
                )
                if st == 200:
                    final = int(json.loads(raw)["revision"])
                    lag = [
                        (m.idx, tab)
                        for m in self.managers
                        for tab in m.tab_tasks
                        if not self.obs[(m.idx, tab)] or self.obs[(m.idx, tab)][-1][1] < final
                    ]
                    if not lag:
                        break
                await asyncio.sleep(0.25)
            self.final_revision = final
            self.tabs_behind_at_end = []
            if final is not None:
                for m in self.managers:
                    for tab in m.tab_tasks:
                        o = self.obs[(m.idx, tab)]
                        last = o[-1][1] if o else -1
                        if last < final:
                            self.tabs_behind_at_end.append((m.seat, tab, last, final))
        finally:
            await c.aclose()

    # -- verification -----------------------------------------------------------------

    async def verify_http(self) -> None:
        """Fresh read of every seat's view + every acknowledged receipt."""
        oc = self.client(self.managers[0].cookie)
        try:
            r = await oc.get(f"/api/auction/rooms/{self.room}/view")
            view = r.json()
        finally:
            await oc.aclose()
        pub = view["public"]
        self.final_public = pub
        for s in pub["seats"]:
            bal, com, sp = s["balance"], s["committed"], s["spendable"]
            if bal is None:
                continue
            if bal < 0 or com > bal or sp < 0:
                self.violations.append(
                    f"HTTP view: seat {s['id']} overspent balance={bal} committed={com} spendable={sp}"
                )
        players = Counter(a["player"] for a in pub["auctions"])
        dup = [p for p, n in players.items() if n > 1]
        if dup:
            self.violations.append(f"HTTP view: players nominated/won more than once: {dup}")
        for a in pub["auctions"]:
            if a["status"] == "closed" and not a["winner"]:
                self.violations.append(f"HTTP view: closed lot {a['id']} without a winner")
        # each seat's own private ledger
        for m in self.managers:
            async with self.client(m.cookie) as c:
                r = await c.get(f"/api/auction/rooms/{self.room}/view")
                priv = r.json()["me"]["private"] or {}
            bal, com, sp = priv.get("balance"), priv.get("committed"), priv.get("spendable")
            if bal is not None and (bal < 0 or com > bal or sp < 0):
                self.violations.append(
                    f"HTTP private view: seat {m.seat} balance={bal} committed={com} spendable={sp}"
                )
        # every acknowledged command has a durable receipt with the same outcome
        acked = [x for x in self.cmds if x.status == 200 and not x.replayed]
        sem = asyncio.Semaphore(16)
        clients = {m.idx: self.client(m.cookie) for m in self.managers}
        bad = 0

        async def check(x: Cmd) -> None:
            nonlocal bad
            async with sem:
                st, raw, _ = await self.call(
                    clients[x.manager],
                    "GET",
                    f"/api/auction/rooms/{self.room}/receipts/{x.key}",
                    "verify_receipt",
                )
            if st != 200:
                bad += 1
                self.violations.append(f"acknowledged command lost: key={x.key} receipt={st}")
                return
            rc = json.loads(raw)
            if int(rc["status"]) != 200 or rc.get("revision") != x.revision:
                bad += 1
                self.violations.append(
                    f"receipt disagrees with ack: key={x.key} ack=(200,{x.revision})"
                    f" receipt=({rc['status']},{rc.get('revision')})"
                )

        try:
            await asyncio.gather(*[check(x) for x in acked])
        finally:
            for c in clients.values():
                await c.aclose()
        self.receipts_checked = len(acked)
        self.receipts_bad = bad

    def verify_db(self) -> dict:
        """After a hard kill: fresh Store over the same file."""
        sys.path.insert(0, str(REPO))
        from src.auction import engine
        from src.auction.store import open_store

        out: dict[str, Any] = {}
        st = open_store(self.db_path)
        state, revision, _ = st.load(self.room)
        out["revision"] = revision
        out["status"] = state["status"]
        try:
            engine.check_invariants(state)
            out["engine_invariants"] = "ok"
        except AssertionError as exc:
            out["engine_invariants"] = f"FAILED: {exc}"
            self.violations.append(f"engine invariants: {exc}")
        report = st.verify_room(self.room)
        out["replay_matches"] = report["replay_matches"]
        out["awards_match"] = report["awards_match"]
        if not report["replay_matches"]:
            self.violations.append("command-log replay does not reproduce the room")
        if not report["awards_match"]:
            self.violations.append("awards table disagrees with closed lots")
        seats = []
        for s in state["seats"]:
            bal = engine.balance(state, s["id"])
            com = engine.committed(state, s["id"])
            seats.append((s["id"], s["opening_budget"], bal, com, bal - com))
            if bal < 0 or com > bal:
                self.violations.append(
                    f"DB: seat {s['id']} overspent balance={bal} committed={com}"
                )
        out["seats"] = seats
        closed = [a for a in state["auctions"].values() if a["status"] == "closed"]
        out["lots_total"] = len(state["auctions"])
        out["lots_closed"] = len(closed)
        out["lots_open"] = len(engine.open_auctions(state))
        out["bid_log_len"] = len(state.get("bid_log") or [])
        out["state_json_bytes"] = len(json.dumps(state, sort_keys=True))
        conn = sqlite3.connect(str(self.db_path))
        conn.row_factory = sqlite3.Row
        try:
            dup_awards = conn.execute(
                "SELECT player_id, COUNT(*) n FROM awards WHERE room_id=? GROUP BY player_id HAVING n>1",
                (self.room,),
            ).fetchall()
            if dup_awards:
                self.violations.append(f"duplicate winners: {[r['player_id'] for r in dup_awards]}")
            out["awards"] = conn.execute(
                "SELECT COUNT(*) FROM awards WHERE room_id=?", (self.room,)
            ).fetchone()[0]
            # Winners per settled player from the state itself.
            per_player = Counter(a["player"] for a in closed)
            if any(n > 1 for n in per_player.values()):
                self.violations.append("a player was settled more than once")
            idem = {
                (r["user_id"], r["key"]): r
                for r in conn.execute(
                    "SELECT user_id, key, revision, status, result_json, created_at FROM idempotency WHERE room_id=?",
                    (self.room,),
                )
            }
            dup_keys = conn.execute(
                "SELECT user_id, key, COUNT(*) n FROM idempotency WHERE room_id=? GROUP BY user_id, key HAVING n>1",
                (self.room,),
            ).fetchall()
            if dup_keys:
                self.violations.append(f"duplicate idempotency rows: {len(dup_keys)}")
            human_cmds = conn.execute(
                "SELECT revision, actor_user_id, kind, created_at FROM commands WHERE room_id=? AND actor_user_id IS NOT NULL",
                (self.room,),
            ).fetchall()
        finally:
            conn.close()
        out["idempotency_rows"] = len(idem)
        out["human_command_rows"] = len(human_cmds)
        # (1) every client-acknowledged 200 survived the hard kill, same revision.
        lost = 0
        by_uid = {m.idx: m.user_id for m in self.managers}
        max_acked = -1
        for x in self.cmds:
            if x.status is None:
                continue
            row = idem.get((by_uid[x.manager], x.key))
            if x.status == 200:
                max_acked = max(max_acked, x.revision or -1)
                if row is None or int(row["status"]) != 200 or row["revision"] != x.revision:
                    lost += 1
                    if lost <= 10:
                        self.violations.append(
                            f"DB: acknowledged action missing/changed key={x.key} row="
                            f"{None if row is None else (row['status'], row['revision'])}"
                        )
            elif (
                row is not None and int(row["status"]) == 200 and x.error != "idempotency_conflict"
            ):
                self.violations.append(
                    f"DB: client saw {x.status} but receipt says 200 key={x.key}"
                )
        out["lost_acknowledged"] = lost
        if revision < max_acked:
            self.violations.append(f"DB revision {revision} < highest acknowledged {max_acked}")
        # (2) every human command row was committed by exactly one accepted
        # receipt.  Store.execute stamps the SAME now_real on the command row and
        # its idempotency row, so (user, revision, created_at) is an exact join.
        # Note a receipt saying {"noop": true} can still own a command row: the
        # engine settles lots that fell due at the command's own server time in
        # the same transaction, so the revision advances even though the bid
        # itself changed nothing.  Joining on revision alone miscounts both that
        # case and later no-op resubmissions that record the unchanged revision.
        # On Windows + Python < 3.13 time.time() ticks at ~15.6 ms, so a later
        # no-op resubmission by the same user can share that (revision,
        # now_real) exactly: the owner is the one NON-no-op receipt, or a lone
        # no-op receipt (the settle-due case above).
        real_by_commit: dict[tuple[int, int, float], list[str]] = defaultdict(list)
        noop_by_commit: dict[tuple[int, int, float], list[str]] = defaultdict(list)
        noop_receipts = 0
        for (uid, key), r in idem.items():
            if int(r["status"]) != 200:
                continue
            try:
                res = json.loads(r["result_json"]) or {}
            except (TypeError, ValueError):
                res = {}
            k = (uid, r["revision"], float(r["created_at"]))
            if isinstance(res, dict) and res.get("noop"):
                noop_receipts += 1
                noop_by_commit[k].append(key)
            else:
                real_by_commit[k].append(key)
        out["noop_receipts"] = noop_receipts
        orphan = []
        for c in human_cmds:
            k = (c["actor_user_id"], c["revision"], float(c["created_at"]))
            real = real_by_commit.get(k, [])
            noop = noop_by_commit.get(k, [])
            if not (len(real) == 1 or (not real and len(noop) == 1)):
                orphan.append((c["revision"], c["actor_user_id"], c["kind"], real + noop))
        out["command_rows_without_single_receipt"] = len(orphan)
        if orphan:
            self.violations.append(
                f"{len(orphan)} applied command rows are not owned by exactly one accepted"
                f" receipt; e.g. (revision, user, kind, keys) {orphan[:5]}"
            )
        # (3) every accepted, non-noop bid / nomination / withdrawal changes the
        # room (the engine appends to bid_log or flips a bid), so each must be in
        # the command log at its acknowledged revision, by its own user and kind.
        cmd_rows = {(c["actor_user_id"], c["revision"]): c["kind"] for c in human_cmds}
        missing = 0
        for x in self.cmds:
            if (
                x.status == 200
                and not x.replayed
                and not x.noop
                and x.kind in ("bid", "nominate", "withdraw")
                and cmd_rows.get((by_uid[x.manager], x.revision)) != x.kind
            ):
                missing += 1
        out["accepted_actions_missing_from_log"] = missing
        if missing:
            self.violations.append(f"{missing} accepted actions are not in the command log")
        return out

    def scan_log(self) -> dict:
        try:
            text = self.log_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return {}
        return {
            "database is locked": text.count("database is locked"),
            "OperationalError": text.count("OperationalError"),
            "Traceback": text.count("Traceback"),
            "ERROR lines": sum(
                1 for ln in text.splitlines() if " ERROR" in ln or ln.startswith("ERROR")
            ),
            "HTTP 5xx access lines": len(re.findall(r'" 5\d\d', text)),
        }

    # -- analysis -------------------------------------------------------------------------

    def propagation(self) -> dict:
        # Per manager: merged observations (any tab), running max.
        series: dict[int, tuple[list[float], list[int]]] = {}
        for m in self.managers:
            pts = sorted(p for (mi, _), obs in self.obs.items() if mi == m.idx for p in obs)
            ts, rm = [], []
            best = -1
            for t, r in pts:
                best = max(best, r)
                ts.append(t)
                rm.append(best)
            series[m.idx] = (ts, rm)
        per_client: list[float] = []
        all_clients: list[float] = []
        missed_pairs = 0
        missed_by_seat: Counter = Counter()
        acks = [
            x
            for x in self.cmds
            if x.status == 200
            and not x.replayed
            and not x.noop
            and x.revision is not None
            and x.t_ack is not None
            and x.t_ack <= self.t_load1
        ]
        for x in acks:
            worst = 0.0
            complete = True
            for m in self.managers:
                if m.idx == x.manager:
                    continue
                ts, rm = series[m.idx]
                i = bisect.bisect_left(rm, x.revision)
                if i >= len(rm):
                    missed_pairs += 1
                    missed_by_seat[m.seat] += 1
                    complete = False
                    continue
                d = max(0.0, ts[i] - x.t_ack)
                per_client.append(d)
                worst = max(worst, d)
            if complete:
                all_clients.append(worst)
        return {
            "acks": len(acks),
            "per_client": per_client,
            "all_clients": all_clients,
            "missed_pairs": missed_pairs,
            "missed_by_seat": dict(missed_by_seat),
        }

    def timeline(self) -> list[dict]:
        rows = []
        width = 10.0
        span = self.t_load1 - self.t_load0
        nb = max(1, math.ceil(span / width))
        bids = [x for x in self.cmds if x.kind == "bid" and x.t_ack is not None]
        for b in range(nb):
            lo, hi = self.t_load0 + b * width, self.t_load0 + (b + 1) * width
            bl = [x.t_ack - x.t_send for x in bids if lo <= x.t_send < hi]
            hl = [lat for t, lat in self.health if lo <= t < hi and lat is not None]
            cpu = None
            ss = [(t, s) for t, s in self.proc_samples if lo <= t < hi]
            if len(ss) >= 2 and ss[0][1].get("cpu_s") is not None:
                cpu = 100.0 * (ss[-1][1]["cpu_s"] - ss[0][1]["cpu_s"]) / (ss[-1][0] - ss[0][0])
            rows.append(
                {
                    "t": f"{b * width:>4.0f}-{(b + 1) * width:<4.0f}",
                    "cmds": sum(1 for x in self.cmds if lo <= x.t_send < hi),
                    "bid_p95": pct(bl, 0.95),
                    "health_max": max(hl) if hl else None,
                    "cpu_pct": cpu,
                }
            )
        return rows


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


def fmt(v: float | None, unit: str = "s") -> str:
    if v is None:
        return "-"
    if unit == "s":
        return f"{v * 1000:.0f}ms" if v < 1 else f"{v:.2f}s"
    return f"{v:.1f}"


def report(h: Harness, db: dict, log_counts: dict, prop: dict) -> dict:
    a = h.a
    bid_lat = [x.t_ack - x.t_send for x in h.cmds if x.kind == "bid" and x.t_ack]
    all_lat = [x.t_ack - x.t_send for x in h.cmds if x.t_ack]
    nom_lat = [x.t_ack - x.t_send for x in h.cmds if x.kind == "nominate" and x.t_ack]
    advice_lat = [lat for lat, st, _, _ in h.advice if st == 200]
    notify_lat = [lat for lat, st in h.notify if st == 200]
    health_lat = [lat for _, lat in h.health if lat is not None]
    base_lat = [lat for _, lat in h.health_baseline if lat is not None]
    sm = h.server_metrics.get("stats", {})
    rows = [
        ("bid command latency", dist(bid_lat)),
        ("nominate command latency", dist(nom_lat)),
        ("all command latency", dist(all_lat)),
        ("propagation: ack -> each other client", dist(prop["per_client"])),
        ("propagation: ack -> ALL 11 other clients", dist(prop["all_clients"])),
        ("reconnect (kill poll -> fresh snapshot)", dist(h.reconnects)),
        ("advice-context GET", dist(advice_lat)),
        ("notify state/inbox GET", dist(notify_lat)),
        ("health ping (idle baseline)", dist(base_lat)),
        ("health ping (under load)", dist(health_lat)),
    ]
    srv_rows = [
        ("server loop lag (in-process 50ms probe)", sm.get("loop_lag")),
        ("sqlite writer-lock wait (process RLock)", sm.get("writer_lock_wait")),
        ("sqlite write acquire (lock+connect+BEGIN IMMEDIATE)", sm.get("write_acquire")),
        ("sqlite write txn body (held)", sm.get("write_hold")),
        ("sqlite COMMIT (+close)", sm.get("write_commit")),
        ("sqlite read connect", sm.get("read_open")),
        ("client-harness loop lag (validity check)", dist(h.client_lag)),
    ]
    print()
    print("=" * 100)
    print(
        f"AUCTION LOAD REHEARSAL  run={h.run_id}  room={h.room}  duration={a.duration:.0f}s  seed={a.seed}"
    )
    print(f"contract: {h.contract_kind}")
    tabs = sum(m.tab_count for m in h.managers)
    print(
        f"clients: {len(h.managers)} managers, {tabs} long-poll tabs, "
        f"{a.bidders_per_manager} bidders/manager, reconnect every {a.reconnect_every}s, "
        f"clock jump {a.clock_jump_seconds}s every {a.clock_jump_every}s"
    )
    print(
        f"opening burst: {h.nomination_setup.get('accepted')}/12 nominations accepted in "
        f"{fmt(h.nomination_setup.get('wall_s'))}; open lots = {h.nomination_setup.get('open_lots')}"
    )
    print("-" * 100)
    print(f"{'metric':<52}{'n':>7}{'p50':>10}{'p95':>10}{'p99':>10}{'max':>10}")
    for name, d in rows + srv_rows:
        d = d or {"n": 0}
        print(
            f"{name:<52}{d.get('n', 0):>7}{fmt(d.get('p50')):>10}{fmt(d.get('p95')):>10}"
            f"{fmt(d.get('p99')):>10}{fmt(d.get('max')):>10}"
        )
    print("-" * 100)
    span = max(1e-9, h.t_load1 - h.t_load0)
    status_by_cat: dict[str, Counter] = defaultdict(Counter)
    for (cat, st), n in h.http_status.items():
        status_by_cat[cat][st] += n
    for cat in sorted(status_by_cat):
        parts = ", ".join(f"{k}:{v}" for k, v in sorted(status_by_cat[cat].items(), key=str))
        print(f"  HTTP {cat:<16} {parts}")
    codes = Counter()
    for (cat, st, code), n in h.error_codes.items():
        codes[f"{cat} {st} {code}"] += n
    print("  rejection codes: " + ", ".join(f"{k}={v}" for k, v in codes.most_common(14)))
    n5 = sum(n for (cat, st), n in h.http_status.items() if isinstance(st, int) and st >= 500)
    n409 = sum(n for (cat, st), n in h.http_status.items() if st == 409)
    n429 = sum(n for (cat, st), n in h.http_status.items() if st == 429)
    ntr = sum(n for (cat, st), n in h.http_status.items() if st == "transport")
    print(
        f"  totals: commands={len(h.cmds)} ({len(h.cmds) / span:.1f}/s)  5xx={n5}  409={n409}  429={n429}"
        f"  transport_errors={ntr} {dict(h.transport_errors) or ''}"
    )
    print(
        f"  retries={h.retries} receipt_lookups={h.receipt_lookups}  idempotency checks={dict(h.replay_checks)}"
    )
    print(
        f"  sqlite: server-side errors={h.server_metrics.get('errors') or {}}  "
        f"'locked' in response bodies={h.locked_bodies}  server log={log_counts}"
    )
    print(
        f"  long-poll: out-of-order responses dropped={h.out_of_order}  unchanged (timeout) returns="
        f"{h.poll_unchanged}  possible event-feed gaps (150-event window overrun)="
        f"{sum(m.event_gaps for m in h.managers)}"
    )
    print(
        f"  missed revisions: (ack, other-client) pairs never observed={prop['missed_pairs']} "
        f"{prop['missed_by_seat'] or ''}; tabs behind final revision after "
        f"{a.drain_seconds:.0f}s drain={len(getattr(h, 'tabs_behind_at_end', []))} "
        f"(final rev {getattr(h, 'final_revision', None)})"
    )
    cpu_vals, rss_vals, fd_vals = [], [], []
    ps = h.proc_samples
    for (t0, s0), (t1, s1) in zip(ps, ps[1:], strict=False):
        if s0.get("cpu_s") is not None and s1.get("cpu_s") is not None and t1 > t0:
            cpu_vals.append(100.0 * (s1["cpu_s"] - s0["cpu_s"]) / (t1 - t0))
    rss_vals = [s["rss"] / 2**20 for _, s in ps if s.get("rss")]
    fd_vals = [s["fds"] for _, s in ps if s.get("fds") is not None]
    if ps:
        print(
            f"  server process ({h.proc_method}): CPU% of one core mean={fmt(sum(cpu_vals) / len(cpu_vals) if cpu_vals else None, '')}"
            f" p95={fmt(pct(cpu_vals, 0.95), '')} max={fmt(max(cpu_vals) if cpu_vals else None, '')};"
            f" RSS MB start={fmt(rss_vals[0] if rss_vals else None, '')} max={fmt(max(rss_vals) if rss_vals else None, '')}"
            f" end={fmt(rss_vals[-1] if rss_vals else None, '')};"
            f" {h.handle_label} start={fd_vals[0] if fd_vals else '-'} max={max(fd_vals) if fd_vals else '-'}"
            f" end={fd_vals[-1] if fd_vals else '-'}; threads max={max(h.server_threads) if h.server_threads else '-'}"
        )
    else:
        print("  server process: CPU/RSS/FDs unavailable (install psutil)")
    adv = Counter(f"{st}/{s}/{r}" for _, st, s, r in h.advice)
    print(f"  advice-context outcomes: {dict(adv)}")
    print(
        f"  room after run: status={db.get('status')} lots total={db.get('lots_total')} "
        f"closed={db.get('lots_closed')} open={db.get('lots_open')} awards={db.get('awards')} "
        f"bid_log={db.get('bid_log_len')} state_json={db.get('state_json_bytes', 0) / 1024:.0f}KB "
        f"revision={db.get('revision')}"
    )
    print("  timeline (10 s buckets): t | commands | bid p95 | health max | server CPU%")
    for r in h.timeline():
        print(
            f"    {r['t']} | {r['cmds']:>5} | {fmt(r['bid_p95']):>7} | {fmt(r['health_max']):>7} |"
            f" {fmt(r['cpu_pct'], ''):>6}"
        )
    print("-" * 100)
    print("INVARIANTS (fresh HTTP read + fresh Store over the file after a hard kill)")
    print(
        f"  engine invariants: {db.get('engine_invariants')}  replay_matches={db.get('replay_matches')}"
        f"  awards_match={db.get('awards_match')}"
    )
    print(
        f"  receipts checked={getattr(h, 'receipts_checked', 0)} bad={getattr(h, 'receipts_bad', 0)};"
        f" lost acknowledged actions (after kill)={db.get('lost_acknowledged')};"
        f" command rows without exactly one accepted receipt={db.get('command_rows_without_single_receipt')}"
    )
    over = [s for s in db.get("seats", []) if s[2] < 0 or s[3] > s[2]]
    print(
        f"  seats (id, opening, balance, committed, spendable): {db.get('seats')}\n"
        f"  overspent seats={len(over)}"
    )
    targets = {
        "bid result p95 < 1 s": (pct(bid_lat, 0.95) or 0) < a.target_bid_p95,
        "accepted state visible to all clients p95 < 2 s": (pct(prop["all_clients"], 0.95) or 0)
        < a.target_visible_p95,
        "zero overspend / duplicate winners / lost acks": not h.violations,
    }
    print("-" * 100)
    for k, ok in targets.items():
        print(f"  TARGET {k:<52} {'PASS' if ok else 'FAIL'}")
    if h.violations:
        print("  VIOLATIONS:")
        for v in h.violations[:40]:
            print(f"    - {v}")
    for n in h.notes:
        print(f"  note: {n}")
    print("=" * 100)
    return {
        "run_id": h.run_id,
        "room": h.room,
        "args": vars(a),
        "contract": h.contract_kind,
        "rows": {k: v for k, v in rows},
        "server": {k: v for k, v in srv_rows},
        "server_metrics": h.server_metrics,
        "http_status": {f"{c}|{s}": n for (c, s), n in h.http_status.items()},
        "rejections": dict(codes),
        "retries": h.retries,
        "receipt_lookups": h.receipt_lookups,
        "idempotency_checks": dict(h.replay_checks),
        "log_counts": log_counts,
        "propagation": {k: v for k, v in prop.items() if k not in ("per_client", "all_clients")},
        "out_of_order": h.out_of_order,
        "event_gaps": sum(m.event_gaps for m in h.managers),
        "tabs_behind_at_end": getattr(h, "tabs_behind_at_end", []),
        "cpu_pct": dist(cpu_vals),
        "rss_mb": dist(rss_vals),
        "fds": dist([float(x) for x in fd_vals]),
        "advice_outcomes": dict(adv),
        "db": db,
        "timeline": h.timeline(),
        "targets": targets,
        "violations": h.violations,
        "commands_sample": [asdict(x) for x in h.cmds[:5]],
    }


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


async def amain(h: Harness) -> tuple[dict, dict, dict]:
    contract = h.prepare_contract()
    h.start_server(contract)
    print(f"[setup] server pid={h.proc.pid} {h.base} store={h.db_path}")
    await h.wait_ready()
    stop = asyncio.Event()
    base_task = asyncio.create_task(h.health_loop(h.health_baseline, stop))
    await asyncio.sleep(3.0)
    stop.set()
    await base_task
    await h.setup()
    print(
        f"[setup] room {h.room}: 12 human seats, {len(h.pool_ids)} pool players, 12 lots open; "
        f"load for {h.a.duration:.0f}s ..."
    )
    await h.run_load()
    await h.verify_http()
    prop = h.propagation()
    return prop, {}, {}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="12-manager load rehearsal for the rookie auction room (LOCAL ONLY).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--duration", type=float, default=120.0, help="load phase seconds")
    ap.add_argument("--seed", type=int, default=20260929)
    ap.add_argument("--tabs-min", type=int, default=2)
    ap.add_argument("--tabs-max", type=int, default=3)
    ap.add_argument("--bidders-per-manager", type=int, default=2)
    ap.add_argument(
        "--bid-interval", type=float, default=0.8, help="mean seconds between commands per bidder"
    )
    ap.add_argument(
        "--burst-every", type=float, default=20.0, help="seconds between bursts (0 = none)"
    )
    ap.add_argument("--burst-seconds", type=float, default=4.0)
    ap.add_argument(
        "--burst-interval",
        type=float,
        default=0.05,
        help="mean seconds between commands in a burst",
    )
    ap.add_argument(
        "--replay-rate",
        type=float,
        default=0.05,
        help="share of accepted commands resent with the same key",
    )
    ap.add_argument(
        "--conflict-rate",
        type=float,
        default=0.01,
        help="share resent with the same key but a different body",
    )
    ap.add_argument("--advice-interval", type=float, default=15.0)
    ap.add_argument("--notify-interval", type=float, default=10.0)
    ap.add_argument("--health-interval", type=float, default=0.1)
    ap.add_argument("--reconnect-every", type=float, default=5.0)
    ap.add_argument(
        "--clock-jump-every", type=float, default=20.0, help="0 disables mock clock jumps"
    )
    ap.add_argument("--clock-jump-seconds", type=float, default=30.0)
    ap.add_argument("--lot-seconds", type=int, default=60, help="auction_active_seconds (min 60)")
    ap.add_argument("--extension-seconds", type=int, default=15)
    ap.add_argument("--poll-wait", type=float, default=25.0)
    ap.add_argument("--drain-seconds", type=float, default=10.0)
    ap.add_argument("--budgets", default="", help="12 comma-separated opening budgets")
    ap.add_argument("--contract", choices=["auto", "export", "synthetic"], default="auto")
    ap.add_argument("--export-path", default="")
    ap.add_argument("--port", type=int, default=0, help="0 = ephemeral")
    ap.add_argument("--startup-timeout", type=float, default=240.0)
    ap.add_argument(
        "--server-log-level", default="info", help="uvicorn log level (production uses info)"
    )
    ap.add_argument("--target-bid-p95", type=float, default=1.0)
    ap.add_argument("--target-visible-p95", type=float, default=2.0)
    ap.add_argument(
        "--strict-targets", action="store_true", help="exit 3 when a latency target is missed"
    )
    ap.add_argument("--json-out", default="")
    ap.add_argument("--keep-tmp", action="store_true")
    args = ap.parse_args(argv)
    if not (1 <= args.tabs_min <= args.tabs_max):
        ap.error("need 1 <= --tabs-min <= --tabs-max")

    h = Harness(args)
    code = EXIT_OK
    out: dict = {}
    try:
        try:
            prop, _, _ = asyncio.run(amain(h))
        except Exception as exc:  # noqa: BLE001
            print(f"[harness] setup/run failure: {type(exc).__name__}: {exc}", file=sys.stderr)
            h.kill_server()
            tail = (
                h.log_path.read_text(encoding="utf-8", errors="replace")[-3000:]
                if h.log_path.exists()
                else ""
            )
            if tail:
                print("[server log tail]\n" + tail, file=sys.stderr)
            return EXIT_SETUP
        h.kill_server()
        db = h.verify_db()
        log_counts = h.scan_log()
        out = report(h, db, log_counts, prop)
        if h.violations:
            code = EXIT_INVARIANT
        elif args.strict_targets and not all(out["targets"].values()):
            code = EXIT_TARGET
        if args.json_out:
            Path(args.json_out).write_text(json.dumps(out, indent=2, default=str), encoding="utf-8")
            print(f"[report] JSON written to {args.json_out}")
    finally:
        if h.proc and h.proc.poll() is None:
            h.kill_server()
        if args.keep_tmp:
            print(f"[cleanup] kept temp dir {h.tmp}")
        else:
            import gc

            gc.collect()  # release any sqlite handles before removing the temp store
            shutil.rmtree(h.tmp, ignore_errors=True)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
