"""ESPN-style fantasy matchup previews and recaps generated by Claude.

Pipeline (5 pure stages, each individually testable):

    Sleeper snapshot ─┐
    NFL news/results ─┼─► build_brief() ─► assemble_prompt() ─► generate_article() ─► save_article()
    prior articles ───┘   (structured)        (system + user)     (Claude API)        (filesystem)

Key design choices:

* **The brief is the contract.** Every downstream layer — prompt
  assembly, the LLM call, the regression tests, the rendered frontend
  card — reads the brief. If the brief is correct, the article will
  reference correct data. If we add a new data source, we add a field
  to the brief; we don't sprinkle ``snapshot`` calls through the
  generator.

* **Anti-repetition is load-bearing.** A weekly column that uses
  identical phrasing each week feels templated within two reads. The
  ``prior_articles`` payload feeds Claude every opening line and
  metaphor used in the previous N articles for the same season, with
  an explicit "do not reuse" instruction. Combined with rotating
  ``angle`` and ``persona`` choices (data-derived, deterministic per
  matchup), this keeps the slate distinct without any human curation.

* **Retrieval is bounded.** A brief, even for a championship round, is
  a few KB of JSON; the prior-articles bundle is also a few KB. Total
  prompt is ~6-10 KB → ~2K input tokens → cheap on Opus 4.7.

* **Storage is filesystem JSON, source-controlled.** League members
  reading articles want them durable across deploys; a missing DB
  shouldn't 404 last season's championship recap. ``exports/narratives/``
  is committed alongside the league's other public artifacts.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import matchup_preview, metrics
from .snapshot import PublicLeagueSnapshot, SeasonSnapshot


# ── Storage ───────────────────────────────────────────────────────────────


_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_NARRATIVES_DIR = _REPO_ROOT / "exports" / "narratives"


def narratives_dir() -> Path:
    """Resolve the narratives root.

    Override with ``LEAGUE_NARRATIVES_DIR`` for tests or staging boxes
    that want to write somewhere ephemeral.
    """
    override = (os.getenv("LEAGUE_NARRATIVES_DIR") or "").strip()
    if override:
        return Path(override).expanduser().resolve()
    return _DEFAULT_NARRATIVES_DIR


def article_path(
    season: str | int,
    week: int,
    matchup_id: int,
    mode: str,
    *,
    base: Path | None = None,
) -> Path:
    """Canonical on-disk path for a generated article.

    Layout: ``<base>/<season>/week-<NN>/<mode>-<matchupId>.json``.
    Zero-padded week so ``ls`` sorts correctly. Mode is ``preview`` or
    ``recap``; both can co-exist for the same matchup (preview written
    Wed, recap written the following Tue).
    """
    root = base or narratives_dir()
    return root / str(season) / f"week-{int(week):02d}" / f"{mode}-{int(matchup_id)}.json"


def save_article(article: dict[str, Any], *, base: Path | None = None) -> Path:
    """Write an article to disk, creating parents. Returns the path."""
    season = article["season"]
    week = int(article["week"])
    matchup_id = int(article["matchupId"])
    mode = article["mode"]
    if mode not in {"preview", "recap"}:
        raise ValueError(f"mode must be 'preview' or 'recap', got {mode!r}")
    path = article_path(season, week, matchup_id, mode, base=base)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(article, indent=2, sort_keys=True), encoding="utf-8")
    return path


def load_article(
    season: str | int,
    week: int,
    matchup_id: int,
    mode: str,
    *,
    base: Path | None = None,
) -> dict[str, Any] | None:
    """Read a previously saved article, or None if it doesn't exist."""
    path = article_path(season, week, matchup_id, mode, base=base)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def list_articles(
    season: str | int | None = None,
    *,
    base: Path | None = None,
) -> list[dict[str, Any]]:
    """Index of every article on disk.

    Used by the frontend list page and the cron generator's
    "what's already done" check.
    """
    root = base or narratives_dir()
    if not root.exists():
        return []
    out: list[dict[str, Any]] = []
    seasons = (
        [str(season)]
        if season is not None
        else sorted(p.name for p in root.iterdir() if p.is_dir())
    )
    for s in seasons:
        sdir = root / s
        if not sdir.exists():
            continue
        for week_dir in sorted(sdir.iterdir()):
            if not week_dir.is_dir() or not week_dir.name.startswith("week-"):
                continue
            try:
                week_num = int(week_dir.name.split("-", 1)[1])
            except (ValueError, IndexError):
                continue
            for fp in sorted(week_dir.glob("*.json")):
                try:
                    payload = json.loads(fp.read_text(encoding="utf-8"))
                except (json.JSONDecodeError, OSError):
                    continue
                out.append(
                    {
                        "season": s,
                        "week": week_num,
                        "mode": payload.get("mode"),
                        "matchupId": payload.get("matchupId"),
                        "title": payload.get("title"),
                        "generatedAt": payload.get("generatedAt"),
                        "path": str(fp.relative_to(root.parent))
                        if fp.is_relative_to(root.parent)
                        else str(fp),
                    }
                )
    return out


# ── Brief assembly ────────────────────────────────────────────────────────


# Round labels used in the brief so the prompt knows whether this is a
# bye-week opener, a regular-season tilt, or the title game. The
# strings are surfaced verbatim in some prompt scaffolding.
_ROUND_LABELS = {
    "regular": "Regular Season",
    "wildcard": "Wild Card",
    "semifinal": "Semifinal",
    "championship": "Championship",
    "consolation": "Consolation",
    "third_place": "Third-Place Game",
    "fifth_place": "Fifth-Place Game",
}


def _bracket_round_for(
    season: SeasonSnapshot,
    matchup_id: int,
    week: int,
    home_rid: int,
    away_rid: int,
) -> tuple[str, bool]:
    """Classify a playoff matchup using the winners/losers brackets.

    Returns ``(round_label, is_championship)``. Falls back to
    ``"regular"`` for non-playoff weeks. The classification looks at
    *which* roster_id pair appears in the bracket; matchup_id alone
    isn't enough because Sleeper resets matchup_id per week.
    """
    if week < season.playoff_week_start:
        return _ROUND_LABELS["regular"], False

    pair = {int(home_rid), int(away_rid)}

    # Winners bracket — the championship is always the last entry with
    # the highest ``r`` and ``p == 1`` placement.
    wb = season.winners_bracket or []
    if wb:
        # Find every bracket entry whose t1/t2 match this pair.
        for entry in wb:
            t1, t2 = entry.get("t1"), entry.get("t2")
            if t1 is None or t2 is None:
                continue
            if {int(t1), int(t2)} == pair:
                placement = entry.get("p")
                round_num = int(entry.get("r") or 0)
                if placement == 1:
                    return _ROUND_LABELS["championship"], True
                if placement == 3:
                    return _ROUND_LABELS["third_place"], False
                # Non-placement bracket entries: classify by round.
                # In a 6-team-bracket dynasty playoff (wks 14-17), r=1
                # is wild-card, r=2 is semifinal, r=3 is championship.
                if round_num >= 3:
                    return _ROUND_LABELS["championship"], True
                if round_num == 2:
                    return _ROUND_LABELS["semifinal"], False
                return _ROUND_LABELS["wildcard"], False

    # Losers bracket — fifth-place / consolation games.
    lb = season.losers_bracket or []
    for entry in lb:
        t1, t2 = entry.get("t1"), entry.get("t2")
        if t1 is None or t2 is None:
            continue
        if {int(t1), int(t2)} == pair:
            placement = entry.get("p")
            if placement == 5:
                return _ROUND_LABELS["fifth_place"], False
            return _ROUND_LABELS["consolation"], False

    # Playoff week but pair not found in either bracket → it's a
    # toilet-bowl / non-bracket matchup.
    return _ROUND_LABELS["consolation"], False


def _multi_week_round(
    season: SeasonSnapshot,
    week: int,
    home_rid: int,
    away_rid: int,
) -> dict[str, Any] | None:
    """If the playoff round spans multiple weeks, return cumulative scoring.

    Sleeper's bracket only stores the final winner; multi-week rounds
    show up as two consecutive weeks with the same (rid_a, rid_b)
    pairing. We walk back from ``week`` collecting prior weeks where
    the same pair faced each other, so a Week-17 championship preview
    can correctly report "trails by 18.43 from Week 16".

    Returns ``None`` for single-week rounds.
    """
    pair = {int(home_rid), int(away_rid)}
    prior: list[dict[str, Any]] = []
    for prev in range(week - 1, season.playoff_week_start - 1, -1):
        entries = season.matchups_by_week.get(prev) or []
        # Build matchup_id groups; only consider real (non-None) ids.
        groups: dict[int, list[dict[str, Any]]] = {}
        for e in entries:
            mid = e.get("matchup_id")
            if mid is None:
                continue
            try:
                groups.setdefault(int(mid), []).append(e)
            except (TypeError, ValueError):
                continue
        matched = False
        for entries_for_id in groups.values():
            if len(entries_for_id) != 2:
                continue
            rids = {metrics.roster_id_of(e) for e in entries_for_id}
            if rids != pair:
                continue
            home_entry = next(
                (e for e in entries_for_id if metrics.roster_id_of(e) == int(home_rid)),
                None,
            )
            away_entry = next(
                (e for e in entries_for_id if metrics.roster_id_of(e) == int(away_rid)),
                None,
            )
            if home_entry is None or away_entry is None:
                continue
            prior.append(
                {
                    "week": prev,
                    "homePoints": round(metrics.matchup_points(home_entry), 2),
                    "awayPoints": round(metrics.matchup_points(away_entry), 2),
                }
            )
            matched = True
            break
        if not matched:
            # Pair didn't continue past this week — round started here.
            break

    if not prior:
        return None

    prior.sort(key=lambda r: r["week"])
    home_total = round(sum(p["homePoints"] for p in prior), 2)
    away_total = round(sum(p["awayPoints"] for p in prior), 2)
    if home_total > away_total:
        leader = "home"
    elif away_total > home_total:
        leader = "away"
    else:
        leader = "tied"
    # Field naming: ``priorTotal*`` is unambiguously the sum of prior
    # weeks only — does NOT include the current week. The brief
    # builder layers ``currentTotal*`` on top for recap mode (where the
    # current week is done and the model wants the final 2-week total
    # to cite). Preview mode leaves currentTotal* unset so the prompt
    # can't accidentally cite a not-yet-played sum.
    return {
        "priorWeeks": prior,
        "priorTotalHome": home_total,
        "priorTotalAway": away_total,
        "priorLeader": leader,
        "priorLead": round(abs(home_total - away_total), 2),
        "weeksInRound": len(prior) + 1,
    }


def _starter_lineup(
    entry: dict[str, Any],
    snapshot: PublicLeagueSnapshot,
    *,
    include_points: bool,
) -> list[dict[str, Any]]:
    """Materialize the starter list with names, positions, and points.

    For previews (``include_points=False``), this is the projected
    starting lineup as Sleeper has it — points are reported but they
    may be 0.0 if the games haven't kicked off. For recaps, points are
    final.
    """
    starters = entry.get("starters") or []
    pp = entry.get("players_points") or {}
    rows: list[dict[str, Any]] = []
    for pid in starters:
        if not pid or pid == "0":
            continue
        try:
            points = float(pp.get(pid) or 0.0)
        except (TypeError, ValueError):
            points = 0.0
        rows.append(
            {
                "playerId": str(pid),
                "playerName": snapshot.player_display(pid),
                "position": snapshot.player_position(pid),
                "points": round(points, 2) if include_points else None,
            }
        )
    return rows


def _bench_top(
    entry: dict[str, Any],
    snapshot: PublicLeagueSnapshot,
    n: int = 5,
) -> list[dict[str, Any]]:
    """Top-``n`` bench scorers (relevant only for recaps)."""
    starters = {str(s) for s in (entry.get("starters") or []) if s}
    pp = entry.get("players_points") or {}
    rows = []
    for pid in entry.get("players") or []:
        s_pid = str(pid)
        if s_pid in starters or s_pid == "0":
            continue
        try:
            points = float(pp.get(s_pid) or 0.0)
        except (TypeError, ValueError):
            points = 0.0
        rows.append(
            {
                "playerId": s_pid,
                "playerName": snapshot.player_display(s_pid),
                "position": snapshot.player_position(s_pid),
                "points": round(points, 2),
            }
        )
    rows.sort(key=lambda r: -r["points"])
    return rows[:n]


def _angle_pool(
    *,
    is_championship: bool,
    is_playoff: bool,
    h2h_total: int,
    multi_week: dict[str, Any] | None,
    cumulative_close: bool,
    underdog_seed_gap: int,
) -> list[str]:
    """Curate a list of viable narrative angles for this matchup.

    The model picks the best fit. We pre-filter to angles that the
    *data* supports — e.g., "comeback-arc" only if a multi-week round
    has someone trailing, "first-meeting" only if H2H total is zero.
    Without this filter, the model invents a pretext to use a fun
    angle that doesn't match the facts ("rivalry game" between teams
    with no series history).
    """
    pool: list[str] = []
    if is_championship:
        pool.append("championship-stakes")
    if h2h_total == 0:
        pool.append("first-meeting")
    elif h2h_total >= 5:
        pool.append("rivalry-grudge")
    if multi_week and multi_week.get("priorLead", 0) >= 15:
        pool.append("comeback-arc")
        pool.append("front-runner-vs-finisher")
    if multi_week and cumulative_close:
        pool.append("razor-thin")
    if underdog_seed_gap >= 3:
        pool.append("david-vs-goliath")
    if is_playoff and not is_championship:
        pool.append("statement-game")
        pool.append("must-win")
    pool.append("vibes-check")  # always a fallback option
    pool.append("managerial-mastery")
    # Dedup while preserving order.
    seen: set[str] = set()
    out: list[str] = []
    for tag in pool:
        if tag not in seen:
            seen.add(tag)
            out.append(tag)
    return out


def _persona_for(season: str, week: int, matchup_id: int) -> str:
    """Pick a deterministic columnist voice based on (season, week, matchup_id).

    Three rotating personas keep the slate's articles distinct in tone
    without manual curation. Because the seed is deterministic, the
    same matchup re-generates with the same persona, so a regenerated
    preview reads with consistent voice.
    """
    seed = hashlib.md5(f"{season}|{week}|{matchup_id}".encode()).digest()[0]
    return ["analyst", "storyteller", "sharp-take"][seed % 3]


_PERSONA_BLURBS = {
    "analyst": (
        "Lead with numbers. Reference points, rank, and matchup-relevant "
        "splits. Calm, precise, slightly dry. Think Bill Barnwell — "
        "no breathless adjectives, but vivid where the data demands."
    ),
    "storyteller": (
        "Lead with a scene or a character. Treat the managers as "
        "protagonists. Use metaphor sparingly but well. Think Wright "
        "Thompson, except this is fantasy and you can be funnier."
    ),
    "sharp-take": (
        "Lead with a clear thesis you'll defend. Be willing to be "
        "wrong. Snappy sentences. One genuinely funny line per article. "
        "Think Bill Simmons in a 600-word mood, not the 8000-word one."
    ),
}


@dataclass
class MatchupBrief:
    """The fully-assembled, LLM-ready brief for one matchup.

    Held as a dataclass for type clarity in the generator path; the
    serialized form (``to_dict()``) is what gets shipped to disk and
    rendered in tests.
    """

    mode: str  # "preview" | "recap"
    season: str
    week: int
    matchup_id: int
    is_playoff: bool
    is_championship: bool
    round_label: str
    league_name: str
    # ``best_ball`` controls whether the prompt allows lineup-decision
    # framing.  Best-ball leagues auto-optimize each week — there is no
    # "started" / "benched" / "biggest bench miss" narrative because
    # the manager doesn't make those calls.  The brief surfaces the
    # flag so the prompt template can tell the model to write about
    # roster construction (drafting / trades / waivers) instead.
    best_ball: bool
    home: dict[str, Any]
    away: dict[str, Any]
    h2h: dict[str, Any]
    multi_week_round: dict[str, Any] | None
    angle_pool: list[str]
    persona: str
    news_context: list[dict[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode": self.mode,
            "season": self.season,
            "week": self.week,
            "matchupId": self.matchup_id,
            "isPlayoff": self.is_playoff,
            "isChampionship": self.is_championship,
            "roundLabel": self.round_label,
            "leagueName": self.league_name,
            "bestBall": self.best_ball,
            "home": self.home,
            "away": self.away,
            "h2h": self.h2h,
            "multiWeekRound": self.multi_week_round,
            "anglePool": self.angle_pool,
            "persona": self.persona,
            "newsContext": self.news_context,
        }


def build_brief(
    snapshot: PublicLeagueSnapshot,
    *,
    season: str,
    week: int,
    matchup_id: int,
    mode: str,
    news_context: list[dict[str, Any]] | None = None,
) -> MatchupBrief | None:
    """Assemble the structured brief.

    Returns ``None`` if the matchup doesn't exist, isn't a real pair,
    or one of the rosters can't be resolved to an owner. The caller
    should treat ``None`` as "skip this matchup" — never generate a
    half-brief.
    """
    if mode not in {"preview", "recap"}:
        raise ValueError(f"mode must be 'preview' or 'recap', got {mode!r}")
    season_snap = snapshot.season_by_year(season)
    if season_snap is None:
        return None
    entries = season_snap.matchups_by_week.get(week) or []
    if not entries:
        return None

    # Best-ball flag drives several downstream choices (bench misses
    # don't apply, prompt template suppresses lineup-decision framing).
    # Pulled from the Sleeper league settings — same field Sleeper uses
    # to drive auto-lineups, so we always agree with what actually
    # happened on the field.
    league_settings = (season_snap.league or {}).get("settings") or {}
    best_ball = bool(league_settings.get("best_ball"))

    # Find the (home, away) entries for this matchup_id.
    pair_entries = [e for e in entries if e.get("matchup_id") == matchup_id]
    if len(pair_entries) != 2:
        return None
    pair_entries.sort(key=lambda e: int(e.get("roster_id") or 0))
    home_entry, away_entry = pair_entries

    home_rid = metrics.roster_id_of(home_entry)
    away_rid = metrics.roster_id_of(away_entry)
    if home_rid is None or away_rid is None:
        return None
    home_owner = metrics.resolve_owner(snapshot.managers, season_snap.league_id, home_rid)
    away_owner = metrics.resolve_owner(snapshot.managers, season_snap.league_id, away_rid)
    if not home_owner or not away_owner:
        return None

    # H2H series + recent form lifted from matchup_preview's helpers.
    h2h_index = matchup_preview._build_h2h_index(snapshot)  # noqa: SLF001 — intentional reuse
    pair_key = matchup_preview._pair_key(home_owner, away_owner)  # noqa: SLF001
    meetings = h2h_index.get(pair_key, [])
    summary = matchup_preview._h2h_summary(meetings, *pair_key)  # noqa: SLF001
    last_5 = matchup_preview._meetings_recent(meetings, n=5)  # noqa: SLF001

    home_form = matchup_preview._recent_form_for_owner(  # noqa: SLF001
        snapshot,
        home_owner,
        season,
        week,
        n=3,
    )
    away_form = matchup_preview._recent_form_for_owner(  # noqa: SLF001
        snapshot,
        away_owner,
        season,
        week,
        n=3,
    )

    # Pre-week standings — lifted from matchup_recap's helper.
    pre = metrics.pre_week_standings(season_snap, snapshot.managers, week)
    pre_lookup = {r["ownerId"]: r for r in pre}
    home_pre = pre_lookup.get(home_owner) or {}
    away_pre = pre_lookup.get(away_owner) or {}

    # Bracket classification.
    round_label, is_championship = _bracket_round_for(
        season_snap,
        matchup_id,
        week,
        home_rid,
        away_rid,
    )
    is_playoff = week >= season_snap.playoff_week_start

    # Multi-week round detection (championship rounds in 2-week
    # leagues, etc.).
    multi_week = None
    if is_playoff:
        multi_week = _multi_week_round(season_snap, week, home_rid, away_rid)

    # Lineups: previews include planned starters with projection-style
    # context (no points), recaps include final scoring + bench.
    include_points = mode == "recap"
    home_lineup = _starter_lineup(home_entry, snapshot, include_points=include_points)
    away_lineup = _starter_lineup(away_entry, snapshot, include_points=include_points)

    # Top-scorer / biggest-bench-miss for recaps only.
    if mode == "recap":
        home_top = max(
            home_lineup,
            key=lambda r: r.get("points") or 0.0,
            default=None,
        )
        away_top = max(
            away_lineup,
            key=lambda r: r.get("points") or 0.0,
            default=None,
        )
        # In best-ball, Sleeper auto-optimizes the lineup so a "bench
        # miss" (best bench scorer outscoring the worst starter) is by
        # construction either zero or a tied-points artifact. Skip the
        # whole computation so the brief doesn't tempt the model with
        # a narrative that doesn't exist in this format.
        if best_ball:
            home_bench = away_bench = []
            home_miss = away_miss = None
        else:
            home_bench = _bench_top(home_entry, snapshot, n=5)
            away_bench = _bench_top(away_entry, snapshot, n=5)
            home_miss = (
                home_bench[0]
                if home_bench
                and home_top
                and home_bench[0]["points"] > (home_top.get("points") or 0.0)
                else None
            )
            away_miss = (
                away_bench[0]
                if away_bench
                and away_top
                and away_bench[0]["points"] > (away_top.get("points") or 0.0)
                else None
            )
        home_points = round(metrics.matchup_points(home_entry), 2)
        away_points = round(metrics.matchup_points(away_entry), 2)
    else:
        home_top = away_top = None
        home_bench = away_bench = []
        home_miss = away_miss = None
        home_points = away_points = None

    # Seed context — final regular-season standings rank both teams
    # going into the playoffs, so we know if this is a 1-vs-2 or a
    # 6-vs-3 underdog story.
    standings = metrics.season_standings(season_snap, snapshot.managers)
    seed_lookup = {r["ownerId"]: i + 1 for i, r in enumerate(standings)}
    home_seed = seed_lookup.get(home_owner)
    away_seed = seed_lookup.get(away_owner)
    seed_gap = abs((home_seed or 0) - (away_seed or 0))

    # Cumulative-close detection: a multi-week round where the leader
    # has a smaller cushion than a typical single-week swing (roughly
    # two stdevs of weekly variance ≈ 50 pts in a TE-premium IDP
    # league).  Tunable but stable enough in practice.
    cumulative_close = bool(multi_week and multi_week.get("priorLead", 0.0) <= 50.0)

    # Layer current-week totals onto the multi-week block when this is
    # a recap (current week is final). Preview mode deliberately leaves
    # currentTotal* unset — the model can't cite scores that don't exist.
    if multi_week and mode == "recap" and home_points is not None and away_points is not None:
        ct_home = round(multi_week["priorTotalHome"] + home_points, 2)
        ct_away = round(multi_week["priorTotalAway"] + away_points, 2)
        multi_week["currentTotalHome"] = ct_home
        multi_week["currentTotalAway"] = ct_away
        if ct_home > ct_away:
            multi_week["currentLeader"] = "home"
        elif ct_away > ct_home:
            multi_week["currentLeader"] = "away"
        else:
            multi_week["currentLeader"] = "tied"
        multi_week["currentMargin"] = round(abs(ct_home - ct_away), 2)

    angle_pool = _angle_pool(
        is_championship=is_championship,
        is_playoff=is_playoff,
        h2h_total=summary.get("totalMeetings", 0),
        multi_week=multi_week,
        cumulative_close=cumulative_close,
        underdog_seed_gap=seed_gap,
    )
    persona = _persona_for(season, week, matchup_id)

    def _side_block(
        owner_id: str,
        rid: int,
        seed: int | None,
        pre_rec: dict[str, Any],
        form: dict[str, Any],
        lineup: list[dict[str, Any]],
        bench: list[dict[str, Any]],
        top_scorer: dict[str, Any] | None,
        biggest_miss: dict[str, Any] | None,
        points: float | None,
    ) -> dict[str, Any]:
        return {
            "ownerId": owner_id,
            "rosterId": rid,
            "displayName": metrics.display_name_for(snapshot, owner_id),
            "teamName": metrics.team_name(snapshot, season_snap.league_id, rid),
            "playoffSeed": seed,
            "preWeekRecord": {
                "wins": pre_rec.get("wins", 0),
                "losses": pre_rec.get("losses", 0),
                "ties": pre_rec.get("ties", 0),
                "winPct": pre_rec.get("winPct", 0.0),
                "standing": pre_rec.get("standing"),
                "pointsFor": pre_rec.get("pointsFor", 0.0),
            }
            if pre_rec
            else None,
            "recentForm": form,
            "starters": lineup,
            "topBench": bench,
            "topScorer": top_scorer,
            "biggestBenchMiss": biggest_miss,
            "points": points,
        }

    home_block = _side_block(
        home_owner,
        home_rid,
        home_seed,
        home_pre,
        home_form,
        home_lineup,
        home_bench,
        home_top,
        home_miss,
        home_points,
    )
    away_block = _side_block(
        away_owner,
        away_rid,
        away_seed,
        away_pre,
        away_form,
        away_lineup,
        away_bench,
        away_top,
        away_miss,
        away_points,
    )

    h2h_block = {
        "totalMeetings": summary.get("totalMeetings", 0),
        "homeWins": summary.get("sideAWins", 0)
        if pair_key[0] == home_owner
        else summary.get("sideBWins", 0),
        "awayWins": summary.get("sideBWins", 0)
        if pair_key[0] == home_owner
        else summary.get("sideAWins", 0),
        "ties": summary.get("ties", 0),
        "avgMargin": summary.get("avgMargin", 0.0),
        "biggestMargin": summary.get("biggestMargin", 0.0),
        "playoffMeetings": summary.get("playoffMeetings", 0),
        "last5": last_5,
    }

    league_name = str((season_snap.league or {}).get("name") or "")

    return MatchupBrief(
        mode=mode,
        season=str(season),
        week=int(week),
        matchup_id=int(matchup_id),
        is_playoff=is_playoff,
        is_championship=is_championship,
        round_label=round_label,
        league_name=league_name,
        best_ball=best_ball,
        home=home_block,
        away=away_block,
        h2h=h2h_block,
        multi_week_round=multi_week,
        angle_pool=angle_pool,
        persona=persona,
        news_context=news_context or [],
    )


# ── Prompt assembly ───────────────────────────────────────────────────────


_SYSTEM_PROMPT_TEMPLATE = """\
You are an ESPN-style fantasy football columnist for the dynasty league \
"{league_name}" — a TE-premium, IDP-heavy superflex format with 12 managers \
who have been together long enough to have real history. Your job: write \
weekly matchup previews (Wednesday) and recaps (Tuesday) that feel like \
the league has its own beat writer.

{format_blurb}

Voice this week — {persona}:
{persona_blurb}

Rules of the road:

* Treat the data in the brief as ground truth. Do not invent stats, scores, \
  injuries, or NFL game results that are not in the brief or news context.
* Reference real player names, positions, and points exactly as they appear \
  in the brief. When you cite a fantasy point total, it must match.
* Pick ONE narrative angle from the suggested pool. The brief filters the \
  pool to angles the data supports — don't reach outside it.
* Avoid every template phrase, opener, and metaphor used in the prior \
  articles list. Do not start with "It's that time of week again," "All eyes \
  on," "When all was said and done," or any variant. Find a fresh way in.
* When the news context surfaces a real-world NFL detail relevant to a \
  player on either roster (a Sunday-night injury, a coaching change, a \
  divisional rivalry), weave it in. When it doesn't, don't fake one.
* Length: 550-750 words. Tight, not padded. One ledetic opener (max 2 \
  sentences), 3-5 body beats, and a one-line bold prediction (preview) or a \
  one-line league-history-stake summary (recap).
* Output JSON only, with this shape:
  {{
    "title": "<headline, ≤80 chars>",
    "lede": "<the 1-2 sentence opener>",
    "body": "<the rest of the article — markdown allowed: paragraphs, **bold**, *italics*, blockquotes, but no headers>",
    "kicker": "<the one-line bold prediction or stake — ≤180 chars>",
    "angleUsed": "<one of the angles from anglePool>",
    "wordCount": <int — your own count of body+lede>
  }}
* Do not include any text outside the JSON object.
"""


# Format-specific narrative guardrails. Best-ball leagues auto-optimize
# the lineup each week — there is no start/sit decision for the manager
# to make and no "biggest bench miss" arc — so any framing that implies
# the manager benched a player or chose between two skill-position options
# is wrong on its face. The model needs to be told this explicitly because
# its prior on "fantasy football article" is overwhelmingly weighted
# toward managed-lineup formats.
_FORMAT_BLURB_BEST_BALL = """\
This is a BEST-BALL league. Sleeper auto-selects the optimal lineup each \
week from each manager's roster — managers do not set or change their \
starting lineups during the week. That means:

* DO NOT write that any manager "started", "benched", or "sat" a player. \
  They didn't.
* DO NOT speculate about lineup decisions, roster activations, or last-minute \
  flex calls. There aren't any.
* DO NOT reference "biggest bench misses" or "left points on the bench." \
  Best-ball makes those concepts moot — Sleeper already optimized.
* DO talk about ROSTER CONSTRUCTION: who they drafted, who they traded \
  for, who they grabbed off waivers. That's the entire game in best-ball, \
  and it's where the manager's actual fingerprints are.
* DO talk about the bottom-line score, who scored what, and how players \
  on each roster performed in their real NFL games — the brief shows you \
  the auto-optimized lineup that produced the score.
"""

_FORMAT_BLURB_MANAGED = """\
This is a managed-lineup league — managers set their starters each week \
and live with the consequences. Lineup decisions, biggest bench misses, \
and start/sit calls are fair game in the narrative.
"""


# Week 1 (and any week whose recent-form window lies entirely in a
# previous season) hands the model a ``record``/``avgPoints`` pair that
# describes LAST season. Every game in that window is prior-season by
# construction — including the championship, which is the most
# quotable and the most misleading. Without this the model has the
# per-game ``season`` fields available but no instruction to use them,
# and the natural phrasing ("averaging 118 a week") silently asserts
# current-season form that does not exist yet.
_PRIOR_SEASON_FORM_BLURB = """\
IMPORTANT — RECENT FORM IS FROM A PREVIOUS SEASON. For {sides}, every \
game in the ``recentForm`` window predates this season. There is no \
current-season form yet.

* DO label it explicitly: "last season", "closed 2025 with", "their \
  final three of a year ago". The per-game ``season`` field tells you \
  which year each result belongs to.
* DO NOT write ``record`` or ``avgPoints`` as though they describe this \
  season, and do not write "coming off" or "riding a streak" without \
  saying which season it was.
* DO NOT invent current-season stats to fill the gap. A season that has \
  not started has no results, and that is itself the story.
"""


_PRIOR_OPENERS_BLURB = """\
Here are the opening lines (and headline) of every recent article you've \
written for this league. DO NOT reuse phrasing, structure, or metaphor from \
any of these. Match the voice; vary the entry. If you find yourself writing \
something that echoes any of these, rewrite.
"""


def _format_prior_articles(prior: list[dict[str, Any]]) -> str:
    if not prior:
        return "(no prior articles in this season — first one)"
    lines = [_PRIOR_OPENERS_BLURB, ""]
    for art in prior:
        title = (art.get("title") or "").strip()
        lede = (art.get("lede") or "").strip()
        gen = art.get("generatedAt") or ""
        season = art.get("season") or ""
        week = art.get("week") or ""
        mode = art.get("mode") or ""
        lines.append(f"[{season} W{week} {mode} | {gen}]")
        if title:
            lines.append(f"  Title: {title}")
        if lede:
            lines.append(f"  Lede:  {lede}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def assemble_prompt(
    brief: MatchupBrief,
    *,
    prior_articles: list[dict[str, Any]] | None = None,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Build (system_blocks, messages) for the Anthropic SDK.

    The system block uses a cache_control breakpoint at the end so the
    static rules-of-the-road portion caches across articles within an
    hour. The brief and prior-articles bundle change per request and
    aren't cacheable.
    """
    persona = brief.persona
    format_blurb = _FORMAT_BLURB_BEST_BALL if brief.best_ball else _FORMAT_BLURB_MANAGED
    system_text = _SYSTEM_PROMPT_TEMPLATE.format(
        league_name=brief.league_name or "Risk It To Get The Brisket",
        format_blurb=format_blurb,
        persona=persona,
        persona_blurb=_PERSONA_BLURBS.get(persona, _PERSONA_BLURBS["analyst"]),
    )
    # System block: cache the rules-of-the-road across articles.
    system_blocks: list[dict[str, Any]] = [
        {
            "type": "text",
            "text": system_text,
            "cache_control": {"type": "ephemeral", "ttl": "1h"},
        },
    ]

    # User message: brief + prior articles.
    brief_json = json.dumps(brief.to_dict(), indent=2, sort_keys=True)
    prior_text = _format_prior_articles(prior_articles or [])

    mode_directive = {
        "preview": (
            "Write the PREVIEW for this matchup. Tense: future / "
            "anticipatory. The kicker is a one-line bold prediction "
            "(score or storyline you're staking your week on)."
        ),
        "recap": (
            "Write the RECAP for this matchup. Tense: past. The kicker "
            "is a one-line summary of what this result means for the "
            "league's history this season."
        ),
    }[brief.mode]

    # Goes in the USER message, not the cached system block: whether the
    # form window is prior-season depends on the week being written, so
    # caching it across articles would apply Week 1's instruction to
    # Week 5.
    prior_form_sides = [
        label
        for label, side in (("the home team", brief.home), ("the away team", brief.away))
        if (side.get("recentForm") or {}).get("isPriorSeasonOnly")
    ]
    prior_form_directive = ""
    if prior_form_sides:
        prior_form_directive = (
            _PRIOR_SEASON_FORM_BLURB.format(sides=" and ".join(prior_form_sides)) + "\n"
        )

    user_text = (
        f"{mode_directive}\n\n"
        f"{prior_form_directive}"
        f"=== MATCHUP BRIEF ===\n{brief_json}\n\n"
        f"=== PRIOR ARTICLES (anti-repetition source) ===\n{prior_text}\n"
    )

    messages: list[dict[str, Any]] = [
        {"role": "user", "content": user_text},
    ]
    return system_blocks, messages


# ── Generation ────────────────────────────────────────────────────────────


_MODEL_ID = "claude-opus-4-7"
_MAX_TOKENS = 4096
_EFFORT = "high"


async def generate_article(
    *,
    client: Any,
    brief: MatchupBrief,
    prior_articles: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Call Claude and return the article dict ready to persist.

    Output schema (also what gets saved to disk):
        {
            mode, season, week, matchupId,    # identity (mirrors brief)
            isChampionship, roundLabel,
            home: {ownerId, displayName, teamName},
            away: {ownerId, displayName, teamName},
            title, lede, body, kicker,
            angleUsed, persona,
            wordCount,
            model, generatedAt,
            usage: {input_tokens, output_tokens, cache_*}
        }

    Raises ``RuntimeError`` if Claude returns malformed JSON. Callers
    should catch and either retry or surface an error so we don't
    silently persist a broken article.
    """
    system_blocks, messages = assemble_prompt(brief, prior_articles=prior_articles)

    # The SDK ``messages.create`` is awaitable on AsyncAnthropic.
    response = await client.messages.create(
        model=_MODEL_ID,
        max_tokens=_MAX_TOKENS,
        thinking={"type": "adaptive"},
        output_config={"effort": _EFFORT},
        system=system_blocks,
        messages=messages,
    )

    # Concatenate all text blocks into one string. Claude with
    # ``thinking`` enabled emits a thinking block first then a text
    # block; we only want the text.
    raw_text = ""
    for block in response.content or []:
        block_type = getattr(block, "type", None)
        if block_type == "text":
            raw_text += getattr(block, "text", "") or ""
    raw_text = raw_text.strip()

    # The model is instructed to emit JSON only. If it wraps in
    # ```json fences (occasional drift), peel them.
    if raw_text.startswith("```"):
        raw_text = raw_text.strip("`")
        if raw_text.lower().startswith("json"):
            raw_text = raw_text[4:].lstrip()
    try:
        article_obj = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Claude returned malformed JSON for {brief.mode} "
            f"{brief.season}-W{brief.week}-M{brief.matchup_id}: {exc}\n"
            f"---\n{raw_text[:1500]}"
        ) from exc

    usage = getattr(response, "usage", None)
    usage_block = {}
    if usage is not None:
        usage_block = {
            "input_tokens": getattr(usage, "input_tokens", 0),
            "output_tokens": getattr(usage, "output_tokens", 0),
            "cache_read_input_tokens": getattr(usage, "cache_read_input_tokens", 0) or 0,
            "cache_creation_input_tokens": getattr(usage, "cache_creation_input_tokens", 0) or 0,
        }

    return {
        "mode": brief.mode,
        "season": brief.season,
        "week": brief.week,
        "matchupId": brief.matchup_id,
        "isChampionship": brief.is_championship,
        "roundLabel": brief.round_label,
        "home": {
            "ownerId": brief.home["ownerId"],
            "displayName": brief.home["displayName"],
            "teamName": brief.home["teamName"],
        },
        "away": {
            "ownerId": brief.away["ownerId"],
            "displayName": brief.away["displayName"],
            "teamName": brief.away["teamName"],
        },
        "title": article_obj.get("title") or "",
        "lede": article_obj.get("lede") or "",
        "body": article_obj.get("body") or "",
        "kicker": article_obj.get("kicker") or "",
        "angleUsed": article_obj.get("angleUsed") or "",
        "persona": brief.persona,
        "wordCount": int(article_obj.get("wordCount") or 0),
        "model": _MODEL_ID,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "usage": usage_block,
    }


def collect_prior_articles(
    season: str | int,
    *,
    n: int = 6,
    base: Path | None = None,
) -> list[dict[str, Any]]:
    """Return the most recent N article dicts from the same season.

    Used as the anti-repetition payload for the next generation. Sort
    is reverse-chronological by (week, mode-precedence) so the freshest
    articles' phrasing weighs most against new output.
    """
    items = list_articles(season=str(season), base=base)
    if not items:
        return []
    # Mode precedence: recap (Tue) is fresher than preview (Wed of same week).
    mode_order = {"recap": 1, "preview": 0}
    items.sort(
        key=lambda r: (int(r.get("week") or 0), mode_order.get(r.get("mode"), -1)),
        reverse=True,
    )
    out: list[dict[str, Any]] = []
    for entry in items[:n]:
        full = load_article(
            entry["season"],
            entry["week"],
            entry["matchupId"],
            entry["mode"],
            base=base,
        )
        if not full:
            continue
        out.append(
            {
                "season": full.get("season"),
                "week": full.get("week"),
                "mode": full.get("mode"),
                "title": full.get("title"),
                "lede": full.get("lede"),
                "generatedAt": full.get("generatedAt"),
            }
        )
    return out


# ── Convenience: enumerate matchups for a (season, week) ─────────────────


def enumerate_week_matchups(
    snapshot: PublicLeagueSnapshot,
    season: str,
    week: int,
) -> list[int]:
    """Return matchup_ids that have a real (2-roster) pairing for the week.

    The cron generator iterates this list to know which articles to
    produce. Skips bye-week placeholders and incomplete entries.
    """
    season_snap = snapshot.season_by_year(season)
    if season_snap is None:
        return []
    entries = season_snap.matchups_by_week.get(week) or []
    groups: dict[int, list[dict[str, Any]]] = {}
    for e in entries:
        mid = e.get("matchup_id")
        if mid is None:
            continue
        try:
            groups.setdefault(int(mid), []).append(e)
        except (TypeError, ValueError):
            continue
    return sorted(mid for mid, ents in groups.items() if len(ents) == 2)
