from __future__ import annotations

from typing import Final

PARSER_VERSION: Final[str] = "mike_clay_pdf_v1.0.0"
IMPORT_PIPELINE_VERSION: Final[str] = "mike_clay_import_v1.1.0"

TEAM_GUIDE_TO_CANONICAL: Final[dict[str, str]] = {
    "ARZ": "ARI",
    "ATL": "ATL",
    "BLT": "BAL",
    "BUF": "BUF",
    "CAR": "CAR",
    "CHI": "CHI",
    "CIN": "CIN",
    "CLV": "CLE",
    "DAL": "DAL",
    "DEN": "DEN",
    "DET": "DET",
    "GB": "GB",
    "HST": "HOU",
    "IND": "IND",
    "JAX": "JAX",
    "KC": "KC",
    "LAC": "LAC",
    "LAR": "LAR",
    "LV": "LV",
    "MIA": "MIA",
    "MIN": "MIN",
    "NE": "NE",
    "NO": "NO",
    "NYG": "NYG",
    "NYJ": "NYJ",
    "PHI": "PHI",
    "PIT": "PIT",
    "SEA": "SEA",
    "SF": "SF",
    "TB": "TB",
    "TEN": "TEN",
    "WAS": "WAS",
}

TEAM_CANONICAL_ALIASES: Final[dict[str, str]] = {
    "ARZ": "ARI",
    "BLT": "BAL",
    "CLV": "CLE",
    "HST": "HOU",
}

TEAM_NAME_TO_CANONICAL: Final[dict[str, str]] = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KC",
    "Las Vegas Raiders": "LV",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Francisco 49ers": "SF",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS",
}

CANONICAL_TO_TEAM_NAME: Final[dict[str, str]] = {
    v: k for k, v in TEAM_NAME_TO_CANONICAL.items()
}

POS_SOURCE_TO_CANONICAL: Final[dict[str, str]] = {
    "QB": "QB",
    "RB": "RB",
    "WR": "WR",
    "TE": "TE",
    "DI": "DL",
    "DT": "DL",
    "DE": "DL",
    "DL": "DL",
    "ED": "DL",
    "EDGE": "DL",
    "LB": "LB",
    "ILB": "LB",
    "OLB": "LB",
    "CB": "DB",
    "S": "DB",
    "FS": "DB",
    "SS": "DB",
    "DB": "DB",
    "K": "K",
    "OL": "OL",
}

MATCH_STATUS_VALUES: Final[set[str]] = {
    "exact_match",
    "deterministic_match",
    "fuzzy_match_reviewed",
    "unresolved",
    "ambiguous_duplicate",
}

READINESS_MIN_PARSE_SUCCESS_RATE: Final[float] = 0.88
READINESS_MIN_MATCH_RATE: Final[float] = 0.60
LOW_CONFIDENCE_THRESHOLD: Final[float] = 0.90

# Page 46..55 are defender pages in this guide order.
IDP_SECTION_ORDER: Final[list[str]] = [
    "DI",
    "DI",
    "ED",
    "ED",
    "LB",
    "LB",
    "CB",
    "CB",
    "S",
    "S",
]

STARTER_SLOT_TOKENS: Final[set[str]] = {
    "QB1",
    "QB2",
    "RB1",
    "RB2",
    "WR1",
    "WR2",
    "WR3",
    "WR4",
    "TE1",
    "TE2",
    "TE3",
    "LT",
    "LG",
    "C",
    "RG",
    "RT",
    "DI1",
    "DI2",
    "DI3",
    "ED1",
    "ED2",
    "ED3",
    "LB1",
    "LB2",
    "LB3",
    "CB1",
    "CB2",
    "CB3",
    "CB4",
    "S1",
    "S2",
    "S3",
}

STARTER_SLOT_TO_POS: Final[dict[str, str]] = {
    "QB1": "QB",
    "QB2": "QB",
    "RB1": "RB",
    "RB2": "RB",
    "WR1": "WR",
    "WR2": "WR",
    "WR3": "WR",
    "WR4": "WR",
    "TE1": "TE",
    "TE2": "TE",
    "TE3": "TE",
    "LT": "OL",
    "LG": "OL",
    "C": "OL",
    "RG": "OL",
    "RT": "OL",
    "DI1": "DL",
    "DI2": "DL",
    "DI3": "DL",
    "ED1": "DL",
    "ED2": "DL",
    "ED3": "DL",
    "LB1": "LB",
    "LB2": "LB",
    "LB3": "LB",
    "CB1": "DB",
    "CB2": "DB",
    "CB3": "DB",
    "CB4": "DB",
    "S1": "DB",
    "S2": "DB",
    "S3": "DB",
}
